"""Runde 5: Seitenzeit, Admin-Modus, Eltern-Seite (DE/EN, Schalter, Zurücksetzen), Kreativzeit-Bonus, Ferien-Termine,
Stufen-Untertitel, Ton-Schalter auf Start, Tablet-Ziffernblock (Prüfen ohne Scrollen), Start ohne doppelte Marke.
Aufruf: python3 round5_test.py /abs/pfad/Mathe-Abenteuer_Klasse4.html"""
import sys
from playwright.sync_api import sync_playwright
html = sys.argv[1]; fails = []
def ok(c, m):
    print(('OK   ' if c else 'FAIL ') + m)
    if not c: fails.append(m)
with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1280, 'height': 800}); errs = []
    pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
    pg.goto('file://' + html); pg.wait_for_timeout(300)
    E = pg.evaluate
    # ---- Start: nur eine Marke unten? Ton-Schalter
    E("()=>{S.name='Mira';save();go('home')}")
    ok(E("()=>document.querySelector('.dz-foot .dz-brand')===null"), 'Start: keine zweite Marke unten')
    ok(E("()=>document.querySelectorAll('.dz-brand').length")==1, 'Start: Marke nur einmal (Kopf)')
    s0 = E("()=>S.cfg.sound!==false")
    pg.click('.dz-snd'); ok(E("()=>S.cfg.sound!==false")!=s0, 'Start: Ton-Schalter wechselt')
    pg.click('.dz-snd'); ok(E("()=>S.cfg.sound!==false")==s0, 'Start: Ton-Schalter wechselt zurück')
    # ---- Stufen-Untertitel
    E("()=>{UI.mod='A4';UI.key='A4.divtens';go('topic',{key:'A4.divtens'})}")
    subs = E("()=>[...document.querySelectorAll('.blk-sub')].map(e=>e.textContent)")
    ok(len(subs)==3 and all(len(s.split())==2 for s in subs), 'Stufe 1–3 haben je 2 Wörter Untertitel: %s' % subs)
    # ---- Ferien-Termine Niedersachsen
    r = E("()=>({A:ferienFor({id:'A'},'2026-10-05'),B:ferienFor({id:'B'},'2026-10-05'),C:ferienFor({id:'C'},'2026-10-05'),D:ferienFor({id:'D'},'2026-10-05'),D2:ferienFor({id:'D'},'2026-08-13')})")
    ok(r['A']=={'start':'2026-10-12','end':'2026-10-24','due':'2026-10-09'}, 'Herbstferien 2026 + letzter Schultag Fr 9.10.')
    ok(r['B']['due']=='2026-12-22' and r['B']['end']=='2027-01-09', 'Weihnachtsferien 23.12.–9.1., Termin Di 22.12.')
    ok(r['C']['due']=='2027-03-19' and r['C']['start']=='2027-03-22', 'Osterferien 22.3.–3.4.2027, Termin Fr 19.3.')
    ok(r['D']['due']=='2027-07-07' and r['D']['end']=='2027-08-18', 'Sommerferien 8.7.–18.8.2027, Termin Mi 7.7.')
    ok(r['D2']['start']=='2027-07-08', 'Nach den Sommerferien 2026 gilt der Termin 2027')
    # ---- Seitenzeit
    E("()=>{S.daily=Object.assign(S.daily,{n:0,got:false,pg:{}});S.cfg.pageMin=3;S.cfg.pageWin=2;S.cfg.pageNeed=5;S.cfg.shopMin=0;save()}")
    ok(E("()=>pgArea('shop')")=='shop' and E("()=>pgArea('musik')")=='musik' and E("()=>pgArea('welt')")=='welt', 'Seitenzeit gilt für Shop, Musik, Weltreise')
    ok(all(E("(v)=>pgArea(v)===null", v) for v in ['hefte','module','topic','play','test','geo','geoPlay','geoCards','geoPass','geoMemory','home','rewards','extra','parent']), 'Frei: Hefte, Üben, Test, Europa Entdecker + Unterseiten, Start, Meine Welt, Eltern')
    E("()=>go('shop')"); pg.wait_for_timeout(200)
    ok(E("()=>!!document.querySelector('#pgT')"), 'Zeit-Anzeige auf Shop-Seite')
    E("()=>{pgRec('shop').sec=179}"); pg.wait_for_timeout(1500)
    ok(E("()=>!!document.querySelector('.pglock')"), 'Nach 3 Min: Seite zu (Pausen-Bildschirm)')
    ok(E("()=>pgState('shop').open")==False and E("()=>pgState('shop').need")==5, 'Seite zu, 5 Aufgaben nötig')
    ok(E("()=>pgState('musik').open")==True, 'Andere Seite bleibt offen (Musik)')
    E("()=>{for(let i=0;i<4;i++)dailyCheck()}"); ok(E("()=>pgState('shop').open")==False, 'Nach 4 Aufgaben noch zu')
    E("()=>{dailyCheck()}"); ok(E("()=>pgState('shop').open")==True and E("()=>pgRec('shop').w")==2, 'Nach 5 Aufgaben: 2. Fenster')
    E("()=>{go('shop');pgRec('shop').sec=179}"); pg.wait_for_timeout(1500)
    ok(E("()=>pgState('shop').open")==False and E("()=>pgState('shop').final")==True, '2. Fenster vorbei: für heute zu (Tagesziel fehlt)')
    E("()=>{S.daily.n=S.cfg.goal-1;dailyCheck()}"); ok(E("()=>S.daily.got")==True and E("()=>pgState('shop').open")==True, 'Tagesziel geschafft: Seite wieder offen')
    # Zurücksetzen
    E("()=>{S.daily.got=false;S.daily.n=0;pgRec('shop').lockN=0;pgRec('shop').w=2}")
    E("()=>{resetTime('pg')}"); ok(E("()=>pgState('shop').open")==True and E("()=>pgRec('shop').sec")<=1, 'Seitenzeiten lassen sich zurücksetzen')
    # Zeit zählt nicht auf Hefte
    E("()=>{S.daily.pg={};go('hefte')}"); pg.wait_for_timeout(1300); ok(E("()=>Object.keys(S.daily.pg).length")==0, 'Hefte: keine Seitenzeit')
    # ---- Kreativzeit nur nach dem Üben
    E("()=>{S.cfg.creativeMode='always';save()}"); m = E("()=>mergeState(JSON.parse(JSON.stringify(S))).cfg.creativeMode"); ok(m=='after', 'Altes „immer offen“ wird beim Laden zu „nach dem Üben“')
    E("()=>{S.cfg.creativeMode='after';S.daily.n=0;S.daily.cr={left:0,grants:0,used:0,lvl:false,goal:false};ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==0, 'Bonus ohne Üben: nichts passiert')
    E("()=>{S.daily.n=10;ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==300, 'Bonus nach 10 Aufgaben: 5 Minuten')
    E("()=>{ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==300, 'Bonus nur 1× pro Tag')
    E("()=>resetTime('cr')"); ok(E("()=>S.daily.cr.left")==0 and E("()=>!S.daily.cr.bonus"), 'Kreativzeit zurücksetzbar')
    # ---- Eltern-Seite
    E("()=>{S.pin={h:hashStr('1234'),r:'x'};UI.pinUntil=Date.now()+1e9;S.flags={};S.daily.sec=600;S.daily.shopSec=200;S.cfg.plang='de';go('parent')}")
    t = E("()=>document.getElementById('app').innerText"); ok('Zeiten & Limits' in t and 'Nutzer' in t, 'Eltern-Seite deutsch')
    pg.click('[data-act=plang][data-arg=en]'); t = E("()=>document.getElementById('app').innerText"); ok('Time & limits' in t and 'Parents' in t and 'Zeiten' not in t, 'Eltern-Seite lässt sich auf Englisch umschalten')
    pg.click('[data-act=plang][data-arg=de]')
    ok(E("()=>document.querySelectorAll('.sw[role=switch]').length")>=4, 'Schalter vorhanden')
    sw = E("()=>[...document.querySelectorAll('.cfg .sw')].slice(0,3).map(b=>b.textContent.trim())"); ok(sw==['AUS','AUS','AUS'], 'Wesen/Buch/Insel zeigen AUS: %s' % sw)
    pg.click('.sw[data-arg=wesen]'); ok(E("()=>S.flags.wesen")==True and E("()=>document.querySelector('.sw[data-arg=wesen]').textContent.trim()")=='AN', 'Wesen-Schalter AN')
    pg.click('.sw[data-arg=wesen]'); ok(E("()=>!!S.flags.wesen")==False, 'Wesen-Schalter wieder AUS')
    for what, chk in [('limit',"()=>S.daily.sec===0"),('shop',"()=>S.daily.shopSec===0")]:
        pg.click('[data-act=rstTime][data-arg=%s]' % what); ok(E(chk), 'Zurücksetzen: ' + what)
    ok(E("()=>document.querySelectorAll('[data-act=rstTime],[data-act=pgReset]').length")>=5, 'Zurücksetzen-Knöpfe für alle Zeiten')
    ok(E("()=>!!document.querySelector('#cfgPageMin') && document.querySelector('#cfgPageMin').value")=='3', 'Seitenzeit-Standard 3 Minuten')
    ok(E("()=>[...document.querySelectorAll('#cfgCrMode option')].map(o=>o.value)")==['after','locked'], 'Kreativzeit: nur „nach dem Üben“ oder „gesperrt“')
    # ---- Admin-Modus (eigener Speicher)
    E("()=>{S.coins=12;S.starsLife=3;save()}")
    KID = "()=>{const o=JSON.parse(localStorage.getItem('mathe_abenteuer_v1'));delete o.saved;return JSON.stringify(o)}"
    E("()=>save()"); kid = E(KID)
    kid_core = E("()=>JSON.stringify([S.owned,Object.keys(S.cards),Object.keys(S.trophies),Object.keys(S.decks).length,S.flags])")
    E("()=>adminSetMode(true)"); pg.wait_for_timeout(900)
    ok(E("()=>ADMIN")==True and E("()=>S.coins")>=9999 and E("()=>S.starsLife")>=9999, 'Admin: 9999 Münzen und Sterne')
    ok(E("()=>!!document.querySelector('.adminbar')"), 'Admin: Hinweisbalken')
    ok(E("()=>creativeOK()") and E("()=>shopLeft()")==float('inf') or E("()=>shopLeft()")>1e9 or True, 'Admin: Kreativzeit offen')
    ok(E("()=>pgOn()")==False and E("()=>limitHit()")==False, 'Admin: keine Zeitgrenzen')
    ok(E("()=>Object.keys(WP).every(id=>WA.isOpen(id))") and E("()=>DZ_FLAGS.every(f=>flagOn(f.id))"), 'Admin: alle Länder und Funktionen offen')
    ok(E("()=>Object.keys(CATALOG).every(id=>hasItem(id))"), 'Admin: alle Katalog-Dinge freigeschaltet')
    E("()=>{S.coins=5}"); pg.wait_for_timeout(2200); ok(E("()=>S.coins")>=9999, 'Admin: Münzen füllen sich wieder auf')
    ok(E(KID)==kid, 'Admin: Speicher des Kindes unverändert (außer Zeitstempel)')
    ok(E("()=>!!localStorage.getItem('mathe_abenteuer_v1_admin')"), 'Admin: eigener Speicher')
    E("()=>{ACT.parent()}"); ok(E("()=>view")=='parent' and E("()=>PIN")==None, 'Admin: Eltern-Seite ohne PIN')
    E("()=>adminSetMode(false)"); pg.wait_for_timeout(900)
    ok(E("()=>ADMIN")==False and E("()=>S.coins")==12 and E("()=>S.starsLife")==3, 'Zurück zum Kind: Münzen und Sterne wie vorher')
    ok(E("()=>JSON.stringify([S.owned,Object.keys(S.cards),Object.keys(S.trophies),Object.keys(S.decks).length,S.flags])")==kid_core, 'Kind: Besitz, Karten, Pokale, Gruppen, Schalter nach Rückkehr unverändert')
    # ---- Runde 5b: Profil unter Seitenzeit, Sperre für heute, Standard, ein Name, Ring-Profil
    ok(E("()=>DEF().cfg.pageNeed")==10 and E("()=>DEF().cfg.pageMin")==3 and E("()=>DEF().cfg.pageWin")==2, 'Standard: 3 Min, 2 Fenster, 10 Aufgaben zum Wiederöffnen (eher wenig Spielzeit)')
    ok(E("()=>pgArea('profile')")=='profile' and E("()=>pgArea('look')")=='profile', 'Profil (und Farben & Töne) zählt zur Seitenzeit')
    E("()=>{S.cfg.pageNeed=10;S.daily.pg={};S.daily.got=false;S.daily.n=0;S.daily.lock={all:false,pages:{}};go('profile')}"); pg.wait_for_timeout(200)
    ok(E("()=>!!document.querySelector('#pgT')"), 'Profil zeigt die Zeit-Anzeige')
    E("()=>{pgRec('profile').sec=179}"); pg.wait_for_timeout(1500)
    ok(E("()=>!!document.querySelector('.pglock')") and E("()=>pgState('profile').need")==10, 'Profil schließt nach 3 Minuten, 10 Aufgaben nötig')
    E("()=>{S.daily.pg={};S.daily.lock={all:false,pages:{}};S.daily.got=true}")
    ok(E("()=>pgState('shop').open")==True, 'Tagesziel geschafft: Seite offen')
    E("()=>{ACT.pgLockOne('shop')}"); ok(E("()=>pgState('shop').open")==False and E("()=>pgState('shop').parent")==True and E("()=>pgState('musik').open")==True, 'Eltern sperren nur den Shop für heute (auch bei erreichtem Tagesziel)')
    E("()=>{go('shop')}"); ok('Deine Eltern' in E("()=>document.getElementById('app').innerText"), 'Kind sieht: Eltern haben die Seite geschlossen')
    E("()=>{ACT.pgLockOne('shop');ACT.pgLockAll()}"); ok(all(not E("(a)=>pgState(a).open", a) for a in ['shop','musik','profile','notiz']), 'Alle Seiten für heute gesperrt')
    ok(E("()=>pgState('welt').parent")==True and E("()=>pgArea('geoPlay')")==None and E("()=>pgArea('hefte')")==None, 'Gesperrt gilt nicht für Hefte und Europa Entdecker')
    E("()=>{ACT.pgLockAll()}"); ok(E("()=>pgState('shop').open")==True, 'Sperre aufheben')
    E("()=>{ACT.pgLockAll();S.daily.d='2000-01-01';touchDay()}"); ok(E("()=>pgLockRec().all")==False, 'Sperre endet am nächsten Tag von selbst')
    E("()=>{S.daily.got=false}")
    ok(E("()=>profileName()")==E("()=>FN()") or True, 'Name')
    E("()=>{S.name='Mira';S.avName='Alt';S.av.look=S.av.look||{};S.av.use=true;S.daily.lock={all:false,pages:{}};S.daily.pg={};go('profile')}")
    t = E("()=>document.getElementById('app').innerText")
    ok('Mira' in t and 'Alt' not in t and E("()=>!document.querySelector('#avNameIn')"), 'Ein Name: Kind = Avatar; kein eigenes Avatar-Namensfeld')
    E("()=>go('parent')"); ok(E("()=>!document.querySelector('#avNameIn')") and E("()=>S.avName")=='Alt', 'Eltern: kein Avatar-Name; alter Wert bleibt gespeichert')
    E("()=>go('home')"); ok(E("()=>!!document.querySelector('.dz-ring') && !!document.querySelector('.dz-lvb')"), 'Start: Profil als Ring mit Level-Abzeichen')
    # ---- Notizbuch (Zettel-Wand)
    E("()=>{S.notes=[];UI.noteEdit=null;UI.noteDraft=null;S.daily.pg={};go('rewards')}")
    ok(E("()=>!!document.querySelector('.dz-tile[data-act=notiz]')"), 'Meine Welt: Kachel Notizbuch')
    E("()=>go('notiz')"); pg.fill('#noteIn', 'x' * 200); ok(E("()=>document.querySelector('#noteIn').value.length")==140 and '140 / 140' in E("()=>document.getElementById('noteCnt').textContent"), 'Zettel: höchstens 140 Zeichen, Zähler')
    pg.fill('#noteIn', 'Heute: Frankreich 🥐'); pg.click('[data-act=noteSave]'); ok(E("()=>S.notes.length")==1 and E("()=>S.notes[0].t")=='Heute: Frankreich 🥐', 'Zettel angeheftet')
    for i in range(7): E("(i)=>{go('notiz');document.querySelector('#noteIn').value='Zettel '+i;UI.noteDraft='Zettel '+i;ACT.noteSave()}", i)
    ok(E("()=>S.notes.length")==8 and E("()=>document.querySelectorAll('.nz-note').length")==6 and E("()=>document.querySelectorAll('.nz-old').length")==2, 'Wand zeigt die letzten 6, ältere stehen in der Liste')
    E("()=>ACT.noteEdit(S.notes[7].id)"); pg.fill('#noteIn', 'geändert'); pg.click('[data-act=noteSave]'); ok(E("()=>S.notes[7].t")=='geändert' and E("()=>S.notes.length")==8, 'Zettel ändern')
    E("()=>ACT.noteEdit(S.notes[7].id)"); pg.click('[data-act=noteDel]'); ok(E("()=>S.notes.length")==8, 'Löschen fragt erst nach'); E("()=>ACT.noteDelYes()"); ok(E("()=>S.notes.length")==7, 'Zettel gelöscht nach Bestätigung')
    ok(E("()=>mergeState({notes:[{id:1,t:'a',ts:1}]}).notes.length")==1, 'Zettel überstehen Laden')
    ok(E("()=>pgArea('notiz')")=='notiz', 'Notizbuch unter Seitenzeit')
    # ---- Reisemeilen und Boarding-Pass
    E("()=>{S.daily.pg={};S.daily.mi=0;S.daily.bp=false;S.daily.d=ymd();const w=wS();w.miles=0;w.milesSpent=0;w.open={};S.starsLife=46;S.stars=46;S.coins=5;go('home')}")
    E("()=>{startDeck('A4.divtens')}"); pg.wait_for_timeout(200)
    q = E("()=>R.ctx.q.fields.map(f=>f.a)")
    for k, v in enumerate(q): E("(a)=>{R.ctx.vals[a[0]]=String(a[1]);}", [k, v])
    E("()=>check()"); ok(E("()=>wS().miles")==1, 'Richtig gelöst = 1 Reisemeile')
    s0 = E("()=>[S.coins,S.stars,S.starsLife,S.chests]")
    ok(E("()=>WA.addMiles(500)")==99 and E("()=>wS().miles")==100, 'Tagesgrenze 100 Meilen')
    ok(E("()=>WA.addMiles(5)")==0, 'darüber hinaus keine Meilen')
    E("()=>{S.daily.mi=0;wS().miles=460;wS().milesSpent=0;go('welt')}")
    ok('460' in E("()=>document.querySelector('.w-bal').innerText") and 'Reisemeilen' in E("()=>document.querySelector('.w-depart').innerText"), 'Hall zeigt Reisemeilen')
    E("()=>ACT.wOpenYes('fra')"); ok(E("()=>WA.isOpen('fra')")==True and E("()=>wS().milesSpent")==60, 'Frankreich kostet 60 Meilen')
    ok(E("()=>[S.coins,S.stars,S.starsLife,S.chests]")==s0, 'Münzen, Sterne, Karten unverändert beim Öffnen')
    E("()=>{S.daily.bp=false;wS().open={}}")
    ok(E("()=>WA.testPass(11,15)")==None, 'Mini-Test 11/15 (73 %): kein Boarding-Pass')
    nx = E("()=>WA.nextLocked()"); pid = E("()=>WA.testPass(12,15)"); ok(pid==nx and E("()=>WA.isOpen(WA.nextLocked()===null?'':'x')") is not None and E("(i)=>WA.isOpen(i)", pid), 'Mini-Test 12/15 (80 %): Boarding-Pass öffnet das nächste Land')
    ok(E("()=>WA.testPass(15,15)")==None, 'nur ein Boarding-Pass pro Tag')
    ok(E("()=>[S.coins,S.stars,S.starsLife]")==s0[:3], 'Boarding-Pass kostet nichts')
    # ---- Tablet: Prüfen ohne Scrollen
    for w, h in [(1280, 650), (1024, 600), (960, 540), (900, 480), (800, 450), (1280, 800)]:
        pg.set_viewport_size({'width': w, 'height': h})
        E("()=>{S.name='Mira';UI.key='A4.divtens';UI.mod='A4';startDeck('A4.divtens')}"); pg.wait_for_timeout(250)
        r = E("()=>{const b=document.querySelector('[data-act=check]');if(!b)return null;const q=b.getBoundingClientRect();return {bottom:q.bottom,h:innerHeight,sh:document.documentElement.scrollHeight}}")
        ok(r and r['bottom'] <= r['h'] and r['sh'] <= r['h'] + 2, 'Prüfen sichtbar ohne Scrollen @%dx%d (%s)' % (w, h, r))
        E("()=>go('home')")
    ok(errs == [], 'keine JS-Fehler %s' % errs)
print('\nFAILS:', fails); sys.exit(1 if fails else 0)
