"""Runde 8: 4 Minuten freie Zeit + Hinweis, Eltern-Freigaben je Bereich (Auto/Offen/Zu, Zeit), Weltreise freie Wahl (DE/JP/IN offen),
Heft B mit 6 Heften, Admin-Modus endet beim Sperren des Bildschirms, Mini-Test übersteht Neuladen, Notenheft (Notenbild + Eltern-Schalter),
„Extra Spaß“ aufgelöst (6 Kacheln in Meine Hefte), Belohnungs-Momente (Münz-Beutel, Karten-Hinweis, Pokal-Feier).
Aufruf: python3 round8_test.py /abs/pfad/Mathe-Abenteuer_Klasse4.html"""
import sys
from playwright.sync_api import sync_playwright
html = sys.argv[1]; fails = []
def ok(c, m):
    print(('OK   ' if c else 'FAIL ') + m)
    if not c: fails.append(m)
HIDE = "(h)=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>h});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>h?'hidden':'visible'});document.dispatchEvent(new Event('visibilitychange'))}"
with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1280, 'height': 800}); errs = []
    pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
    pg.goto('file://' + html); pg.wait_for_timeout(300)
    E = pg.evaluate
    E("()=>{window.__rwOff=1;S.name='Mira';S.coins=300;S.life=300;S.starsLife=40;S.stars=40;S.cards={a1:1};S.trophies={blk1:1};S.cfg.shopMin=0;S.cfg.limitMin=0;save()}")
    kid0 = E("()=>JSON.stringify([S.coins,S.starsLife,S.cards,Object.keys(S.trophies)])")

    # ---------- 9: 4 Minuten freie Zeit vor der Hausaufgabe ----------
    E("()=>{S.daily.n=0;S.daily.sec=0;S.daily.free=0;S.daily.freeMsg=false;rgResetAll();save();go('home')}"); pg.wait_for_timeout(100)
    ok(E("()=>FREE_SEC")==240 and 'Freie Zeit heute' in pg.inner_text('.freenote') and '4:00' in pg.inner_text('.freenote'), 'Start: Hinweis „Freie Zeit heute 4:00“')
    ok(E("()=>[...document.querySelectorAll('.dz-home4 .dz-tile')].filter(t=>/Noch zu/.test(t.innerText)).length")==0, 'Während der freien Zeit: kein „Noch zu“ auf der Startseite')
    E("()=>go('shop')"); pg.wait_for_timeout(100)
    ok(E("()=>!document.querySelector('.pglock')") and 'Freie Zeit heute' in pg.inner_text('.freebar') and E("()=>document.getElementById('pgT').textContent")=='4:00', 'Shop vor der Hausaufgabe offen, mit sichtbarer Uhr „Freie Zeit heute“')
    pg.mouse.click(5, 790); pg.wait_for_timeout(2300)
    f1 = E("()=>S.daily.free"); ok(f1 >= 1 and E("()=>document.getElementById('pgT').textContent") != '4:00', 'Uhr läuft im Shop (%s s)' % f1)
    E("()=>go('geo')"); pg.mouse.click(5, 790); pg.wait_for_timeout(1600); ok(E("()=>S.daily.free")==f1, 'Europa Entdecker zählt nicht zur freien Zeit')
    E("()=>go('hefte')"); pg.wait_for_timeout(1300); ok(E("()=>S.daily.free")==f1, 'Meine Hefte zählt nicht zur freien Zeit')
    E("()=>{S.daily.free=239;go('schatz')}"); pg.mouse.click(5, 790); pg.wait_for_timeout(1600)
    ok(E("()=>!!document.getElementById('modal')") and 'Die freie Zeit ist um' in pg.inner_text('#modal') and '25 Aufgaben' in pg.inner_text('#modal') and '20 Minuten' in pg.inner_text('#modal'), 'Nach 4 Minuten: Hinweis „nächste Freigabe: 25 Aufgaben ODER 20 Minuten“')
    E("()=>closeModal()")
    ok(E("()=>!!document.querySelector('.pglock')") and '4 freien Minuten' in pg.inner_text('.pglock'), 'Danach ist der Bereich zu, der Sperr-Bildschirm nennt die verbrauchte freie Zeit')
    E("()=>go('home')"); ok('Die freie Zeit ist um' in pg.inner_text('.freenote') and E("()=>[...document.querySelectorAll('.dz-home4 .dz-tile')].filter(t=>/Noch zu/.test(t.innerText)).map(t=>t.dataset.act).join()")=='rewards', 'Start: Hinweis + „Noch zu“ auf Meine Welt')
    E("()=>{go('shop')}"); pg.wait_for_timeout(100); E("()=>go('home')"); ok(E("()=>!document.getElementById('modal')"), 'Der Hinweis kommt nur einmal am Tag')
    E("()=>{S.daily.n=25;save();go('home')}"); ok(pg.locator('.freenote').count()==0, 'Nach der Hausaufgabe: kein Freie-Zeit-Hinweis mehr')
    E("()=>go('shop')"); ok('Zeit in „Shop“' in pg.inner_text('.pgbar'), 'Nach der Hausaufgabe gilt wieder die Bereichszeit (5 Min)')
    E("()=>{S.daily.d='2000-01-01';touchDay()}"); ok(E("()=>freeLeft()")==240 and E("()=>!S.daily.freeMsg"), 'Neuer Tag: wieder 4 Minuten freie Zeit')

    # ---------- 1: Eltern-Freigaben je Haupt- und Unterbereich ----------
    E("()=>{S.daily.n=25;S.cfg.perm={};save()}")
    ok(E("()=>SEC_TREE().map(m=>m.id).join()")=='m_hefte,m_geo,m_kreativ,m_welt,m_profil', 'Fünf Hauptbereiche')
    E("()=>{permSet('m_geo','lock');go('home')}")
    ok('Noch zu' in pg.inner_text('.dz-home4 .dz-tile[data-act=geo]'), 'Europa Entdecker gesperrt → „Noch zu“ auf der Start-Kachel')
    E("()=>go('geo')"); ok(E("()=>!!document.querySelector('.pglock')") and 'Eltern' in pg.inner_text('.pglock'), 'Gesperrter Hauptbereich zeigt den Eltern-Sperr-Bildschirm')
    E("()=>go('geoMemory')"); ok(E("()=>!!document.querySelector('.pglock')"), 'Unterbereich folgt dem gesperrten Hauptbereich')
    E("()=>{permSet('geoCards','open');go('geoCards')}"); ok(E("()=>!document.querySelector('.pglock')"), 'Unterbereich mit eigener Einstellung „Offen“ gewinnt')
    E("()=>{permSet('m_geo','');permSet('geoCards','');permSet('geoMemory','lock');go('geo')}")
    ok(E("()=>!document.querySelector('.pglock')") and 'Noch zu' in pg.inner_text('.dz-tile[data-act=geoMemory]') and 'Noch zu' not in pg.inner_text('.dz-tile[data-act=geoCards]'), 'Gesperrter Unterordner (Memory) trägt „Noch zu“ im offenen Ordner')
    E("()=>{permSet('geoMemory','');permSet('KOPF','lock');go('hefte')}")
    ok('Noch zu' in pg.inner_text('.dz-tile[data-act=kopf]') and 'Noch zu' not in pg.inner_text('.dz-tile[data-act=testSetup]'), 'Meine Hefte: gesperrtes Kopfrechnen trägt „Noch zu“')
    E("()=>{ACT.mod('EMAL')}"); pg.wait_for_timeout(80); ok(E("()=>!!document.querySelector('.pglock')"), 'Kopfrechnen (auch über Einmaleins-Einsprung) öffnet nicht, solange es gesperrt ist')
    E("()=>{permSet('KOPF','');S.daily.n=0;S.daily.free=240;rgResetAll();permSet('shop','open');go('shop')}")
    ok(E("()=>!document.querySelector('.pglock')") and E("()=>!document.getElementById('pgT')"), '„Offen“: Shop ohne Hausaufgabe und ohne Zeitgrenze')
    E("()=>{permSet('shop','');S.daily.n=25;permSet('shop','lock');go('rewards')}")
    ok('Noch zu' in pg.inner_text('.dz-tile[data-act=shop]') and 'Noch zu' not in pg.inner_text('.dz-tile[data-act=welt]'), 'Meine Welt: gesperrter Shop trägt „Noch zu“')
    E("()=>{permSet('shop','');permSet('musik','lock');go('kreativhefte')}")
    ok('Noch zu' in pg.inner_text('.dz-tile[data-act=musik]') and 'Noch zu' not in pg.inner_text('.dz-tile[data-act=story]'), 'Ideenwerkstatt: von den Eltern gesperrte Musik trägt „Noch zu“')
    E("()=>{permSet('musik','');permSet('m_welt','lock');go('rewards')}"); ok(E("()=>!!document.querySelector('.pglock')"), 'Meine Welt gesamt sperrbar')
    E("()=>{permSet('m_welt','');S.pin={h:hashStr('1234'),r:'x'};S.cfg.plang='de';go('parent')}"); pg.wait_for_timeout(100)
    ok(pg.locator('.ptblock').count()==5 and pg.locator('.ptsubs').count()==5, 'Eltern: 5 Hauptbereiche mit aufklappbaren Unterbereichen')
    pg.click('.ptblock[data-sec=m_kreativ] .ptarea.main [data-act=permSetAct][data-arg="m_kreativ|lock"]'); pg.wait_for_timeout(100)
    ok(E("()=>S.cfg.perm.m_kreativ")=='lock', 'Eltern: „Zu“ sperrt die Ideenwerkstatt')
    pg.click('.ptblock[data-sec=m_kreativ] .ptarea.main [data-act=permSetAct][data-arg="m_kreativ|auto"]'); pg.wait_for_timeout(100)
    ok(E("()=>!('m_kreativ' in S.cfg.perm)"), 'Eltern: „Auto“ hebt die Sperre auf')
    E("()=>{rgData().rg.a.shop=200;rgData().rg.tot=200;render()}")
    pg.click('.ptsubs[data-sec=m_welt] > summary'); pg.wait_for_timeout(80)
    pg.click('[data-act=ptSubReset][data-arg=shop]'); pg.wait_for_timeout(80); ok(E("()=>rgAreaUsed('shop')")==0, 'Eltern: Zeit eines Unterbereichs zurücksetzen')
    pg.click('[data-act=ptSubExt][data-arg=welt]'); pg.wait_for_timeout(80); ok(E("()=>rgAreaCap('welt')")==600, 'Eltern: Unterbereich +5 Min')
    pg.click('.ptsubs[data-sec=m_welt] [data-act=permSetAct][data-arg="welt|lock"]'); pg.wait_for_timeout(80); ok(E("()=>S.cfg.perm.welt")=='lock' and E("()=>UI.ptOpen.m_welt")==True, 'Eltern: Unterbereich einzeln sperren (Liste bleibt offen)')
    E("()=>{rgData().rg.a.shop=100;rgData().rg.a.welt=50;render()}"); pg.click('[data-act=ptMainReset][data-arg=m_welt]'); pg.wait_for_timeout(80)
    ok(E("()=>rgAreaUsed('shop')+rgAreaUsed('welt')")==0, 'Eltern: Hauptbereich zurücksetzen setzt alle Unterbereiche zurück')
    E("()=>{S.daily.free=200;render()}"); pg.click('[data-act=freeResetAct]'); pg.wait_for_timeout(80); ok(E("()=>S.daily.free")==0, 'Eltern: freie Zeit zurücksetzen')
    E("()=>{S.cfg.perm={};save()}")

    # ---------- 2: Weltreise – freie Wahl, DE/JP/IN von Anfang an ----------
    E("()=>{const w=wS();w.open={};w.picks=0;w.miles=0;w.milesSpent=0;S.daily.n=0;S.daily.sec=0;S.daily.wpk='';S.daily.free=0;save();go('welt')}"); pg.wait_for_timeout(100)
    ok(E("()=>['deu','jpn','ind'].every(WA.isOpen)") and pg.locator('.w-card.open').count()==3, 'Deutschland, Japan, Indien sind frei')
    ok(E("()=>WA.picks()")==0 and '25 Aufgaben' in pg.inner_text('.w-picknote') and '20 Minuten' in pg.inner_text('.w-picknote'), 'Ohne Hausaufgabe: noch keine freie Wahl (Hinweis 25 Aufgaben oder 20 Minuten)')
    E("()=>{S.daily.sec=1200;render()}"); ok(E("()=>WA.picks()")==1 and 'frei wählen' in pg.inner_text('.w-picknote'), '20 Minuten geübt: ein Land frei wählbar')
    E("()=>ACT.wLock('usa')"); ok('frei wählen' in pg.inner_text('#modal') and 'USA' in pg.inner_text('#modal'), 'Beliebiges Land (USA, ganz hinten in der Liste) wählbar')
    E("()=>ACT.wPickYes('usa')"); pg.wait_for_timeout(100); E("()=>UI.wFlightEnd&&UI.wFlightEnd()"); pg.wait_for_timeout(100)
    ok(E("()=>WA.isOpen('usa')") and E("()=>S.daily.wpk")=='usa' and E("()=>WA.picks()")==0 and E("()=>wS().milesSpent")==0, 'USA offen, kostet keine Meilen; heute keine weitere freie Wahl')
    E("()=>{closeModal();ACT.wLock('fra')}"); ok('schon ein Land gewählt' in pg.inner_text('#modal'), 'Zweites Land am selben Tag: freundlicher Hinweis')
    E("()=>{closeModal();S.daily.d='2000-01-01';touchDay();S.daily.n=25}"); ok(E("()=>WA.picks()")==1, 'Am nächsten Tag (nach der Hausaufgabe) wieder eine freie Wahl')
    E("()=>{S.daily.n=0;S.daily.wpk='';go('home')}")

    # ---------- 3: Heft B mit 6 Heften ----------
    E("()=>{UI.acc_hefte='B';go('hefte')}"); pg.wait_for_timeout(100)
    ok(E("()=>document.querySelectorAll('.dz-acc-item.open .dz-hefte5 .dz-tile').length")==6 and 'von 6 Heften' in pg.inner_text('.dz-acc-item.open'), 'Kapitel B: 6 Hefte (B1–B6)')
    ok(E("()=>chapN('A')")==5 and E("()=>chapN('B')")==6 and E("()=>isExtra({id:'B6'})")==False, 'Kapitel A bleibt bei 5, B6 zählt als Arbeitsheft')

    # ---------- 7: „Extra Spaß“ → Meine Hefte, eine Reihe ----------
    E("()=>go('home')"); ok('Extra Spaß' not in pg.inner_text('#app') and pg.locator('.dz-home4 .dz-tile').count()==4, 'Startseite ohne „Extra Spaß“')
    for w in (1280, 1024, 800, 390):
        pg.set_viewport_size({'width': w, 'height': 800}); E("()=>go('hefte')"); pg.wait_for_timeout(80)
        r = E("()=>{const t=[...document.querySelectorAll('.dz-hefte6 .dz-tile')];return {n:t.length,tops:[...new Set(t.map(e=>Math.round(e.getBoundingClientRect().top)))].length,names:t.map(e=>e.querySelector('strong').textContent),over:document.documentElement.scrollWidth>innerWidth}}")
        ok(r['n']==4 and r['tops']==1 and not r['over'], 'Meine Hefte @%d: 4 Kacheln in einer Reihe, nichts ragt heraus' % w)
    ok(r['names']==['Los geht’s', 'Fehler-Heft', 'Mini-Test', 'Kopfrechnen'], 'Reihenfolge: %s' % r['names'])
    pg.set_viewport_size({'width': 1280, 'height': 800})
    E("()=>go('hefte')"); pg.click('.dz-tile[data-act=kopf]'); pg.wait_for_timeout(100)
    ok(E("()=>view")=='kopf' and pg.locator('.topic').count()==9 and pg.locator('.dz-tile').count()==0, 'Kopfrechnen öffnet direkt alle 9 Übungen (kein weiterer Ordner)')

    # ---------- 5: Mini-Test übersteht Neuladen ----------
    E("()=>{UI.scope='all';startTest()}"); pg.wait_for_timeout(150)
    E("()=>{const c=T.qs[0].c;if(c.q.fields){c.vals=c.q.fields.map(f=>f.a)}else{c.sel=c.q.correct};T.i=2;render()}")
    t0 = E("()=>({start:T.start,titles:T.qs.map(x=>x.q.title),a0:JSON.stringify([T.qs[0].c.vals,T.qs[0].c.sel])})")
    pg.reload(); pg.wait_for_timeout(500)
    t1 = E("()=>view==='test'&&T?({start:T.start,titles:T.qs.map(x=>x.q.title),a0:JSON.stringify([T.qs[0].c.vals,T.qs[0].c.sel]),i:T.i}):null")
    ok(t1 and t1['start']==t0['start'] and t1['titles']==t0['titles'] and t1['a0']==t0['a0'] and t1['i']==2, 'Neuladen mitten im Mini-Test: gleiche Aufgaben, Antworten, Aufgabe 3, Uhr läuft weiter')
    ok(E("()=>document.querySelector('.qnav button.has')!==null"), 'Beantwortete Aufgabe ist markiert')
    E("()=>finishTest(false)"); pg.wait_for_timeout(150); ok(E("()=>localStorage.getItem(TEST_KEY)")=='', 'Nach der Abgabe ist der gemerkte Test leer')
    pg.reload(); pg.wait_for_timeout(400); ok(E("()=>view")=='home', 'Nach der Abgabe: Neuladen startet normal')
    E("()=>{UI.scope='all';startTest()}"); pg.wait_for_timeout(100); E("()=>ACT.quitYes()"); ok(E("()=>localStorage.getItem(TEST_KEY)")=='', 'Abbrechen leert den gemerkten Test')
    E("()=>{UI.scope='all';startTest();T.start=Date.now()-3600e3;testPersist()}"); pg.reload(); pg.wait_for_timeout(400)
    ok(E("()=>view")=='home', 'Sehr alter Test (vor 1 Stunde) wird nicht wiederhergestellt')
    E("()=>{window.__rwOff=1}")

    # ---------- 6: Notenheft – Notenbild und Eltern-Schalter ----------
    E("""()=>{const d=noData();const s=noNewSong();s.notes=[{id:'a',name:'C',duration:'short',rest:false,oct:0},{id:'b',name:'E',duration:'short',rest:false,oct:0},{id:'c',name:'G',duration:'short',rest:false,oct:0},{id:'d',name:'A',duration:'normal',rest:false,oct:1},{id:'e',name:'C',duration:'long',rest:true,oct:0},{id:'f',name:'C',duration:'short',rest:true,oct:0},{id:'g',name:'C',duration:'normal',rest:true,oct:0}];d.songs.unshift(s);d.act=s.id;NO.id=null;go('noten')}"""); pg.wait_for_timeout(150)
    ok(pg.locator('#noScore .no-beam').count()==1 and pg.locator('#noScore .no-flag').count()==1, 'Zwei Achtel = ein Balken, das dritte Achtel hat ein Fähnchen')
    ok(pg.locator('#noScore .no-endbar').count()==1 and pg.locator('#noScore .no-bar').count()==1, 'Schlussstrich am Ende, kein falscher Taktstrich nach dem Schlüssel')
    ok(pg.locator('#noScore rect.no-rest').count()==1 and pg.locator('#noScore g.no-rest').count()==1 and pg.locator('#noScore path.no-rest').count()==1, 'Halbe, Achtel- und Viertelpause haben ihre eigene Form')
    hr = E("()=>{const r=document.querySelector('#noScore rect.no-rest');return [+r.getAttribute('y')+ +r.getAttribute('height'), NO_TOP+28]}")
    ok(hr[0]==hr[1], 'Halbe Pause liegt auf der Mittellinie')
    ok(E("()=>noStemEnd(38-14,true,38)")==38+28 and E("()=>noStemEnd(38+70,false,38)")==38+28, 'Hälse von Noten mit Hilfslinien reichen bis zur Mittellinie')
    ok(E("()=>noY('E',0,0)")==56 and E("()=>noY('H',0,0)")==28 and E("()=>noY('F',1,0)")==0 and E("()=>noY('C',0,0)")==70, 'Lage im System: E4 unterste Linie, H4 Mittellinie, F5 oberste Linie, C4 Hilfslinie')
    mk = E("()=>{const g=(n,o)=>{const d=document.createElement('div');d.innerHTML=noMini(n,o);return d};const e=g('E',0).querySelector('ellipse').getAttribute('cy'),f=g('F',1).querySelector('ellipse').getAttribute('cy'),c=[...g('C',0).querySelectorAll('line')].map(l=>l.getAttribute('y1')),a=[...g('A',1).querySelectorAll('line')].map(l=>l.getAttribute('y1')),h=[...g('H',1).querySelectorAll('line')].map(l=>l.getAttribute('y1'));return {e,f,c,a,h}}")
    ok(float(mk['e'])==64 and float(mk['f'])==28 and '73' in mk['c'] and '19' in mk['a'] and '19' in mk['h'], 'Tasten-Bilder: E4 auf der untersten Linie, F5 auf der obersten, Hilfslinien für C4, A5, H5 (%s)' % mk)
    ok('Achtel' in E("()=>document.querySelector('.no-dur[data-arg=short]').getAttribute('aria-label')"), 'Längen heißen auch Achtel/Viertel/Halbe')
    ok(pg.locator('.no-playbar [data-act=noPlay]').count()==1 and pg.locator('.no-playbar [data-act=toggleSound]').count()==1, 'Standard: Abspielen- und Ton-Knopf da')
    E("()=>{S.cfg.noPlay=false;go('home');go('noten')}"); pg.wait_for_timeout(100)
    ok(pg.locator('[data-act=noPlay]').count()==0 and pg.locator('[data-act=noTempo]').count()==0, 'Eltern: Abspielen aus → kein Abspielen-Knopf, kein Tempo')
    E("()=>noPlayToggle()"); ok(E("()=>NO.playing")==False, 'Abspielen aus: auch per Taste kein Abspielen')
    E("()=>{S.cfg.noTone=false;go('home');go('noten')}"); pg.wait_for_timeout(100)
    ok(pg.locator('.no-playbar').count()==0 and pg.locator('[data-act=toggleSound]').count()==0 and E("()=>noToneOn()")==False, 'Eltern: Ton aus → kein Ton-Knopf, Notenheft bleibt still')
    E("()=>go('parent')"); pg.click('[data-act=noToneSw]'); pg.wait_for_timeout(80); pg.click('[data-act=noPlaySw]'); pg.wait_for_timeout(80)
    ok(E("()=>noToneOn()&&noPlayOn()"), 'Eltern-Schalter schalten Ton und Abspielen wieder an')

    # ---------- 8: Belohnungs-Momente ----------
    E("()=>{window.__rwOff=0;S.cfg.calm=false;go('home')}")
    E("()=>{S.life=100;S.coins=100;giveCoins(5,'Test')}"); pg.wait_for_timeout(250)
    ok(pg.locator('#rwBag').count()==0 and pg.locator('.rw-coin').count()==0, 'Münzen (nicht die 10.): keine Beutel-Animation, nur ein leiser Puls')
    E("()=>{S.life=106;S.coins=106;giveCoins(5,'Test')}"); pg.wait_for_timeout(250)
    ok(E("()=>!!document.getElementById('rwBag')&&document.getElementById('rwBag').classList.contains('in')") and '+10' in pg.inner_text('#rwBag') and pg.locator('.rw-coin').count()>=1, 'Jede 10. Münze: Beutel erscheint, Münzen fliegen hinein (+10 seit dem letzten Mal)')
    pg.wait_for_timeout(2600); ok(pg.locator('.rw-coin').count()==0 and E("()=>document.getElementById('rwBag').classList.contains('out')"), 'Münzen: danach verschwindet der Beutel wieder')
    E("()=>{S.cfg.calm=true;S.life=119;S.coins=119;giveCoins(2)}"); pg.wait_for_timeout(250); ok(pg.locator('.rw-coin').count()==0 and '+' in pg.inner_text('#rwBag'), 'Ruhige Darstellung: keine fliegenden Münzen, Beutel zeigt die Summe')
    E("()=>{S.cfg.calm=false;document.querySelectorAll('.confetti').forEach(e=>e.remove());giveChest()}"); pg.wait_for_timeout(300)
    ok('Neue Karte' in pg.inner_text('#rwNote') and pg.locator('.confetti').count()==0 and pg.locator('#rwPop').count()==0, 'Karte: Hinweis „Neue Karte!“ ohne Konfetti, kein Fenster')
    pg.wait_for_timeout(5400); ok(pg.locator('#rwNote.in').count()==0, 'Karten-Hinweis verschwindet von selbst')
    E("()=>{S.chests=1;go('schatz')}"); pg.wait_for_timeout(100); E("()=>{document.querySelectorAll('.confetti').forEach(e=>e.remove());openChest()}"); pg.wait_for_timeout(200)
    ok(pg.locator('.confetti').count()==0, 'Karte aufdecken: kein Konfetti')
    E("()=>{go('home');modal('Test','x','OK','closeModal');rwTrophy({id:'q1000',i:'🏆',n:'Test-Pokal',d:'Nur ein Test'})}"); pg.wait_for_timeout(800)
    ok(pg.locator('#rwPop').count()==0, 'Pokal-Fenster wartet, solange ein anderes Fenster offen ist')
    E("()=>closeModal()"); pg.wait_for_timeout(1000)
    ok(pg.locator('#rwPop').count()==1 and 'Neuer Pokal' in pg.inner_text('#rwPop') and pg.locator('.confetti').count()>=1 and pg.locator('#rwPop .rw-rays').count()==1, 'Pokal: Feier (Konfetti, Strahlen) und Fenster')
    pg.click('#rwPop [data-act=rwPopClose]'); pg.wait_for_timeout(100); ok(pg.locator('#rwPop').count()==0, 'Pokal-Fenster schließt mit „Weiter“')
    E("()=>{S.trophies={blk10:1};rwTrophy({id:'blk10',i:'🐝',n:'C',d:'c'})}"); pg.wait_for_timeout(400)
    n = E("()=>Object.keys(S.trophies).length"); ok(n >= 1 and pg.locator('#rwPop').count()==0 and 'Pokal' in pg.inner_text('#rwNote'), 'Gewöhnliche Pokale: nur ein kleiner Hinweis, kein Konfetti-Fenster (%d neu)' % n)
    pg.wait_for_timeout(5400); E("()=>{S.trophies={};rwTrophy({id:'blk1',i:'🌱',n:'A',d:'a'});rwTrophy({id:'deck5',i:'🗺️',n:'B',d:'b'});rwTrophy({id:'blk10',i:'🐝',n:'C',d:'c'});rwTrophy({id:'blk30',i:'🏃',n:'D',d:'d'})}"); pg.wait_for_timeout(400)
    ok(pg.locator('#rwPop').count()==1 and 'neue Pokale' in pg.inner_text('#rwPop') and 'Pokal' in pg.inner_text('#rwNote'), 'Besondere Pokale zusammen in einem Fenster, die übrigen als Hinweis')
    E("()=>{rwPopClose();window.__rwOff=1;S.trophies={blk1:1};save()}")

    # ---------- 4: Admin-Modus endet beim Sperren des Bildschirms ----------
    E("()=>{S.coins=300;S.life=300;S.starsLife=40;S.stars=40;S.cards={a1:1};S.chests=0;S.trophies={blk1:1};save()}")
    kid1 = E("()=>JSON.stringify([S.coins,S.starsLife,S.cards,Object.keys(S.trophies)])")
    E("()=>{localStorage.setItem(MODE_KEY,'admin')}"); pg.reload(); pg.wait_for_timeout(500)
    ok(E("()=>ADMIN")==True, 'Admin-Modus an')
    E(HIDE, True); ok(E("()=>localStorage.getItem(MODE_KEY)")=='child', 'Bildschirm gesperrt: Admin-Modus sofort beendet (gemerkt)')
    with pg.expect_navigation(): E(HIDE, False)
    pg.wait_for_timeout(400)
    ok(E("()=>ADMIN")==False and E("()=>!document.querySelector('.adminbar')"), 'Entsperrt: App lädt im Kind-Modus')
    ok(E("()=>JSON.stringify([S.coins,S.starsLife,S.cards,Object.keys(S.trophies)])")==kid1, 'Stand des Kindes unverändert')
    E(HIDE, True); E(HIDE, False); pg.wait_for_timeout(300); ok(E("()=>ADMIN")==False and E("()=>view")!='', 'Im Kind-Modus passiert beim Sperren nichts')

    ok(errs == [], 'keine JS-Fehler %s' % errs[:5])
print('\nFAILS:', fails); sys.exit(1 if fails else 0)
