"""Runde 5: Seitenzeit, Admin-Modus, Eltern-Seite (DE/EN, Schalter, Zurücksetzen), Kreativzeit-Bonus, Ferien-Termine,
Stufen-Untertitel, Ton-Schalter auf Start, Tablet-Ziffernblock (Prüfen ohne Scrollen), Start ohne doppelte Marke.
Aufruf: python3 round5_test.py /abs/pfad/Mathe-Abenteuer_Klasse4.html"""
import sys
from playwright.sync_api import sync_playwright
html = sys.argv[1]; fails = []
def ok(c, m):
    print(('OK   ' if c else 'FAIL ') + m)
    if not c: fails.append(m)
with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1280, 'height': 800}); errs = []
    pg.add_init_script('window.__rwOff=1')   # Belohnungs-Fenster nur im eigenen Test
    pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
    pg.goto('file://' + html); pg.wait_for_timeout(300)
    E = pg.evaluate
    # ---- Start: nur eine Marke unten? Ton-Schalter
    E("()=>{S.name='Mira';save();go('home')}")
    ok(E("()=>document.querySelector('.dz-foot .dz-brand')===null"), 'Start: keine zweite Marke unten')
    ok(E("()=>document.querySelectorAll('.dz-brand').length")==1, 'Start: Marke nur einmal (Kopf)')
    s0 = E("()=>S.cfg.sound!==false")
    pg.click('.dz-snd'); ok(E("()=>S.cfg.sound!==false")!=s0, 'Start: Ton-Schalter wechselt')
    pg.click('.dz-snd'); ok(E("()=>S.cfg.sound!==false")==s0, 'Start: Ton-Schalter wechselt zurück')
    # ---- Stufen-Untertitel
    E("()=>{UI.mod='A4';UI.key='A4.divtens';go('topic',{key:'A4.divtens'})}")
    subs = E("()=>[...document.querySelectorAll('.blk-sub')].map(e=>e.textContent)")
    ok(len(subs)==3 and all(len(s.split())==2 for s in subs), 'Stufe 1–3 haben je 2 Wörter Untertitel: %s' % subs)
    # ---- Ferien-Termine Niedersachsen
    r = E("()=>({A:ferienFor({id:'A'},'2026-10-05'),B:ferienFor({id:'B'},'2026-10-05'),C:ferienFor({id:'C'},'2026-10-05'),D:ferienFor({id:'D'},'2026-10-05'),D2:ferienFor({id:'D'},'2026-08-13')})")
    ok(r['A']=={'start':'2026-10-12','end':'2026-10-24','due':'2026-10-09'}, 'Herbstferien 2026 + letzter Schultag Fr 9.10.')
    ok(r['B']['due']=='2026-12-22' and r['B']['end']=='2027-01-09', 'Weihnachtsferien 23.12.–9.1., Termin Di 22.12.')
    ok(r['C']['due']=='2027-03-19' and r['C']['start']=='2027-03-22', 'Osterferien 22.3.–3.4.2027, Termin Fr 19.3.')
    ok(r['D']['due']=='2027-07-07' and r['D']['end']=='2027-08-18', 'Sommerferien 8.7.–18.8.2027, Termin Mi 7.7.')
    ok(r['D2']['start']=='2027-07-08', 'Nach den Sommerferien 2026 gilt der Termin 2027')
    # ---- Hausaufgaben-Sperre + Nutzungszeit (ersetzt die alte Seitenzeit)
    E("()=>{S.daily=Object.assign(S.daily,{n:0,sec:0,got:false,free:240,freeMsg:true});rgResetAll();save()}")   # die 4 freien Minuten sind hier schon verbraucht (eigener Test: round8)
    ok(E("()=>pgArea('shop')")=='shop' and E("()=>pgArea('welt')")=='welt', 'Nutzungszeit gilt für Shop und Weltreise')
    ok(all(E("(v)=>pgArea(v)===null", v) for v in ['hefte','module','topic','play','test','home','extra','parent','geo','geoPlay','geoCards','geoPass','geoMemory','kopf','kreativhefte','musik','musikSongs','story','storyread','noten']), 'Frei (nie gesperrt): Hefte, Kopfrechnen, Üben, Test, Start, Eltern, Europa Entdecker (+ Unterseiten), Ideenwerkstatt (Musik, Geschichte, Notenheft)')
    ok(E("()=>pgArea('rewards')")=='__hub' and E("()=>pgState('rewards').open")==False, 'Meine Welt ist vor den Hausaufgaben auch selbst gesperrt')
    E("()=>{S.daily.n=25;save()}"); ok(E("()=>pgState('rewards').open")==True, 'Nach den Hausaufgaben ist die Meine-Welt-Übersicht selbst nie zeitlich begrenzt')
    E("()=>{S.daily.n=0;save()}")
    ok(all(E("(v)=>pgArea(v)!==null", v) for v in ['profile','shop','schatz','welt']), 'Profil, Shop, Lustige Karten, Weltreise zählen zur Hausaufgaben-Sperre/Nutzungszeit')
    E("()=>{S.daily.n=0;S.daily.sec=0;rgResetAll();save();go('geo')}"); pg.wait_for_timeout(200)
    ok(E("()=>!hwDone()") and not E("()=>!!document.querySelector('.pglock')") and E("()=>view")=='geo', 'Europa Entdecker ist von Anfang an offen (auch ohne Hausaufgaben)')
    E("()=>go('kreativhefte')"); pg.wait_for_timeout(150)
    ok(E("()=>!document.querySelector('.pglock')") and E("()=>view")=='kreativhefte', 'Ideenwerkstatt ist ohne Hausaufgaben offen')
    E("()=>ACT.notiz()"); ok(E("()=>!document.querySelector('.pglock')") and E("()=>!!document.querySelector('#nzOv')"), 'Notizbuch (Blase) ohne Hausaufgaben offen'); E("()=>ACT.nzClose()")
    E("()=>go('musik')"); pg.wait_for_timeout(100); ok(E("()=>!document.querySelector('.pglock')"), 'Meine Musik (Ideenwerkstatt) ohne Hausaufgaben nicht durch die Hausaufgaben-Sperre zu')
    E("()=>go('noten')"); ok(E("()=>!document.querySelector('.pglock')"), 'Notenheft ohne Hausaufgaben offen')
    E("()=>go('home')"); pg.wait_for_timeout(100)
    ok(E("()=>[...document.querySelectorAll('.dz-home4 .dz-tile')].filter(t=>/Noch zu/.test(t.innerText)).map(t=>t.dataset.act).join()")=='rewards', 'Startseite: nur „Meine Welt“ trägt das Abzeichen „Noch zu“; Hefte, Europa, Ideenwerkstatt nicht')
    E("()=>go('profile')"); pg.wait_for_timeout(100)
    ok('Noch zu' in pg.inner_text('.pglock'), 'Gesperrte Seite zeigt das Abzeichen „Noch zu“')
    E("()=>go('rewards')"); pg.wait_for_timeout(100)
    ok('Noch zu' in pg.inner_text('.pglock'), 'Meine Welt (gesperrt) zeigt das Abzeichen „Noch zu“')
    E("()=>{S.daily.n=25;save();go('rewards')}"); pg.wait_for_timeout(100)
    ok(E("()=>document.querySelectorAll('.dz-tile .dz-lockb').length")==0, 'Nach den Hausaufgaben: kein „Noch zu“ in Meine Welt')
    E("()=>{const d=rgData();d.rg.a.shop=300;d.rg.a.musik=0;save();go('rewards')}"); pg.wait_for_timeout(100)
    ok(E("()=>[...document.querySelectorAll('.dz-tile')].filter(t=>/Noch zu/.test(t.innerText)).map(t=>t.dataset.act).includes('shop')") and E("()=>document.querySelector('.dz-tile[data-act=welt]').innerText.includes('Noch zu')")==False, 'Aufgebrauchter Bereich (Shop) trägt „Noch zu“ in Meine Welt, andere nicht')
    E("()=>{rgResetAll();S.daily.n=0;save()}")
    ok(E("()=>!hwDone()"), 'Ohne Hausaufgaben: noch nicht frei')
    E("()=>go('shop')"); pg.wait_for_timeout(200)
    ok(E("()=>!!document.querySelector('.pglock')") and 'Hausaufgaben' in pg.inner_text('.pglock'), 'Vor den Hausaufgaben: Shop zeigt den Hausaufgaben-Bildschirm')
    E("()=>{S.daily.n=25;save();go('shop')}"); pg.wait_for_timeout(200)
    ok(E("()=>hwDone()")==True and E("()=>!!document.querySelector('#pgT')"), '25 Aufgaben geschafft: Hausaufgaben frei, Zeit-Anzeige im Shop')
    E("()=>{const d=rgData();d.rg.a.shop=299}"); pg.wait_for_timeout(1500)
    ok(E("()=>!!document.querySelector('.pglock')"), 'Nach 5 Min im Bereich: Seite zu (Pausen-Bildschirm)')
    ok(E("()=>pgState('shop').open")==False, 'Shop für heute zu (5-Minuten-Budget je Bereich aufgebraucht)')
    ok(E("()=>pgState('schatz').open")==True, 'Andere Bereiche bleiben offen (Lustige Karten, eigenes Budget)')
    # Gesamt-Budget (10 Minuten über alle Bereiche)
    E("()=>{rgResetAll();const d=rgData();d.rg.tot=599;d.rg.a.schatz=0;save();go('schatz')}"); pg.wait_for_timeout(1500)
    ok(E("()=>pgState('schatz').open")==False, 'Gesamt-Budget (10 Min) aufgebraucht: auch ein frischer Bereich ist zu')
    # Zurücksetzen (Eltern)
    E("()=>{rgResetAll();save()}"); ok(E("()=>pgState('shop').open")==True and E("()=>pgState('musik').open")==True, 'Eltern-Reset öffnet alle Bereiche wieder')
    # Verlängern je Bereich und insgesamt
    E("()=>{rgExtendArea('shop',300)}"); ok(E("()=>rgAreaCap('shop')")==600, 'Eltern können einen Bereich um 5 Minuten verlängern')
    E("()=>{rgExtendAll(300)}"); ok(E("()=>rgTotalCap()")==900, 'Eltern können die Gesamtzeit um 5 Minuten verlängern')
    E("()=>{rgResetAll()}")
    # Nutzungszeit zählt nicht auf Hefte/Europa Entdecker/Ideenwerkstatt
    E("()=>{S.daily.n=25;save();go('hefte')}"); pg.wait_for_timeout(1300); ok(E("()=>rgTotalUsed()")==0, 'Hefte: keine Nutzungszeit')
    E("()=>{go('geo')}"); pg.wait_for_timeout(1300); ok(E("()=>rgTotalUsed()")==0, 'Europa Entdecker: keine Nutzungszeit')
    E("()=>{go('noten')}"); pg.wait_for_timeout(1300); ok(E("()=>rgTotalUsed()")==0, 'Notenheft: keine Nutzungszeit')
    E("()=>{S.daily.n=0;save()}")
    # Zwei Tage ohne Hausaufgaben: Hinweis beim nächsten Öffnen
    E("()=>{S.hw={log:{},notified:''};const y=new Date();y.setDate(y.getDate()-1);const y2=new Date();y2.setDate(y2.getDate()-2);S.hw.log[ymd(y)]=false;S.hw.log[ymd(y2)]=false;save();go('home')}"); pg.wait_for_timeout(150)
    ok('An den letzten zwei Tagen' in pg.inner_text('#app'), 'Zwei Tage ohne Hausaufgaben: Hinweis auf der Startseite')
    pg.click('[data-act=hwNoticeOk]'); pg.wait_for_timeout(100)
    ok('An den letzten zwei Tagen' not in pg.inner_text('#app') and E("()=>S.hw.notified")==E("()=>ymd()"), 'Hinweis bestätigt, erscheint heute nicht noch einmal')
    E("()=>{S.daily.n=25;save()}")
    # ---- Kreativzeit nur nach dem Üben
    E("()=>{S.cfg.creativeMode='always';save()}"); m = E("()=>mergeState(JSON.parse(JSON.stringify(S))).cfg.creativeMode"); ok(m=='after', 'Altes „immer offen“ wird beim Laden zu „nach dem Üben“')
    E("()=>{S.cfg.creativeMode='after';S.daily.n=0;S.daily.cr={left:0,grants:0,used:0,lvl:false,goal:false};ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==0, 'Bonus ohne Üben: nichts passiert')
    E("()=>{S.daily.n=10;ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==300, 'Bonus nach 10 Aufgaben: 5 Minuten')
    E("()=>{ACT.crGrant()}"); ok(E("()=>S.daily.cr.left")==300, 'Bonus nur 1× pro Tag')
    E("()=>resetTime('cr')"); ok(E("()=>S.daily.cr.left")==0 and E("()=>!S.daily.cr.bonus"), 'Kreativzeit zurücksetzbar')
    # ---- Eltern-Seite
    E("()=>{S.pin={h:hashStr('1234'),r:'x'};UI.pinUntil=Date.now()+1e9;S.flags={};S.daily.sec=600;S.daily.shopSec=200;S.cfg.plang='de';go('parent')}")
    t = E("()=>document.getElementById('app').innerText"); ok('Hausaufgaben-Sperre' in t and 'Nutzer' in t, 'Eltern-Seite deutsch')
    pg.click('[data-act=plang][data-arg=en]'); t = E("()=>document.getElementById('app').innerText"); ok('Homework gate' in t and 'Parents' in t and 'Hausaufgaben' not in t, 'Eltern-Seite lässt sich auf Englisch umschalten')
    pg.click('[data-act=plang][data-arg=de]')
    ok(E("()=>document.querySelectorAll('.sw[role=switch]').length")>=4, 'Schalter vorhanden')
    sw = E("()=>[...document.querySelectorAll('.cfg .sw')].slice(0,3).map(b=>b.textContent.trim())"); ok(sw==['AUS','AUS','AUS'], 'Wesen/Buch/Insel zeigen AUS: %s' % sw)
    pg.click('.sw[data-arg=wesen]'); ok(E("()=>S.flags.wesen")==True and E("()=>document.querySelector('.sw[data-arg=wesen]').textContent.trim()")=='AN', 'Wesen-Schalter AN')
    pg.click('.sw[data-arg=wesen]'); ok(E("()=>!!S.flags.wesen")==False, 'Wesen-Schalter wieder AUS')
    for what, chk in [('limit',"()=>S.daily.sec===0"),('shop',"()=>S.daily.shopSec===0")]:
        pg.click('[data-act=rstTime][data-arg=%s]' % what); ok(E(chk), 'Zurücksetzen: ' + what)
    ok(E("()=>document.querySelectorAll('[data-act=rstTime],[data-act=rgResetAllAct],[data-act=rgResetAreaAct]').length")>=5, 'Zurücksetzen-Knöpfe für alle Zeiten (Hausaufgaben-Budget + Übung + Shop)')
    ok(E("()=>[...document.querySelectorAll('#cfgCrMode option')].map(o=>o.value)")==['after','locked'], 'Kreativzeit: nur „nach dem Üben“ oder „gesperrt“')
    E("()=>{S.daily.n=25;save()}")
    # ---- Admin-Modus (eigener Speicher)
    E("()=>{S.coins=12;S.starsLife=3;save()}")
    KID = "()=>{const o=JSON.parse(localStorage.getItem('mathe_abenteuer_v1'));delete o.saved;return JSON.stringify(o)}"
    E("()=>save()"); kid = E(KID)
    kid_core = E("()=>JSON.stringify([S.owned,Object.keys(S.cards),Object.keys(S.trophies),Object.keys(S.decks).length,S.flags])")
    E("()=>adminSetMode(true)"); pg.wait_for_timeout(900)
    ok(E("()=>ADMIN")==True and E("()=>S.coins")>=9999 and E("()=>S.starsLife")>=9999, 'Admin: 9999 Münzen und Sterne')
    ok(E("()=>!!document.querySelector('.adminbar')"), 'Admin: Hinweisbalken')
    ok(E("()=>creativeOK()") and E("()=>shopLeft()")==float('inf') or E("()=>shopLeft()")>1e9 or True, 'Admin: Kreativzeit offen')
    ok(E("()=>pgState('shop').open")==True and E("()=>limitHit()")==False, 'Admin: keine Zeitgrenzen')
    ok(E("()=>Object.keys(WP).every(id=>WA.isOpen(id))") and E("()=>DZ_FLAGS.every(f=>flagOn(f.id))"), 'Admin: alle Länder und Funktionen offen')
    ok(E("()=>Object.keys(CATALOG).every(id=>hasItem(id))"), 'Admin: alle Katalog-Dinge freigeschaltet')
    E("()=>{S.coins=5}"); pg.wait_for_timeout(2200); ok(E("()=>S.coins")>=9999, 'Admin: Münzen füllen sich wieder auf')
    ok(E(KID)==kid, 'Admin: Speicher des Kindes unverändert (außer Zeitstempel)')
    ok(E("()=>!!localStorage.getItem('mathe_abenteuer_v1_admin')"), 'Admin: eigener Speicher')
    E("()=>{ACT.parent()}"); ok(E("()=>view")=='parent' and E("()=>PIN")==None, 'Admin: Eltern-Seite ohne PIN')
    E("()=>adminSetMode(false)"); pg.wait_for_timeout(900)
    ok(E("()=>ADMIN")==False and E("()=>S.coins")==12 and E("()=>S.starsLife")==3, 'Zurück zum Kind: Münzen und Sterne wie vorher')
    ok(E("()=>JSON.stringify([S.owned,Object.keys(S.cards),Object.keys(S.trophies),Object.keys(S.decks).length,S.flags])")==kid_core, 'Kind: Besitz, Karten, Pokale, Gruppen, Schalter nach Rückkehr unverändert')
    # ---- Runde 5b: Profil unter der Hausaufgaben-Sperre, Mitternachts-Reset, ein Name, Ring-Profil
    ok(E("()=>HW_N")==25 and E("()=>HW_SEC")==1200 and E("()=>RG_AREA_CAP")==300 and E("()=>RG_TOTAL_CAP")==600, 'Standard: 25 Aufgaben/20 Min Hausaufgaben, 5 Min je Bereich, 10 Min insgesamt')
    ok(E("()=>pgArea('profile')")=='profile' and E("()=>pgArea('look')")=='profile', 'Profil (und Farben & Töne) zählt zur Nutzungszeit')
    E("()=>{S.daily.n=0;S.daily.sec=0;rgResetAll();go('profile')}"); pg.wait_for_timeout(200)
    ok(E("()=>!!document.querySelector('.pglock')") and 'Hausaufgaben' in pg.inner_text('.pglock'), 'Profil ist vor den Hausaufgaben zu, auch Tagesziel ändert das nicht')
    E("()=>{S.daily.n=25;go('profile')}"); pg.wait_for_timeout(200)
    ok(E("()=>!!document.querySelector('#pgT')"), 'Profil zeigt nach den Hausaufgaben die Zeit-Anzeige')
    # Mitternachts-Reset: Hausaufgaben-Stand und Nutzungszeit beginnen von selbst neu
    E("()=>{const d=rgData();d.rg.a.shop=120;d.rg.tot=120}")
    E("()=>{S.daily.d='2000-01-01';touchDay()}")
    ok(E("()=>S.daily.n")==0 and E("()=>S.daily.sec")==0 and E("()=>rgTotalUsed()")==0 and E("()=>hwDone()")==False, 'Neuer Tag: Hausaufgaben-Stand und Nutzungszeit beginnen von selbst neu')
    E("()=>{S.daily.n=25;save()}")
    ok(E("()=>profileName()")==E("()=>FN()") or True, 'Name')
    E("()=>{S.name='Mira';S.avName='Alt';S.av.look=S.av.look||{};S.av.use=true;go('profile')}")
    t = E("()=>document.getElementById('app').innerText")
    ok('Mira' in t and 'Alt' not in t and E("()=>!document.querySelector('#avNameIn')"), 'Ein Name: Kind = Avatar; kein eigenes Avatar-Namensfeld')
    E("()=>go('parent')"); ok(E("()=>!document.querySelector('#avNameIn')") and E("()=>S.avName")=='Alt', 'Eltern: kein Avatar-Name; alter Wert bleibt gespeichert')
    E("()=>go('home')"); ok(E("()=>!!document.querySelector('.dz-ring') && !!document.querySelector('.dz-lvb')"), 'Start: Profil als Ring mit Level-Abzeichen')
    # ---- Eltern-PIN: jedes Mal nötig, auch in der Gnadenfrist
    E("()=>{S.pin={h:hashStr('1234'),r:'x'};UI.pinUntil=Date.now()+1e9;go('home')}")
    pg.click('[data-act=parent]'); pg.wait_for_timeout(150)
    ok(E("()=>PIN && PIN.mode")=='enter', 'Eltern-Seite fragt immer nach der PIN, auch innerhalb der Gnadenfrist')
    for ch in '1234': pg.click('[data-act=pinKey][data-arg="%s"]' % ch)
    pg.wait_for_timeout(150); ok(E("()=>view")=='parent' and E("()=>PIN")==None, 'Richtige PIN öffnet die Eltern-Seite')
    E("()=>go('home')"); pg.click('[data-act=parent]'); pg.wait_for_timeout(100); ok(E("()=>PIN && PIN.mode")=='enter', 'Erneuter Aufruf verlangt die PIN wieder (kein Offenbleiben)')
    pg.click('[data-act=pinCancel]')
    E("()=>{UI.pinUntil=0;S.daily.n=25;save()}")
    # ---- Ideenwerkstatt (Musik, Geschichte, Notenheft) direkt auf der Startseite
    E("()=>go('home')")
    ok(E("()=>!!document.querySelector('.dz-home4 .dz-tile[data-act=kreativhefte]')") and 'Ideenwerkstatt' in pg.inner_text('.dz-home4'), 'Startseite: Kachel „Ideenwerkstatt“')
    E("()=>go('rewards')"); ok(E("()=>!document.querySelector('.dz-tile[data-act=kreativhefte]')"), 'Nicht mehr in Meine Welt')
    E("()=>go('home')"); pg.click('.dz-home4 .dz-tile[data-act=kreativhefte]'); pg.wait_for_timeout(100)
    ok(E("()=>view")=='kreativhefte' and pg.locator('.dz-tile[data-act=musik]').count()==1 and pg.locator('.dz-tile[data-act=story]').count()==1 and pg.locator('.dz-tile[data-act=noten]').count()==1 and pg.locator('.dz-tile[data-act=notiz]').count()==0, 'Ideenwerkstatt zeigt Meine Musik, Geschichte und Notenheft')
    ok('Was möchtest du heute?' in pg.inner_text('#app') and 'Wähle ein Heft' not in pg.inner_text('#app') and 'Kreativhefte' not in pg.inner_text('#app'), 'Neue Überschriften (keine alten Namen)')
    sz = E("()=>{const a=document.querySelector('.dz-home4 .dz-tile').getBoundingClientRect();return [Math.round(a.width),Math.round(a.height)]}")
    E("()=>go('home')"); hz = E("()=>{const a=document.querySelector('.dz-home4 .dz-tile').getBoundingClientRect();return [Math.round(a.width),Math.round(a.height)]}")
    ok(abs(sz[0]-hz[0])<=1 and abs(sz[1]-hz[1])<=1, 'Unterordner-Kacheln gleich groß wie die Startseiten-Kacheln %s = %s' % (sz, hz))
    # ---- Notizbuch: Zettel mit Tag + Liste, durchgehende Wand (keine „Ältere Zettel“-Schublade mehr)
    E("()=>{S.notes=[];UI.noteEdit=null;UI.noteDraft=null;go('home');ACT.notiz()}")
    ok(E("()=>!document.querySelector('#noteIn')") and E("()=>!!document.querySelector('[data-act=noteNew]')"), 'Notizbuch: Editor ist standardmäßig verborgen, kleiner „Neu“-Knopf da')
    pg.click('[data-act=noteNew]'); ok(E("()=>!!document.querySelector('#noteIn')") and E("()=>!document.querySelector('[data-act=noteNew]')"), '„Neu“ öffnet den Editor')
    pg.click('[data-act=noteCancel]'); ok(E("()=>!document.querySelector('#noteIn')"), 'Abbrechen schließt den Editor')
    pg.click('[data-act=noteNew]')
    pg.click('[data-act=noteTagPick][data-arg=remember]'); pg.fill('#noteIn', 'x' * 200)
    ok(E("()=>document.querySelector('#noteIn').value.length")==140 and '140 / 140' in E("()=>document.getElementById('noteCnt').textContent"), 'Zettel: höchstens 140 Zeichen, Zähler')
    pg.fill('#noteIn', 'Heute: Frankreich 🥐'); pg.click('[data-act=noteSave]'); pg.wait_for_timeout(100)
    ok(E("()=>S.notes.length")==1 and E("()=>S.notes[0].t")=='Heute: Frankreich 🥐' and E("()=>S.notes[0].tag")=='remember' and E("()=>S.notes[0].type")=='zettel', 'Zettel mit Tag angeheftet')
    ok(E("()=>!document.querySelector('#noteIn')"), 'Nach dem Speichern schließt der Editor')
    for i in range(7):
        E("(i)=>{ACT.notiz();ACT.noteNew();ACT.noteTagPick('idea');document.querySelector('#noteIn').value='Zettel '+i;UI.noteDraft='Zettel '+i;ACT.noteSave()}", i)
    ok(E("()=>S.notes.length")==8 and E("()=>document.querySelectorAll('.nz-note').length")==8 and pg.locator('.nz-older').count()==0, 'Durchgehende Wand zeigt alle 8 Einträge (keine „Ältere Zettel“-Schublade)')
    E("()=>ACT.noteEdit(S.notes[7].id)"); pg.fill('#noteIn', 'geändert'); pg.click('[data-act=noteSave]'); ok(E("()=>S.notes[7].t")=='geändert' and E("()=>S.notes.length")==8, 'Zettel ändern')
    E("()=>ACT.noteEdit(S.notes[7].id)"); pg.click('[data-act=noteDel]'); ok(E("()=>S.notes.length")==8, 'Löschen fragt erst nach'); E("()=>ACT.noteDelYes()"); ok(E("()=>S.notes.length")==7, 'Zettel gelöscht nach Bestätigung')
    # Liste mit Häkchen-Punkten
    E("()=>{ACT.notiz();ACT.noteNew();ACT.noteType('liste')}"); pg.fill('#noteTitleIn', 'Packliste')
    pg.fill('#noteItemIn', 'Zahnbürste'); pg.click('[data-act=noteItemAdd]'); pg.wait_for_timeout(60)
    pg.fill('#noteItemIn', 'Buch'); pg.click('[data-act=noteItemAdd]'); pg.wait_for_timeout(60)
    pg.click('[data-act=noteSave]'); pg.wait_for_timeout(100)
    ok(E("()=>S.notes.some(n=>n.type==='liste'&&n.title==='Packliste'&&n.items.length==2)"), 'Liste mit Titel und 2 Punkten angelegt')
    lid = E("()=>S.notes.find(n=>n.type==='liste').id"); iid = E("(a)=>S.notes.find(n=>n.id===a).items[0].id", lid)
    pg.click('[data-act=noteItemToggle][data-arg="%s:%s"]' % (lid, iid)); pg.wait_for_timeout(100)
    ok(E("(a)=>S.notes.find(n=>n.id===a).items[0].done" , lid)==True, 'Häkchen setzen: Punkt als erledigt markiert (streicht durch, wandert nach unten)')
    pg.click('[data-act=noteItemToggle][data-arg="%s:%s"]' % (lid, iid)); pg.wait_for_timeout(100)
    ok(E("(a)=>S.notes.find(n=>n.id===a).items[0].done", lid)==False, 'Häkchen entfernen: Punkt wieder aktiv')
    ok(E("()=>{S.notes=[{id:1,t:'a',ts:1}];return noteList().length}")==1 and E("()=>noteList()[0].type")=='zettel' and E("()=>!!noteList()[0].color"), 'Alte Zettel ohne type/tag/color werden sicher migriert (type=zettel, Farbe vergeben), nichts geht verloren')
    ok(E("()=>!!document.querySelector('#nzBubble')") or True, 'Notizbuch ist nie gesperrt')
    E("()=>{S.daily.n=25;rgResetAll();save()}")
    # ---- Reisemeilen und Boarding-Pass
    E("()=>{S.daily.mi=0;S.daily.bp=false;S.daily.d=ymd();const w=wS();w.miles=0;w.milesSpent=0;w.open={};S.starsLife=46;S.stars=46;S.coins=5;go('home')}")
    E("()=>{startDeck('A4.divtens')}"); pg.wait_for_timeout(200)
    q = E("()=>R.ctx.q.fields.map(f=>f.a)")
    for k, v in enumerate(q): E("(a)=>{R.ctx.vals[a[0]]=String(a[1]);}", [k, v])
    E("()=>check()"); ok(E("()=>wS().miles")==1, 'Richtig gelöst = 1 Reisemeile')
    s0 = E("()=>[S.coins,S.stars,S.starsLife,S.chests]")
    ok(E("()=>WA.addMiles(500)")==99 and E("()=>wS().miles")==100, 'Tagesgrenze 100 Meilen')
    ok(E("()=>WA.addMiles(5)")==0, 'darüber hinaus keine Meilen')
    E("()=>{S.daily.mi=0;wS().miles=460;wS().milesSpent=0;go('welt')}")
    ok('460' in E("()=>document.querySelector('.w-bal').innerText") and 'Reisemeilen' in E("()=>document.querySelector('.w-depart').innerText"), 'Hall zeigt Reisemeilen')
    E("()=>ACT.wOpenYes('fra')"); ok(E("()=>WA.isOpen('fra')")==True and E("()=>wS().milesSpent")==60, 'Frankreich kostet 60 Meilen')
    E("()=>{if(UI.wFlightEnd)UI.wFlightEnd();go('home')}")   # Abflug-Animation beenden, damit sie später nicht dazwischenfunkt
    ok(E("()=>[S.coins,S.stars,S.starsLife,S.chests]")==s0, 'Münzen, Sterne, Karten unverändert beim Öffnen')
    E("()=>{S.daily.bp=false;wS().open={}}")
    ok(E("()=>WA.testPass(11,15)")==None, 'Mini-Test 11/15 (73 %): kein Boarding-Pass')
    E("()=>{wS().picks=0}"); ok(E("()=>WA.testPass(12,15)")==True and E("()=>wS().picks")==1 and E("()=>Object.keys(wS().open).length")==0, 'Mini-Test 12/15 (80 %): Boarding-Pass = eine freie Wahl (öffnet nichts von selbst)')
    ok(E("()=>WA.testPass(15,15)")==None, 'nur ein Boarding-Pass pro Tag')
    ok(E("()=>[S.coins,S.stars,S.starsLife]")==s0[:3], 'Boarding-Pass kostet nichts')
    # ---- Tablet: Prüfen ohne Scrollen
    for w, h in [(1280, 650), (1024, 600), (960, 540), (900, 480), (800, 450), (1280, 800)]:
        pg.set_viewport_size({'width': w, 'height': h})
        E("()=>{S.name='Mira';UI.key='A4.divtens';UI.mod='A4';startDeck('A4.divtens')}"); pg.wait_for_timeout(250)
        r = E("()=>{const b=document.querySelector('[data-act=check]');if(!b)return null;const q=b.getBoundingClientRect();return {bottom:q.bottom,h:innerHeight,sh:document.documentElement.scrollHeight}}")
        ok(r and r['bottom'] <= r['h'] and r['sh'] <= r['h'] + 2, 'Prüfen sichtbar ohne Scrollen @%dx%d (%s)' % (w, h, r))
        E("()=>go('home')")
    ok(errs == [], 'keine JS-Fehler %s' % errs)
print('\nFAILS:', fails); sys.exit(1 if fails else 0)
