/* =====================================================================
   SAMMELALBUM – lustige Fakten, Witze und Denkfragen.
   Karten werden aus Schatztruhen gezogen (Truhen gibt es für echte
   Leistungen). t: 'fakt' | 'witz' | 'frage'   a = Antwort (nur bei Frage/Witz)
   Neue Karten einfach unten anhängen – die ids dürfen sich nie ändern.
   ===================================================================== */
const CARD_TYPES = {
  fakt: { ic: '💡', n: 'Lustiger Fakt' },
  witz: { ic: '😄', n: 'Witz' },
  frage: { ic: '🤔', n: 'Knobelfrage' }
};
const CARDS = [
  { id: 'f01', t: 'fakt', q: 'Ein Krake hat drei Herzen und blaues Blut.' },
  { id: 'f02', t: 'fakt', q: 'Flamingos können im Stehen auf nur einem Bein schlafen.' },
  { id: 'f03', t: 'fakt', q: 'Giraffen haben genauso viele Halswirbel wie du: sieben. Bei ihnen sind die nur riesig lang.' },
  { id: 'f04', t: 'fakt', q: 'Pferde können im Stehen schlafen. Dabei rasten ihre Beine ein, damit sie nicht umfallen.' },
  { id: 'f05', t: 'fakt', q: 'Delfine schlafen mit nur einer Gehirnhälfte. Die andere bleibt wach.' },
  { id: 'f06', t: 'fakt', q: 'Beim Seepferdchen bekommt der Papa die Babys: Er trägt sie in einer Bauchtasche aus.' },
  { id: 'f07', t: 'fakt', q: 'Auf der Venus dauert ein Tag länger als ein ganzes Jahr.' },
  { id: 'f08', t: 'fakt', q: 'In die Sonne würden mehr als eine Million Erden hineinpassen.' },
  { id: 'f09', t: 'fakt', q: 'Bananen sind für Pflanzenforscher Beeren – Erdbeeren dagegen nicht.' },
  { id: 'f10', t: 'fakt', q: 'Der Eiffelturm wird im Sommer ein paar Zentimeter höher, weil sich das Metall in der Wärme ausdehnt.' },
  { id: 'f11', t: 'fakt', q: 'Das Gleichheitszeichen „=“ hat 1557 Robert Recorde erfunden. Sein Grund: Nichts ist gleicher als zwei gleich lange, parallele Striche.' },
  { id: 'f12', t: 'fakt', q: 'Unsere Ziffern 0 bis 9 heißen „arabische Ziffern“. Ursprünglich stammen sie aber aus Indien.' },
  { id: 'f13', t: 'fakt', q: 'Eine Million Sekunden sind etwa 11 Tage und 14 Stunden. Eine Milliarde Sekunden sind sogar mehr als 31 Jahre!' },
  { id: 'f14', t: 'fakt', q: 'Den Euro gibt es als Bargeld seit 2002. Davor hat man in Deutschland mit D-Mark bezahlt.' },
  { id: 'f15', t: 'fakt', q: 'Es gibt 8 verschiedene Euromünzen: 1, 2, 5, 10, 20 und 50 Cent sowie 1 und 2 Euro.' },
  { id: 'f16', t: 'fakt', q: 'Das erste Papiergeld der Welt gab es in China – vor mehr als 1000 Jahren.' },
  { id: 'f17', t: 'fakt', q: 'In manchen Ländern haben Menschen früher mit Muscheln bezahlt.' },
  { id: 'f18', t: 'fakt', q: 'Das Wort „Dollar“ kommt vom deutschen „Taler“.' },
  { id: 'f19', t: 'fakt', q: 'Dein Herz schlägt etwa 100.000-mal an einem einzigen Tag.' },
  { id: 'f20', t: 'fakt', q: 'Ein Blitz ist etwa fünfmal so heiß wie die Oberfläche der Sonne.' },
  { id: 'f21', t: 'fakt', q: 'Eine kleine Schäfchenwolke kann so viel wiegen wie ungefähr 100 Elefanten.' },
  { id: 'f22', t: 'fakt', q: 'Pinguine können nicht fliegen, dafür aber super schwimmen und tauchen.' },
  { id: 'f23', t: 'fakt', q: 'Spinnen haben acht Beine, Insekten sechs. Deshalb sind Spinnen gar keine Insekten.' },
  { id: 'f24', t: 'fakt', q: 'Honig verdirbt fast nie. Er kann unglaublich lange essbar bleiben.' },
  { id: 'f25', t: 'fakt', q: 'Das Wort „vier“ hat vier Buchstaben. Im Deutschen ist das die einzige Zahl, bei der das stimmt.' },
  { id: 'f26', t: 'fakt', q: '111.111.111 · 111.111.111 = 12.345.678.987.654.321. Das ist ein richtig schönes Zahlenmuster!' },
  { id: 'f27', t: 'fakt', q: 'Die Rechenzeichen + und − gibt es gedruckt seit über 500 Jahren.' },
  { id: 'f28', t: 'fakt', q: 'Kolibris können rückwärts fliegen. Das schafft sonst kein anderer Vogel.' },
  { id: 'f29', t: 'fakt', q: 'Eine Gartenschnecke hat mehrere tausend winzige Zähnchen auf ihrer Zunge.' },
  { id: 'f30', t: 'fakt', q: 'Kängurus können kaum rückwärts gehen.' },
  { id: 'f31', t: 'fakt', q: 'Elefanten können nicht springen.' },
  { id: 'f32', t: 'fakt', q: 'Der Mond entfernt sich jedes Jahr ein paar Zentimeter von der Erde.' },

  { id: 'w01', t: 'witz', q: 'Was ist grün und klopft an die Tür?', a: 'Ein Klopfsalat!' },
  { id: 'w02', t: 'witz', q: 'Was sagt die Null zur Acht?', a: '„Schicker Gürtel!“' },
  { id: 'w03', t: 'witz', q: 'Warum ist das Mathebuch so traurig?', a: 'Es hat so viele Probleme.' },
  { id: 'w04', t: 'witz', q: 'Was macht ein Pirat am Computer?', a: 'Er drückt die Enter-Taste.' },
  { id: 'w05', t: 'witz', q: 'Was sagt der große Stift zum kleinen Stift?', a: '„Wachs-mal-stift!“' },
  { id: 'w06', t: 'witz', q: 'Was ist ein Keks unter einem Baum?', a: 'Ein schattiges Plätzchen.' },
  { id: 'w07', t: 'witz', q: 'Wie nennt man ein Pferd, das im Wasser lebt?', a: 'Seepferdchen!' },
  { id: 'w08', t: 'witz', q: 'Was ist schlimmer als ein Wurm im Apfel?', a: 'Ein halber Wurm.' },
  { id: 'w09', t: 'witz', q: 'Warum können Geister so schlecht lügen?', a: 'Man kann einfach durch sie hindurchschauen.' },
  { id: 'w10', t: 'witz', q: 'Was macht ein Clown im Büro?', a: 'Faxen!' },
  { id: 'w11', t: 'witz', q: 'Wie nennt man einen Bumerang, der nicht zurückkommt?', a: 'Stock.' },
  { id: 'w12', t: 'witz', q: 'Was ist gelb und kann nicht schwimmen?', a: 'Ein Bagger.' },
  { id: 'w13', t: 'witz', q: 'Zwei Magnete treffen sich. Sagt der eine zum anderen …', a: '„Was soll ich nur anziehen?“' },
  { id: 'w14', t: 'witz', q: 'Wie viele Kekse kann man auf nüchternen Magen essen?', a: 'Nur einen. Danach ist der Magen nicht mehr nüchtern.' },
  { id: 'w15', t: 'witz', q: 'Was sagt ein Taschenrechner zum anderen?', a: '„Du kannst auf mich zählen!“' },

  { id: 'q01', t: 'frage', q: 'Wie viele Beine haben 3 Pferde und 2 Enten zusammen?', a: '16 Beine: 3 · 4 + 2 · 2 = 12 + 4 = 16.' },
  { id: 'q02', t: 'frage', q: 'Du hast 5 Äpfel und nimmst 3 weg. Wie viele Äpfel hast du dann?', a: 'Du hast 3 – nämlich die, die du genommen hast!' },
  { id: 'q03', t: 'frage', q: 'Wie viele Monate haben 28 Tage?', a: 'Alle 12! Jeder Monat hat mindestens 28 Tage.' },
  { id: 'q04', t: 'frage', q: 'Was ist schwerer: ein Kilo Federn oder ein Kilo Steine?', a: 'Beides wiegt gleich viel: ein Kilo.' },
  { id: 'q05', t: 'frage', q: 'Wie oft kannst du 10 von 100 abziehen?', a: 'Nur einmal. Danach hast du 90 und nicht mehr 100.' },
  { id: 'q06', t: 'frage', q: 'Welche Zahl wird größer, wenn du sie auf den Kopf stellst?', a: 'Die 6: Auf den Kopf gestellt wird sie zur 9.' },
  { id: 'q07', t: 'frage', q: 'Wie viele 50-Cent-Münzen brauchst du für 10 Euro?', a: '20 Münzen, denn 2 Münzen sind schon 1 Euro.' },
  { id: 'q08', t: 'frage', q: 'Welche drei Münzen ergeben zusammen genau 35 Cent?', a: '20 ct + 10 ct + 5 ct.' },
  { id: 'q09', t: 'frage', q: 'Wie viele Zehner stecken in 240?', a: '24 Zehner, denn 240 : 10 = 24.' },
  { id: 'q10', t: 'frage', q: 'Ich denke an eine Zahl. Teile ich sie durch 10, kommt 7 heraus. Welche Zahl ist es?', a: '70, denn 70 : 10 = 7.' },
  { id: 'q11', t: 'frage', q: 'Wie oft passt die 20 in die 100?', a: '5-mal, denn 5 · 20 = 100.' },
  { id: 'q12', t: 'frage', q: 'Du teilst 120 Bonbons gerecht unter 40 Kindern auf. Wie viele bekommt jedes Kind?', a: '3 Bonbons, denn 120 : 40 = 3.' },
  { id: 'q13', t: 'frage', q: 'Ein Eis kostet 1,50 €. Wie viel kosten 4 Eis?', a: '6,00 €, denn 4 · 1,50 € = 6,00 €.' },
  { id: 'q14', t: 'frage', q: 'Was ist mehr wert: eine Million Cent oder eine Million Euro?', a: 'Eine Million Euro! Eine Million Cent sind nur 10.000 €.' },
  { id: 'q15', t: 'frage', q: 'Ein Pony frisst am Tag 2 kg Heu. Wie viel Heu braucht es in einer Woche?', a: '14 kg, denn 7 · 2 kg = 14 kg.' },
  { id: 'q16', t: 'frage', q: 'Ein Hase hat 2 Ohren. Wie viele Ohren haben 10 Hasen?', a: '20 Ohren.' },
  { id: 'q17', t: 'frage', q: 'Du bezahlst etwas für 3,20 € mit einem 5-Euro-Schein. Wie viel Rückgeld bekommst du?', a: '1,80 €.' },
  { id: 'q18', t: 'frage', q: 'Wie viele Beine haben 5 Spinnen zusammen?', a: '40 Beine, denn 5 · 8 = 40.' },
  { id: 'q19', t: 'frage', q: 'Du hast 10 Münzen zu je 10 Cent. Wie viel Geld ist das?', a: '100 Cent, also 1 Euro.' },
  { id: 'q20', t: 'frage', q: 'Wenn 3 Mäuse in 3 Minuten 3 Stück Käse fressen: Wie viele Mäuse brauchen 100 Minuten für 100 Stück Käse?', a: 'Auch nur 3 Mäuse! Jede Maus frisst alle 3 Minuten ein Stück.' }
];
