/* =====================================================================
   SCHATZKAMMER – Sammelkarten aus den Schatztruhen: Fakten, Witze,
   Knobelfragen, Rätsel, Musik und Denk-mal-Fragen. Alles liegt in einem
   gemischten Stapel; Karten werden zufällig gezogen.

   Format pro Karte:
     id  eindeutig und stabil – die ids dürfen sich nie ändern!
     t   Kartentyp (Schlüssel aus CARD_TYPES)
     e   Emoji = das Bild der Karte
     q   Haupttext (Frage / Fakt / Witz-Anfang)
     a   Antwort bzw. Erklärung. Pflicht bei witz, frage, raetsel.
         Optional als „Mehr dazu“ bei fakt und musik. Bei offen: NIE.
   Neue Karten einfach unten anhängen und die Nummern pro Präfix
   weiterzählen (f = fakt, w = witz, q = frage, r = raetsel, m = musik,
   o = offen).
   ===================================================================== */
const CARD_TYPES = {
  fakt:    { ic: '💡', n: 'Fakt' },
  witz:    { ic: '😄', n: 'Witz' },
  frage:   { ic: '🤔', n: 'Knobelfrage' },
  raetsel: { ic: '🧩', n: 'Rätsel' },
  musik:   { ic: '🎵', n: 'Musik' },
  offen:   { ic: '💭', n: 'Denk mal' }
};
const CARDS = [
  // Fakten (ursprünglich)
  { id: 'f01', t: 'fakt', e: '🐙', q: 'Ein Krake hat drei Herzen und blaues Blut.' },
  { id: 'f02', t: 'fakt', e: '🦩', q: 'Flamingos können im Stehen auf nur einem Bein schlafen.' },
  { id: 'f03', t: 'fakt', e: '🦒', q: 'Giraffen haben genauso viele Halswirbel wie du: sieben. Bei ihnen sind die nur riesig lang.' },
  { id: 'f04', t: 'fakt', e: '🐴', q: 'Pferde können im Stehen schlafen. Dabei rasten ihre Beine ein, damit sie nicht umfallen.' },
  { id: 'f05', t: 'fakt', e: '🐬', q: 'Delfine schlafen mit nur einer Gehirnhälfte. Die andere bleibt wach.' },
  { id: 'f06', t: 'fakt', e: '🌊', q: 'Beim Seepferdchen bekommt der Papa die Babys: Er trägt sie in einer Bauchtasche aus.' },
  { id: 'f07', t: 'fakt', e: '🪐', q: 'Auf der Venus dauert ein Tag länger als ein ganzes Jahr.' },
  { id: 'f08', t: 'fakt', e: '☀️', q: 'In die Sonne würden mehr als eine Million Erden hineinpassen.' },
  { id: 'f09', t: 'fakt', e: '🍌', q: 'Bananen sind für Pflanzenforscher Beeren – Erdbeeren dagegen nicht.' },
  { id: 'f10', t: 'fakt', e: '🗼', q: 'Der Eiffelturm wird im Sommer ein paar Zentimeter höher, weil sich das Metall in der Wärme ausdehnt.' },
  { id: 'f11', t: 'fakt', e: '✏️', q: 'Das Gleichheitszeichen „=“ hat 1557 Robert Recorde erfunden. Sein Grund: Nichts ist gleicher als zwei gleich lange, parallele Striche.' },
  { id: 'f12', t: 'fakt', e: '🔢', q: 'Unsere Ziffern 0 bis 9 heißen „arabische Ziffern“. Ursprünglich stammen sie aber aus Indien.' },
  { id: 'f13', t: 'fakt', e: '⏳', q: 'Eine Million Sekunden sind etwa 11 Tage und 14 Stunden. Eine Milliarde Sekunden sind sogar mehr als 31 Jahre!' },
  { id: 'f14', t: 'fakt', e: '💶', q: 'Den Euro gibt es als Bargeld seit 2002. Davor hat man in Deutschland mit D-Mark bezahlt.' },
  { id: 'f15', t: 'fakt', e: '🪙', q: 'Es gibt 8 verschiedene Euromünzen: 1, 2, 5, 10, 20 und 50 Cent sowie 1 und 2 Euro.' },
  { id: 'f16', t: 'fakt', e: '📜', q: 'Das erste Papiergeld der Welt gab es in China – vor mehr als 1000 Jahren.' },
  { id: 'f17', t: 'fakt', e: '🐚', q: 'In manchen Ländern haben Menschen früher mit Muscheln bezahlt.' },
  { id: 'f18', t: 'fakt', e: '💵', q: 'Das Wort „Dollar“ kommt vom deutschen „Taler“.' },
  { id: 'f19', t: 'fakt', e: '❤️', q: 'Dein Herz schlägt etwa 100.000-mal an einem einzigen Tag.' },
  { id: 'f20', t: 'fakt', e: '⚡', q: 'Ein Blitz ist etwa fünfmal so heiß wie die Oberfläche der Sonne.' },
  { id: 'f21', t: 'fakt', e: '☁️', q: 'Eine kleine Schäfchenwolke kann so viel wiegen wie ungefähr 100 Elefanten.' },
  { id: 'f22', t: 'fakt', e: '🐧', q: 'Pinguine können nicht fliegen, dafür aber super schwimmen und tauchen.' },
  { id: 'f23', t: 'fakt', e: '🕷️', q: 'Spinnen haben acht Beine, Insekten sechs. Deshalb sind Spinnen gar keine Insekten.' },
  { id: 'f24', t: 'fakt', e: '🍯', q: 'Honig verdirbt fast nie. Er kann unglaublich lange essbar bleiben.' },
  { id: 'f25', t: 'fakt', e: '4️⃣', q: 'Das Wort „vier“ hat vier Buchstaben. Im Deutschen ist das die einzige Zahl, bei der das stimmt.' },
  { id: 'f26', t: 'fakt', e: '🔢', q: '111.111.111 · 111.111.111 = 12.345.678.987.654.321. Das ist ein richtig schönes Zahlenmuster!' },
  { id: 'f27', t: 'fakt', e: '➕', q: 'Die Rechenzeichen + und − gibt es gedruckt seit über 500 Jahren.' },
  { id: 'f28', t: 'fakt', e: '🐦', q: 'Kolibris können rückwärts fliegen. Das schafft sonst kein anderer Vogel.' },
  { id: 'f29', t: 'fakt', e: '🐌', q: 'Eine Gartenschnecke hat mehrere tausend winzige Zähnchen auf ihrer Zunge.' },
  { id: 'f30', t: 'fakt', e: '🦘', q: 'Kängurus können kaum rückwärts gehen.' },
  { id: 'f31', t: 'fakt', e: '🐘', q: 'Elefanten können nicht springen.' },
  { id: 'f32', t: 'fakt', e: '🌙', q: 'Der Mond entfernt sich jedes Jahr ein paar Zentimeter von der Erde.' },

  // Witze (ursprünglich)
  { id: 'w01', t: 'witz', e: '🥬', q: 'Was ist grün und klopft an die Tür?', a: 'Ein Klopfsalat!' },
  { id: 'w02', t: 'witz', e: '🎱', q: 'Was sagt die Null zur Acht?', a: '„Schicker Gürtel!“' },
  { id: 'w03', t: 'witz', e: '📘', q: 'Warum ist das Mathebuch so traurig?', a: 'Es hat so viele Probleme.' },
  { id: 'w04', t: 'witz', e: '🏴‍☠️', q: 'Was macht ein Pirat am Computer?', a: 'Er drückt die Enter-Taste.' },
  { id: 'w05', t: 'witz', e: '🖍️', q: 'Was sagt der große Stift zum kleinen Stift?', a: '„Wachs-mal-stift!“' },
  { id: 'w06', t: 'witz', e: '🍪', q: 'Was ist ein Keks unter einem Baum?', a: 'Ein schattiges Plätzchen.' },
  { id: 'w07', t: 'witz', e: '🐴', q: 'Wie nennt man ein Pferd, das im Wasser lebt?', a: 'Seepferdchen!' },
  { id: 'w08', t: 'witz', e: '🍎', q: 'Was ist schlimmer als ein Wurm im Apfel?', a: 'Ein halber Wurm.' },
  { id: 'w09', t: 'witz', e: '👻', q: 'Warum können Geister so schlecht lügen?', a: 'Man kann einfach durch sie hindurchschauen.' },
  { id: 'w10', t: 'witz', e: '🤡', q: 'Was macht ein Clown im Büro?', a: 'Faxen!' },
  { id: 'w11', t: 'witz', e: '🪃', q: 'Wie nennt man einen Bumerang, der nicht zurückkommt?', a: 'Stock.' },
  { id: 'w12', t: 'witz', e: '🚜', q: 'Was ist gelb und kann nicht schwimmen?', a: 'Ein Bagger.' },
  { id: 'w13', t: 'witz', e: '🧲', q: 'Zwei Magnete treffen sich. Sagt der eine zum anderen …', a: '„Was soll ich nur anziehen?“' },
  { id: 'w14', t: 'witz', e: '🍪', q: 'Wie viele Kekse kann man auf nüchternen Magen essen?', a: 'Nur einen. Danach ist der Magen nicht mehr nüchtern.' },
  { id: 'w15', t: 'witz', e: '🧮', q: 'Was sagt ein Taschenrechner zum anderen?', a: '„Du kannst auf mich zählen!“' },

  // Knobelfragen (ursprünglich)
  { id: 'q01', t: 'frage', e: '🐴', q: 'Wie viele Beine haben 3 Pferde und 2 Enten zusammen?', a: '16 Beine: 3 · 4 + 2 · 2 = 12 + 4 = 16.' },
  { id: 'q02', t: 'frage', e: '🍎', q: 'Du hast 5 Äpfel und nimmst 3 weg. Wie viele Äpfel hast du dann?', a: 'Du hast 3 – nämlich die, die du genommen hast!' },
  { id: 'q03', t: 'frage', e: '📅', q: 'Wie viele Monate haben 28 Tage?', a: 'Alle 12! Jeder Monat hat mindestens 28 Tage.' },
  { id: 'q04', t: 'frage', e: '🪶', q: 'Was ist schwerer: ein Kilo Federn oder ein Kilo Steine?', a: 'Beides wiegt gleich viel: ein Kilo.' },
  { id: 'q05', t: 'frage', e: '➖', q: 'Wie oft kannst du 10 von 100 abziehen?', a: 'Nur einmal. Danach hast du 90 und nicht mehr 100.' },
  { id: 'q06', t: 'frage', e: '🙃', q: 'Welche Zahl wird größer, wenn du sie auf den Kopf stellst?', a: 'Die 6: Auf den Kopf gestellt wird sie zur 9.' },
  { id: 'q07', t: 'frage', e: '🪙', q: 'Wie viele 50-Cent-Münzen brauchst du für 10 Euro?', a: '20 Münzen, denn 2 Münzen sind schon 1 Euro.' },
  { id: 'q08', t: 'frage', e: '💰', q: 'Welche drei Münzen ergeben zusammen genau 35 Cent?', a: '20 ct + 10 ct + 5 ct.' },
  { id: 'q09', t: 'frage', e: '🔟', q: 'Wie viele Zehner stecken in 240?', a: '24 Zehner, denn 240 : 10 = 24.' },
  { id: 'q10', t: 'frage', e: '🤔', q: 'Ich denke an eine Zahl. Teile ich sie durch 10, kommt 7 heraus. Welche Zahl ist es?', a: '70, denn 70 : 10 = 7.' },
  { id: 'q11', t: 'frage', e: '✂️', q: 'Wie oft passt die 20 in die 100?', a: '5-mal, denn 5 · 20 = 100.' },
  { id: 'q12', t: 'frage', e: '🍬', q: 'Du teilst 120 Bonbons gerecht unter 40 Kindern auf. Wie viele bekommt jedes Kind?', a: '3 Bonbons, denn 120 : 40 = 3.' },
  { id: 'q13', t: 'frage', e: '🍦', q: 'Ein Eis kostet 1,50 €. Wie viel kosten 4 Eis?', a: '6,00 €, denn 4 · 1,50 € = 6,00 €.' },
  { id: 'q14', t: 'frage', e: '💶', q: 'Was ist mehr wert: eine Million Cent oder eine Million Euro?', a: 'Eine Million Euro! Eine Million Cent sind nur 10.000 €.' },
  { id: 'q15', t: 'frage', e: '🌾', q: 'Ein Pony frisst am Tag 2 kg Heu. Wie viel Heu braucht es in einer Woche?', a: '14 kg, denn 7 · 2 kg = 14 kg.' },
  { id: 'q16', t: 'frage', e: '🐰', q: 'Ein Hase hat 2 Ohren. Wie viele Ohren haben 10 Hasen?', a: '20 Ohren.' },
  { id: 'q17', t: 'frage', e: '💸', q: 'Du bezahlst etwas für 3,20 € mit einem 5-Euro-Schein. Wie viel Rückgeld bekommst du?', a: '1,80 €.' },
  { id: 'q18', t: 'frage', e: '🕸️', q: 'Wie viele Beine haben 5 Spinnen zusammen?', a: '40 Beine, denn 5 · 8 = 40.' },
  { id: 'q19', t: 'frage', e: '🪙', q: 'Du hast 10 Münzen zu je 10 Cent. Wie viel Geld ist das?', a: '100 Cent, also 1 Euro.' },
  { id: 'q20', t: 'frage', e: '🐭', q: 'Wenn 3 Mäuse in 3 Minuten 3 Stück Käse fressen: Wie viele Mäuse brauchen 100 Minuten für 100 Stück Käse?', a: 'Auch nur 3 Mäuse! Jede Maus frisst alle 3 Minuten ein Stück.' },

  // Fakten (neu)
  { id: 'f33', t: 'fakt', e: '🦥', q: 'Faultiere klettern nur etwa einmal pro Woche vom Baum herunter – um aufs Klo zu gehen.', a: 'Dafür sind sie so langsam, dass sich auf ihrem Fell sogar Algen ansiedeln.' },
  { id: 'f34', t: 'fakt', e: '🐾', q: 'Wombats machen würfelförmige Köttel. Damit markieren sie ihr Revier und die Würfel rollen nicht weg.' },
  { id: 'f35', t: 'fakt', e: '🐋', q: 'Das Herz eines Blauwals wiegt etwa 180 Kilo. Das ist mehr als ein erwachsener Mensch.' },
  { id: 'f36', t: 'fakt', e: '🐝', q: 'Eine Honigbiene stellt in ihrem ganzen Leben nur etwa ein Zwölftel Teelöffel Honig her.' },
  { id: 'f37', t: 'fakt', e: '🐜', q: 'Eine Ameise kann das Vielfache ihres eigenen Gewichts tragen. Bei manchen Arten ist es bis zum 50-Fachen.' },
  { id: 'f38', t: 'fakt', e: '🦋', q: 'Schmetterlinge schmecken mit den Füßen. Sobald sie auf einem Blatt landen, wissen sie, ob es schmeckt.' },
  { id: 'f39', t: 'fakt', e: '🐕', q: 'Der Nasenabdruck eines Hundes ist einzigartig – wie dein Fingerabdruck.' },
  { id: 'f40', t: 'fakt', e: '🦓', q: 'Jedes Zebra hat ein eigenes Streifenmuster. Kein Zebra sieht aus wie das andere.' },
  { id: 'f41', t: 'fakt', e: '🦉', q: 'Eulen können ihren Kopf etwa 270 Grad drehen, also drei Viertel im Kreis.' },
  { id: 'f42', t: 'fakt', e: '🐆', q: 'Der Gepard ist das schnellste Landtier und schafft auf kurzen Strecken rund 100 km/h.' },
  { id: 'f43', t: 'fakt', e: '🦅', q: 'Im Sturzflug kann ein Wanderfalke schneller als 300 km/h werden. Er ist das schnellste Tier der Welt.' },
  { id: 'f44', t: 'fakt', e: '🐦', q: 'Das Herz eines Kolibris schlägt mehr als 1000-mal pro Minute.' },
  { id: 'f45', t: 'fakt', e: '🐘', q: 'Elefanten erkennen sich im Spiegel. Das können nur sehr wenige Tierarten.' },
  { id: 'f46', t: 'fakt', e: '🐦', q: 'Krähen erkennen einzelne Menschen wieder und merken sich, wer nett zu ihnen war.' },
  { id: 'f47', t: 'fakt', e: '🦇', q: 'Fledermäuse sind die einzigen Säugetiere, die richtig fliegen können.' },
  { id: 'f48', t: 'fakt', e: '🐨', q: 'Koalas schlafen am Tag bis zu 20 Stunden. Ihr Eukalyptus-Futter gibt nur wenig Energie.' },
  { id: 'f49', t: 'fakt', e: '🦏', q: 'Das Horn eines Nashorns besteht aus Keratin – dem gleichen Stoff wie deine Fingernägel.' },
  { id: 'f50', t: 'fakt', e: '🐧', q: 'Kaiserpinguin-Papas balancieren das Ei monatelang auf ihren Füßen und wärmen es mit einer Bauchfalte.' },
  { id: 'f51', t: 'fakt', e: '🦎', q: 'Ein Axolotl kann verlorene Beine, ja sogar Teile des Herzens wieder nachwachsen lassen.' },
  { id: 'f52', t: 'fakt', e: '⭐', q: 'Seesterne haben kein Gehirn und kein Herz. Sie pumpen stattdessen Meerwasser durch ihren Körper.' },
  { id: 'f53', t: 'fakt', e: '🐢', q: 'Der Panzer einer Schildkröte gehört zu ihrem Skelett. Sie kann ihn nicht ausziehen wie eine Jacke.' },
  { id: 'f54', t: 'fakt', e: '🦁', q: 'Löwen schlafen bis zu 20 Stunden am Tag.' },
  { id: 'f55', t: 'fakt', e: '🐝', q: 'Bienen tanzen, um ihren Stockgenossinnen zu zeigen, in welcher Richtung leckere Blumen wachsen. Das heißt Schwänzeltanz.' },
  { id: 'f56', t: 'fakt', e: '🐅', q: 'Tiger haben nicht nur im Fell Streifen, sondern auch auf der Haut. Rasiert man sie, bleibt das Muster.' },
  { id: 'f57', t: 'fakt', e: '✨', q: 'Glühwürmchen leuchten durch eine chemische Reaktion in ihrem Körper. Dabei entsteht fast keine Wärme.' },
  { id: 'f58', t: 'fakt', e: '🦟', q: 'Nur weibliche Stechmücken stechen. Die Männchen trinken Pflanzensaft.' },
  { id: 'f59', t: 'fakt', e: '🐪', q: 'Im Höcker eines Kamels steckt Fett, kein Wasser. Es dient als Energievorrat für lange Strecken.' },
  { id: 'f60', t: 'fakt', e: '🦦', q: 'Seeotter halten sich beim Schlafen an den Pfoten, damit sie im Wasser nicht auseinandertreiben.' },
  { id: 'f61', t: 'fakt', e: '🐻‍❄️', q: 'Das Fell eines Eisbären ist eigentlich durchsichtig und seine Haut schwarz. Weiß sieht es nur aus.' },
  { id: 'f62', t: 'fakt', e: '🌊', q: 'Quallen haben kein Gehirn, kein Herz und keine Knochen. Trotzdem gibt es sie schon seit über 500 Millionen Jahren.' },
  { id: 'f63', t: 'fakt', e: '🦘', q: 'Ein neugeborenes Känguru ist nur etwa 2 Zentimeter klein. Es krabbelt allein in den Beutel seiner Mama.' },
  { id: 'f64', t: 'fakt', e: '🦒', q: 'Die Zunge einer Giraffe ist etwa 45 Zentimeter lang und dunkelviolett. Das schützt sie vor Sonnenbrand.' },
  { id: 'f65', t: 'fakt', e: '🦆', q: 'Das Schnabeltier ist ein Säugetier, das Eier legt. Nur ganz wenige Säugetiere machen das.' },
  { id: 'f66', t: 'fakt', e: '🐦', q: 'Das Auge eines Straußes ist größer als sein Gehirn. Der Strauß ist der größte Vogel der Welt.' },
  { id: 'f67', t: 'fakt', e: '🦎', q: 'Chamäleons wechseln die Farbe vor allem, um mit anderen Chamäleons zu „sprechen“ und je nach Stimmung oder Temperatur – nicht nur zur Tarnung.' },
  { id: 'f68', t: 'fakt', e: '🐙', q: 'Ein Krake kann sich durch jede Lücke quetschen, die größer ist als sein harter Schnabel. Alles andere an ihm ist weich.' },
  { id: 'f69', t: 'fakt', e: '🦖', q: 'Vögel stammen von Dinosauriern ab. Ein Huhn ist also ein entfernter Verwandter des T. rex.' },
  { id: 'f70', t: 'fakt', e: '🦖', q: 'Ein Zahn des T. rex konnte mit Wurzel etwa 30 Zentimeter lang sein – so lang wie ein Lineal.' },
  { id: 'f71', t: 'fakt', e: '🦕', q: 'Das Wort „Dinosaurier“ heißt „schreckliche Echse“. Der Forscher Richard Owen hat es 1842 erfunden.' },
  { id: 'f72', t: 'fakt', e: '⏳', q: 'Zwischen dem Stegosaurus und dem T. rex liegen mehr Jahre als zwischen dem T. rex und uns.' },
  { id: 'f73', t: 'fakt', e: '🦕', q: 'Der Argentinosaurus war etwa 30 Meter lang – länger als ein Basketballfeld.' },
  { id: 'f74', t: 'fakt', e: '🦖', q: 'Der Velociraptor war nur so groß wie ein Truthahn. Und er hatte Federn!' },
  { id: 'f75', t: 'fakt', e: '💩', q: 'Versteinerter Dino-Kot heißt Koprolith. Forscher können daran erkennen, was die Dinosaurier gefressen haben.' },
  { id: 'f76', t: 'fakt', e: '🦴', q: 'Flugsaurier wie der Pteranodon waren keine Dinosaurier, sondern eine eigene Tiergruppe.' },
  { id: 'f77', t: 'fakt', e: '☄️', q: 'Die Dinosaurier sind vor etwa 66 Millionen Jahren ausgestorben. Die ersten gab es vor rund 230 Millionen Jahren.' },
  { id: 'f78', t: 'fakt', e: '🌊', q: 'Der tiefste Punkt im Meer ist der Marianengraben im Pazifik – rund 11 Kilometer tief. Der Mount Everest würde darin komplett verschwinden.' },
  { id: 'f79', t: 'fakt', e: '🌍', q: 'Mehr als zwei Drittel der Erdoberfläche sind mit Wasser bedeckt.' },
  { id: 'f80', t: 'fakt', e: '🧂', q: 'In einem Liter Meerwasser sind etwa 35 Gramm Salz gelöst.' },
  { id: 'f81', t: 'fakt', e: '🐠', q: 'Das Great Barrier Reef vor Australien ist das größte Korallenriff der Welt. Es ist über 2000 Kilometer lang.' },
  { id: 'f82', t: 'fakt', e: '🐟', q: 'Korallen sind keine Pflanzen und keine Steine, sondern winzige Tiere.' },
  { id: 'f83', t: 'fakt', e: '🌬️', q: 'Die Meere liefern etwa die Hälfte des Sauerstoffs, den wir atmen – vor allem durch winzige Algen.' },
  { id: 'f84', t: 'fakt', e: '🔦', q: 'In der dunklen Tiefsee leuchten viele Tiere selbst. Der Anglerfisch lockt Beute mit einer leuchtenden Angel an.' },
  { id: 'f85', t: 'fakt', e: '🏊', q: 'Im Toten Meer ist so viel Salz, dass man nicht untergehen kann. Man liegt wie auf einer Luftmatratze.' },
  { id: 'f86', t: 'fakt', e: '🌙', q: 'Ebbe und Flut entstehen vor allem durch die Anziehungskraft des Mondes.' },
  { id: 'f87', t: 'fakt', e: '🌊', q: 'Der Pazifik ist so groß, dass alle Kontinente der Erde zusammen hineinpassen würden.' },
  { id: 'f88', t: 'fakt', e: '👣', q: 'Fußspuren auf dem Mond bleiben sehr lange erhalten, weil es dort keinen Wind und keinen Regen gibt.' },
  { id: 'f89', t: 'fakt', e: '🪐', q: 'Ein Tag auf Jupiter dauert nur etwa 10 Stunden. Er dreht sich schneller als alle anderen Planeten.' },
  { id: 'f90', t: 'fakt', e: '🪐', q: 'Saturn ist so leicht gebaut, dass er in einer riesigen Badewanne schwimmen würde.' },
  { id: 'f91', t: 'fakt', e: '🌞', q: 'Das Licht der Sonne braucht rund 8 Minuten bis zur Erde. Du siehst die Sonne also immer, wie sie vor 8 Minuten war.' },
  { id: 'f92', t: 'fakt', e: '🔵', q: 'Neptun braucht etwa 165 Erdenjahre für eine einzige Runde um die Sonne.' },
  { id: 'f93', t: 'fakt', e: '🔇', q: 'Im Weltall kann man keinen Ton hören, weil dort keine Luft ist, die den Schall weitergibt.' },
  { id: 'f94', t: 'fakt', e: '🧑‍🚀', q: 'Im Weltall werden Astronauten ein paar Zentimeter größer, weil sich ihre Wirbelsäule ohne Schwerkraft streckt.' },
  { id: 'f95', t: 'fakt', e: '⭐', q: 'Wenn du nachts einen Stern siehst, war sein Licht oft hunderte oder tausende Jahre unterwegs. Du schaust in die Vergangenheit!' },
  { id: 'f96', t: 'fakt', e: '🔴', q: 'Der Mars sieht rot aus, weil sein Boden voller Rost ist – also Eisenoxid.' },
  { id: 'f97', t: 'fakt', e: '🌋', q: 'Der Olympus Mons auf dem Mars ist der größte Vulkan im Sonnensystem. Er ist etwa 2,5-mal so hoch wie der Mount Everest.' },
  { id: 'f98', t: 'fakt', e: '🛰️', q: 'Die Raumstation ISS umrundet die Erde etwa alle 90 Minuten. Die Astronauten erleben jeden Tag 16 Sonnenaufgänge.' },
  { id: 'f99', t: 'fakt', e: '🚀', q: 'Der erste Mensch im Weltall war 1961 der Russe Juri Gagarin. Sein Flug dauerte nur etwa 108 Minuten.' },
  { id: 'f100', t: 'fakt', e: '🌟', q: 'Ein Teelöffel Material von einem Neutronenstern würde Milliarden Tonnen wiegen.' },
  { id: 'f101', t: 'fakt', e: '🌙', q: 'Auf dem Mond gibt es Mondbeben. Sie werden von Messgeräten aufgezeichnet, die Astronauten dort aufgestellt haben.' },
  { id: 'f102', t: 'fakt', e: '🔥', q: 'Die Venus ist der heißeste Planet im Sonnensystem – mit rund 460 Grad sogar heißer als der Merkur, der näher an der Sonne ist.' },
  { id: 'f103', t: 'fakt', e: '🌍', q: 'Die Erde ist keine perfekte Kugel. Am Äquator ist sie ein kleines Stück dicker als von Pol zu Pol.' },
  { id: 'f104', t: 'fakt', e: '⚖️', q: 'Auf dem Mond würdest du nur etwa ein Sechstel deines Gewichts wiegen. Du könntest dort richtig hoch springen!' },
  { id: 'f105', t: 'fakt', e: '💍', q: 'Die Ringe des Saturn bestehen aus unzähligen Eis- und Gesteinsbrocken – manche winzig, manche so groß wie ein Haus.' },
  { id: 'f106', t: 'fakt', e: '🌈', q: 'Ein Regenbogen ist eigentlich ein ganzer Kreis. Vom Boden aus siehst du nur den oberen Halbkreis.' },
  { id: 'f107', t: 'fakt', e: '❄️', q: 'Jede Schneeflocke hat sechs Ecken oder Arme. Und trotzdem gleicht kaum eine der anderen.' },
  { id: 'f108', t: 'fakt', e: '🧊', q: 'Die größte Wüste der Welt ist keine Sandwüste, sondern die Antarktis – eine Wüste aus Eis.' },
  { id: 'f109', t: 'fakt', e: '⚡', q: 'Zähle nach einem Blitz die Sekunden bis zum Donner und teile durch 3: Das ist ungefähr die Entfernung in Kilometern.' },
  { id: 'f110', t: 'fakt', e: '🏔️', q: 'Die Kontinente wandern jedes Jahr ein paar Zentimeter – etwa so schnell, wie deine Fingernägel wachsen.' },
  { id: 'f111', t: 'fakt', e: '⛰️', q: 'Die Anden in Südamerika sind das längste Gebirge der Welt: mehr als 7000 Kilometer.' },
  { id: 'f112', t: 'fakt', e: '🏜️', q: 'Die Sahara war vor einigen tausend Jahren mal grün, mit Seen, Gras und Tieren.' },
  { id: 'f113', t: 'fakt', e: '🌤️', q: 'Der Himmel ist blau, weil die Luft das blaue Licht der Sonne viel stärker in alle Richtungen streut als das rote.' },
  { id: 'f114', t: 'fakt', e: '🧊', q: 'Wasser ist einer der wenigen Stoffe, die gefroren leichter werden: Eis schwimmt oben. Deshalb frieren Seen von oben zu und die Fische überleben unten.' },
  { id: 'f115', t: 'fakt', e: '🌅', q: 'Am Südpol gibt es im ganzen Jahr nur einen Sonnenaufgang und einen Sonnenuntergang.' },
  { id: 'f116', t: 'fakt', e: '🎋', q: 'Manche Bambusarten wachsen bis zu 90 Zentimeter an einem einzigen Tag.' },
  { id: 'f117', t: 'fakt', e: '🌻', q: 'Junge Sonnenblumen drehen ihre Blüten im Lauf des Tages mit der Sonne mit. Wenn sie erwachsen sind, schauen sie nach Osten.' },
  { id: 'f118', t: 'fakt', e: '🎃', q: 'Auch Kürbisse und Gurken sind für Pflanzenforscher Beeren.' },
  { id: 'f119', t: 'fakt', e: '🌲', q: 'Küsten-Mammutbäume in Kalifornien werden über 100 Meter hoch – höher als jeder andere Baum.' },
  { id: 'f120', t: 'fakt', e: '🍎', q: 'Ein Apfel besteht zu etwa 85 Prozent aus Wasser.' },
  { id: 'f121', t: 'fakt', e: '🪴', q: 'Die Venusfliegenfalle klappt zu, wenn ein Insekt innerhalb kurzer Zeit zweimal ihre Fühlhaare berührt. So spart sie Energie bei Fehlalarm.' },
  { id: 'f122', t: 'fakt', e: '🥔', q: 'Die Kartoffel ist mit der Tomate verwandt. Beide gehören zu den Nachtschattengewächsen.' },
  { id: 'f123', t: 'fakt', e: '🥜', q: 'Erdnüsse sind gar keine Nüsse, sondern Hülsenfrüchte – wie Erbsen. Sie reifen unter der Erde.' },
  { id: 'f124', t: 'fakt', e: '🌺', q: 'Die größte Blume der Welt, die Rafflesia, wird fast einen Meter breit. Sie riecht aber nach faulem Fleisch.' },
  { id: 'f125', t: 'fakt', e: '🍍', q: 'Ananas wachsen nicht an Bäumen, sondern am Boden zwischen spitzen Blättern.' },
  { id: 'f126', t: 'fakt', e: '🌿', q: 'Pflanzen machen aus Sonnenlicht, Wasser und Kohlendioxid Zucker – und geben dabei Sauerstoff ab. Das nennt man Photosynthese.' },
  { id: 'f127', t: 'fakt', e: '🦴', q: 'Babys haben über 270 Knochen. Erwachsene haben nur noch 206, weil viele Knochen zusammenwachsen.' },
  { id: 'f128', t: 'fakt', e: '🦵', q: 'Der Oberschenkelknochen ist der längste und stärkste Knochen im Körper.' },
  { id: 'f129', t: 'fakt', e: '🧠', q: 'Dein Gehirn hat etwa 86 Milliarden Nervenzellen und verbraucht rund ein Fünftel deiner Energie.' },
  { id: 'f130', t: 'fakt', e: '🖐️', q: 'Die Haut ist das größte Organ deines Körpers.' },
  { id: 'f131', t: 'fakt', e: '💅', q: 'Fingernägel wachsen etwa 3 Millimeter im Monat – Zehennägel noch langsamer.' },
  { id: 'f132', t: 'fakt', e: '👅', q: 'Auch der Abdruck deiner Zunge ist einzigartig – wie ein Fingerabdruck.' },
  { id: 'f133', t: 'fakt', e: '👂', q: 'Der kleinste Knochen im Körper sitzt im Ohr. Er heißt Steigbügel und ist nur etwa 3 Millimeter lang.' },
  { id: 'f134', t: 'fakt', e: '👀', q: 'Dein Auge sieht die Welt eigentlich auf dem Kopf stehend. Dein Gehirn dreht das Bild automatisch um.' },
  { id: 'f135', t: 'fakt', e: '🦷', q: 'Zahnschmelz ist der härteste Stoff in deinem Körper – härter als Knochen.' },
  { id: 'f136', t: 'fakt', e: '📏', q: 'Morgens bist du etwa einen Zentimeter größer als abends, weil sich deine Wirbelsäule tagsüber zusammendrückt.' },
  { id: 'f137', t: 'fakt', e: '💧', q: 'Dein Mund macht jeden Tag etwa einen Liter Spucke.' },
  { id: 'f138', t: 'fakt', e: '🩸', q: 'Ein Erwachsener hat etwa 5 Liter Blut im Körper.' },
  { id: 'f139', t: 'fakt', e: '🏅', q: 'Die fünf Olympischen Ringe stehen für die fünf Kontinente, die beim Sport zusammenkommen.' },
  { id: 'f140', t: 'fakt', e: '🏀', q: 'Basketball wurde 1891 erfunden. Damals waren die Körbe echte Pfirsichkörbe – und man musste nach jedem Treffer den Ball herausholen.' },
  { id: 'f141', t: 'fakt', e: '🏃', q: 'Ein Marathon ist 42,195 Kilometer lang. Die krumme Länge geht auf die Olympischen Spiele 1908 in London zurück.' },
  { id: 'f142', t: 'fakt', e: '⛳', q: 'Ein Golfball hat etwa 300 bis 500 kleine Dellen. Mit ihnen fliegt er viel weiter als ein glatter Ball.' },
  { id: 'f143', t: 'fakt', e: '⚡', q: 'Usain Bolt rannte 2009 die 100 Meter in 9,58 Sekunden. Das ist ein Schnitt von fast 38 km/h.' },
  { id: 'f144', t: 'fakt', e: '🏀', q: 'Ein Basketballkorb hängt überall auf der Welt in genau 3,05 Metern Höhe.' },
  { id: 'f145', t: 'fakt', e: '🎾', q: 'Beim Tennisturnier in Wimbledon müssen die Spielerinnen und Spieler ganz in Weiß spielen.' },
  { id: 'f146', t: 'fakt', e: '⚽', q: 'Ein Fußballprofi läuft in einem Spiel oft mehr als 10 Kilometer.' },
  { id: 'f147', t: 'fakt', e: '🍫', q: 'Kakaobohnen waren bei den Maya und Azteken so wertvoll, dass man sie als Geld benutzt hat.' },
  { id: 'f148', t: 'fakt', e: '🥕', q: 'Früher waren Karotten oft lila oder gelb. Die orangen sind erst später gezüchtet worden.' },
  { id: 'f149', t: 'fakt', e: '🍿', q: 'Popcorn platzt, weil das Wasser im Maiskorn heiß wird, zu Dampf wird und die harte Schale sprengt.' },
  { id: 'f150', t: 'fakt', e: '🧀', q: 'Die Löcher im Emmentaler entstehen durch kleine Gasblasen, die bei der Reifung im Käse entstehen.' },
  { id: 'f151', t: 'fakt', e: '🧅', q: 'Beim Zwiebelschneiden weinst du, weil die Zwiebel ein scharfes Gas freisetzt, das deine Augen reizt.' },
  { id: 'f152', t: 'fakt', e: '🍉', q: 'Eine Wassermelone besteht zu mehr als 90 Prozent aus Wasser.' },
  { id: 'f153', t: 'fakt', e: '🥚', q: 'Ob ein Ei weiß oder braun ist, hängt nur vom Huhn ab, nicht vom Inhalt. Drinnen schmecken beide gleich.' },
  { id: 'f154', t: 'fakt', e: '🖱️', q: 'Die erste Computermaus war aus Holz. Der Erfinder Douglas Engelbart baute sie in den 1960er-Jahren.' },
  { id: 'f155', t: 'fakt', e: '📚', q: 'Um 1450 erfand Johannes Gutenberg in Mainz den Buchdruck mit beweglichen Buchstaben. Bücher konnten nun viel schneller entstehen.' },
  { id: 'f156', t: 'fakt', e: '📷', q: 'Das erste erhaltene Foto der Welt entstand um 1826. Es musste mehrere Stunden belichtet werden.' },
  { id: 'f157', t: 'fakt', e: '💻', q: 'Der deutsche Ingenieur Konrad Zuse baute 1941 in Berlin mit dem Z3 einen der ersten programmierbaren Computer der Welt.' },
  { id: 'f158', t: 'fakt', e: '🛞', q: 'Das Rad ist etwa 5500 Jahre alt. Erst viel später kam jemand auf die Idee, es zum Wagenbau zu nutzen.' },
  { id: 'f159', t: 'fakt', e: '📱', q: 'Die erste SMS der Welt wurde 1992 verschickt. Sie lautete: „Merry Christmas“.' },
  { id: 'f160', t: 'fakt', e: '🌐', q: 'Die erste Webseite der Welt ging 1991 online. Erfunden hat das World Wide Web der Forscher Tim Berners-Lee.' },
  { id: 'f161', t: 'fakt', e: '🍫', q: 'Die Mikrowelle wurde durch Zufall erfunden: Ein Forscher bemerkte, dass ihm ein Schokoriegel in der Tasche geschmolzen war.' },
  { id: 'f162', t: 'fakt', e: '✈️', q: 'Beim ersten Motorflug der Brüder Wright 1903 flog das Flugzeug nur 12 Sekunden und etwa 37 Meter weit.' },
  { id: 'f163', t: 'fakt', e: '🔺', q: 'Die Cheops-Pyramide in Ägypten ist mehr als 4500 Jahre alt. Sie war weit über 3000 Jahre lang das höchste Bauwerk der Welt.' },
  { id: 'f164', t: 'fakt', e: '⚔️', q: 'Wikinger trugen gar keine Helme mit Hörnern. Das ist eine spätere Erfindung von Malern und Kostümbildnern.' },
  { id: 'f165', t: 'fakt', e: '🏔️', q: 'Ötzi, der Mann aus dem Gletscher, lebte vor etwa 5300 Jahren. Er wurde 1991 in den Alpen gefunden.' },
  { id: 'f166', t: 'fakt', e: '🏟️', q: 'Im Kolosseum in Rom fanden etwa 50.000 Zuschauer Platz.' },
  { id: 'f167', t: 'fakt', e: '👑', q: 'Kleopatra lebte zeitlich näher an der Mondlandung als am Bau der Cheops-Pyramide.' },
  { id: 'f168', t: 'fakt', e: '📜', q: 'Das längste Wort, das es je als deutsches Gesetz gab, hatte 63 Buchstaben: „Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz“. Es wurde 2013 abgeschafft.' },
  { id: 'f169', t: 'fakt', e: '🤖', q: 'Das Wort „Roboter“ kommt aus dem Tschechischen. „Robota“ heißt dort „Arbeit“ oder „Fronarbeit“.' },
  { id: 'f170', t: 'fakt', e: '🔁', q: '„Reliefpfeiler“ ist ein Palindrom: Von vorne und von hinten gelesen ergibt es dasselbe Wort.' },
  { id: 'f171', t: 'fakt', e: '🗣️', q: 'Auf der Welt gibt es rund 7000 Sprachen. Allein in Papua-Neuguinea werden mehr als 800 gesprochen.' },
  { id: 'f172', t: 'fakt', e: '🏫', q: 'Das deutsche Wort „Kindergarten“ benutzen Menschen auf der ganzen Welt, zum Beispiel auch im Englischen.' },
  { id: 'f173', t: 'fakt', e: '⌨️', q: '„Zwölf Boxkämpfer jagen Viktor quer über den großen Sylter Deich“ enthält jeden Buchstaben des Alphabets mindestens einmal. So einen Satz nennt man Pangramm.' },
  { id: 'f174', t: 'fakt', e: '🔢', q: 'Ein Googol ist eine 1 mit 100 Nullen. Den Namen hat sich der neunjährige Neffe eines Mathematikers ausgedacht.' },
  { id: 'f175', t: 'fakt', e: '2️⃣', q: 'Die 2 ist die einzige gerade Primzahl. Alle anderen geraden Zahlen kann man durch 2 teilen.' },
  { id: 'f176', t: 'fakt', e: '🥧', q: 'Der Pi-Tag ist am 14. März. Warum? Pi beginnt mit 3,14 und in der US-Schreibweise ist das der 3/14.' },
  { id: 'f177', t: 'fakt', e: '🎲', q: 'Auf einem normalen Würfel ergeben gegenüberliegende Seiten immer 7: 1 und 6, 2 und 5, 3 und 4.' },
  { id: 'f178', t: 'fakt', e: '📄', q: 'Wenn du ein Blatt Papier 42-mal falten könntest, wäre der Stapel in der Theorie dicker als die Strecke von der Erde bis zum Mond.' },
  { id: 'f179', t: 'fakt', e: '🏛️', q: 'Die Römer hatten keine Null in ihren Ziffern. Die Zahl 0 kam erst viel später nach Europa.' },
  { id: 'f180', t: 'fakt', e: '🌼', q: 'Viele Blumen haben 3, 5, 8, 13 oder 21 Blütenblätter. Das sind Zahlen aus der Fibonacci-Reihe: Jede Zahl ist die Summe der beiden davor.' },
  { id: 'f181', t: 'fakt', e: '🔟', q: 'Eine Billion hat zwölf Nullen: 1.000.000.000.000.' },
  { id: 'f182', t: 'fakt', e: '🕐', q: 'Ein Dutzend sind 12 Stück. Ein Gros sind 144 – also ein Dutzend Dutzend.' },
  { id: 'f183', t: 'fakt', e: '🕒', q: 'Russland ist so riesig, dass es 11 Zeitzonen hat.' },
  { id: 'f184', t: 'fakt', e: '🗺️', q: 'Deutschland hat 9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, die Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.' },
  { id: 'f185', t: 'fakt', e: '⛰️', q: 'Der höchste Berg Deutschlands ist die Zugspitze mit etwa 2960 Metern.' },
  { id: 'f186', t: 'fakt', e: '🌍', q: 'Afrika besteht aus 54 Ländern.' },
  { id: 'f187', t: 'fakt', e: '🚤', q: 'Venedig ist auf über 100 kleinen Inseln gebaut. Statt Straßen gibt es dort viele Kanäle.' },
  { id: 'f188', t: 'fakt', e: '🏝️', q: 'Indonesien besteht aus mehr als 17.000 Inseln.' },
  { id: 'f189', t: 'fakt', e: '⛪', q: 'Der Vatikan in Rom ist der kleinste Staat der Welt. Er ist kleiner als ein großer Stadtpark.' },
  { id: 'f190', t: 'fakt', e: '🐋', q: 'Der Blauwal ist das größte Tier, das jemals auf der Erde gelebt hat – bis zu 30 Meter lang.' },
  { id: 'f191', t: 'fakt', e: '🦒', q: 'Die Giraffe ist das höchste Tier der Welt. Ein Bulle kann etwa 5,5 Meter groß werden.' },
  { id: 'f192', t: 'fakt', e: '🐦', q: 'Die Bienenelfe aus Kuba ist der kleinste Vogel der Welt: etwa 6 Zentimeter lang und wiegt nur etwa 2 Gramm.' },
  { id: 'f193', t: 'fakt', e: '🏙️', q: 'Der Burj Khalifa in Dubai ist mit etwa 830 Metern das höchste Gebäude der Welt.' },
  { id: 'f194', t: 'fakt', e: '🌲', q: 'Manche Kiefern in den USA sind fast 5000 Jahre alt. Sie gehören zu den ältesten Lebewesen der Erde.' },
  { id: 'f195', t: 'fakt', e: '🧊', q: 'Grönland ist die größte Insel der Welt – wenn man Australien als Kontinent und nicht als Insel zählt.' },

  // Witze (neu)
  { id: 'w16', t: 'witz', e: '🐪', q: 'Was ist braun, klebrig und läuft durch die Wüste?', a: 'Ein Karamell!' },
  { id: 'w17', t: 'witz', e: '🌱', q: 'Was macht ein Mathelehrer im Garten?', a: 'Er zieht Wurzeln.' },
  { id: 'w18', t: 'witz', e: '🤠', q: 'Was ist ein Cowboy ohne Pferd?', a: 'Ein Sattelschlepper.' },
  { id: 'w19', t: 'witz', e: '🍄', q: 'Was ist rot und steht im Wald?', a: 'Ein Zwerg mit Sonnenbrand.' },
  { id: 'w20', t: 'witz', e: '🗼', q: 'Was steht mitten in Paris?', a: 'Das R.' },
  { id: 'w21', t: 'witz', e: '🐟', q: 'Was sagt ein Fisch, der gegen die Wand schwimmt?', a: '„Damm!“' },
  { id: 'w22', t: 'witz', e: '🥬', q: 'Was ist grün und schaut durchs Schlüsselloch?', a: 'Ein Spionat.' },
  { id: 'w23', t: 'witz', e: '🐘', q: 'Hast du schon mal einen Elefanten im Kirschbaum gesehen?', a: 'Nein? Siehst du, so gut tarnt er sich!' },
  { id: 'w24', t: 'witz', e: '💻', q: 'Was isst ein Computer am liebsten?', a: 'Chips.' },
  { id: 'w25', t: 'witz', e: '🐠', q: 'Was ist ein Fisch ohne Augen?', a: 'Fsch!' },
  { id: 'w26', t: 'witz', e: '⛄', q: 'Was sagt ein Schneemann zum anderen?', a: '„Riechst du auch Karotten?“' },
  { id: 'w27', t: 'witz', e: '🍊', q: 'Was ist orange und läuft durch den Wald?', a: 'Eine Wanderine.' },
  { id: 'w28', t: 'witz', e: '🍅', q: 'Was sagt die große Tomate zur kleinen Tomate?', a: '„Komm, Ketchup!“' },
  { id: 'w29', t: 'witz', e: '⚓', q: 'Was liegt am Meeresgrund und zittert?', a: 'Ein nervliches Wrack.' },
  { id: 'w30', t: 'witz', e: '🕯️', q: 'Zwei Kerzen treffen sich. Fragt die eine die andere …', a: '„Wollen wir ausgehen?“' },
  { id: 'w31', t: 'witz', e: '🐻‍❄️', q: 'Wie viel wiegt ein Eisbär?', a: 'Genug, um das Eis zu brechen.' },
  { id: 'w32', t: 'witz', e: '🐂', q: 'Wie nennt man einen schlafenden Stier?', a: 'Bulldozer!' },
  { id: 'w33', t: 'witz', e: '🕶️', q: 'Warum trägt die Lehrerin eine Sonnenbrille im Unterricht?', a: 'Weil ihre Klasse so eine strahlende Zukunft hat.' },
  { id: 'w34', t: 'witz', e: '🦁', q: 'Die Lehrerin fragt: „Fritzchen, nenne mir fünf Tiere, die in Afrika leben!“', a: 'Fritzchen: „Ein Löwe und vier Elefanten.“' },
  { id: 'w35', t: 'witz', e: '🏫', q: 'Die Lehrerin fragt: „Fritzchen, warum kommst du schon wieder zu spät?“', a: '„Da stand ein Schild: Achtung Schule, bitte langsam fahren!“' },
  { id: 'w36', t: 'witz', e: '🎱', q: 'Was ist grün, hat vier Beine und fällt vom Baum?', a: 'Ein Billardtisch.' },
  { id: 'w37', t: 'witz', e: '🧱', q: 'Treffen sich zwei Wände. Sagt die eine zur anderen …', a: '„Wir treffen uns an der Ecke!“' },
  { id: 'w38', t: 'witz', e: '🏖️', q: 'Was sagt das Meer zum Strand?', a: 'Nichts, es winkt nur.' },
  { id: 'w39', t: 'witz', e: '🐴', q: 'Was ist ein Zebra ohne Streifen?', a: 'Ein Esel.' },
  { id: 'w40', t: 'witz', e: '🐕', q: 'Mein Hund kann bis drei zählen. Frag ihn mal: Wie viel ist 3 minus 3?', a: 'Er sagt nichts.' },
  { id: 'w41', t: 'witz', e: '🎸', q: 'Was ist grün und kann Gitarre spielen?', a: 'Ein Rockfrosch.' },
  { id: 'w42', t: 'witz', e: '🐧', q: 'Wie nennt man einen Pinguin in der Wüste?', a: 'Verirrt.' },
  { id: 'w43', t: 'witz', e: '🕷️', q: 'Welches Tier ist am besten im Internet unterwegs?', a: 'Die Spinne. Sie hat das Netz schon immer zu Hause.' },
  { id: 'w44', t: 'witz', e: '☕', q: 'Was ist das Lieblingsgetränk der Hexe?', a: 'Ein Hex-presso!' },
  { id: 'w45', t: 'witz', e: '🥣', q: 'Was kann man zum Frühstück nicht essen?', a: 'Mittagessen und Abendessen.' },
  { id: 'w46', t: 'witz', e: '🐄', q: 'Warum trägt die Kuh eine Glocke?', a: 'Weil ihre Hörner nicht hupen.' },
  { id: 'w47', t: 'witz', e: '🚪', q: 'Welche Tür kann man nicht öffnen?', a: 'Die Tür-kei.' },
  { id: 'w48', t: 'witz', e: '🔵', q: 'Was sagt die Gerade zum Kreis?', a: '„Du drehst dich immer nur um dich selbst!“' },
  { id: 'w49', t: 'witz', e: '🔺', q: 'Was sagt der Kreis zum Dreieck?', a: '„Du hast aber Ecken und Kanten!“' },
  { id: 'w50', t: 'witz', e: '0️⃣', q: 'Warum ist die Null so beliebt?', a: 'Sie macht jede Zahl zehnmal so groß, wenn sie hinter ihr steht.' },
  { id: 'w51', t: 'witz', e: '🐿️', q: 'Wer ist der beste Rechner im Wald?', a: 'Das Eichhörnchen – es zählt jede Nuss.' },
  { id: 'w52', t: 'witz', e: '🔢', q: 'Zwei Gleichungen treffen sich. Sagt die eine zur anderen …', a: '„Wir passen super zusammen – wir sind ja gleich!“' },
  { id: 'w53', t: 'witz', e: '🐻', q: 'Wie nennt man einen Bären ohne Zähne?', a: 'Gummibär.' },
  { id: 'w54', t: 'witz', e: '🍎', q: 'Der Lehrer fragt: „Ich habe in der einen Hand 3 Äpfel und in der anderen 4. Was habe ich?“', a: 'Fritzchen: „Riesige Hände!“' },
  { id: 'w55', t: 'witz', e: '🍌', q: 'Was ist gelb und schwimmt im Wasser?', a: 'Ein Bananenboot.' },
  { id: 'w56', t: 'witz', e: '🐊', q: 'Was sagt der Zahnarzt zum Krokodil?', a: '„Bitte weit aufmachen – aber nicht ganz!“' },
  { id: 'w57', t: 'witz', e: '🐱', q: 'Welches Schulfach mag die Katze am liebsten?', a: 'Mäuse-matik.' },
  { id: 'w58', t: 'witz', e: '🐄', q: 'Welches Schulfach mag die Kuh am liebsten?', a: 'Muh-sik.' },
  { id: 'w59', t: 'witz', e: '🐘', q: 'Warum haben Elefanten keinen Computer?', a: 'Sie haben Angst vor der Maus.' },
  { id: 'w60', t: 'witz', e: '0️⃣', q: 'Welche Zahl hat nie Lust auf Mathe?', a: 'Die Null – sie hat null Bock.' },
  { id: 'w61', t: 'witz', e: '🦜', q: 'Was sagt der Papagei, wenn er in den Spiegel schaut?', a: '„Hübscher Vogel!“' },
  { id: 'w62', t: 'witz', e: '🐸', q: 'Was ist grün und macht Hicks?', a: 'Ein Frosch mit Schluckauf.' },

  // Knobelfragen (neu)
  { id: 'q21', t: 'frage', e: '🚆', q: 'Ein Zug hat 6 Wagen mit je 80 Plätzen. Wie viele Plätze sind das zusammen?', a: '480 Plätze, denn 6 · 80 = 480.' },
  { id: 'q22', t: 'frage', e: '👟', q: 'Am ersten Tag läufst du 3 km, an jedem weiteren Tag 2 km mehr als am Tag davor. Wie viele Kilometer sind es nach 4 Tagen insgesamt?', a: '24 km: 3 + 5 + 7 + 9 = 24.' },
  { id: 'q23', t: 'frage', e: '🔢', q: 'Wie geht die Reihe weiter? 2, 4, 8, 16, …', a: '32. Jede Zahl ist das Doppelte der Zahl davor.' },
  { id: 'q24', t: 'frage', e: '🟦', q: 'Wie geht die Reihe weiter? 1, 4, 9, 16, 25, …', a: '36. Das sind die Quadratzahlen: 1·1, 2·2, 3·3, … und 6·6 = 36.' },
  { id: 'q25', t: 'frage', e: '🐚', q: 'Wie geht die Reihe weiter? 1, 1, 2, 3, 5, 8, …', a: '13. Jede Zahl ist die Summe der beiden davor (5 + 8 = 13). Das ist die Fibonacci-Reihe.' },
  { id: 'q26', t: 'frage', e: '🎣', q: 'Zwei Väter und zwei Söhne gehen angeln. Jeder fängt genau einen Fisch, aber insgesamt sind es nur 3 Fische. Wie geht das?', a: 'Es sind nur 3 Personen: Großvater, Vater und Sohn. Der Vater ist beides – Vater und Sohn.' },
  { id: 'q27', t: 'frage', e: '🐑', q: 'Ein Bauer hat 17 Schafe. Alle bis auf 9 laufen weg. Wie viele Schafe sind noch da?', a: '9 Schafe. „Alle bis auf 9“ heißt: 9 bleiben.' },
  { id: 'q28', t: 'frage', e: '🍕', q: 'Eine Pizza ist in 8 gleich große Stücke geschnitten. Du isst 3 Stücke. Welcher Bruchteil der Pizza ist noch übrig?', a: '5/8, denn 8 − 3 = 5 Stücke von 8.' },
  { id: 'q29', t: 'frage', e: '🍬', q: 'Du hast 24 Gummibärchen und gibst ein Drittel davon deiner Freundin. Wie viele bekommt sie?', a: '8 Stück, denn 24 : 3 = 8.' },
  { id: 'q30', t: 'frage', e: '⚖️', q: 'Was ist größer: 1/2 oder 1/3?', a: '1/2. Je mehr Teile, desto kleiner ist jedes einzelne Teil: Ein Drittel ist kleiner als ein Halbes.' },
  { id: 'q31', t: 'frage', e: '✂️', q: 'Wie viel ist die Hälfte von der Hälfte von 80?', a: '20. Die Hälfte von 80 ist 40, die Hälfte davon ist 20.' },
  { id: 'q32', t: 'frage', e: '🥚', q: 'Du kaufst ein Dutzend Eier und noch ein halbes Dutzend dazu. Wie viele Eier sind das?', a: '18 Eier, denn 12 + 6 = 18.' },
  { id: 'q33', t: 'frage', e: '🎂', q: 'Mia ist doppelt so alt wie ihr Bruder Ben. Ben ist 5. Wie alt ist Mia, wenn Ben 10 ist?', a: '15. Mia ist jetzt 10, also immer 5 Jahre älter als Ben. Das Doppelte wäre 20 – aber der Altersunterschied bleibt gleich!' },
  { id: 'q34', t: 'frage', e: '📐', q: 'Ein Rechteck ist 6 m lang und 4 m breit. Wie groß sind Umfang und Fläche?', a: 'Umfang: 20 m (6 + 4 + 6 + 4). Fläche: 24 m² (6 · 4).' },
  { id: 'q35', t: 'frage', e: '🧊', q: 'Wie viele Ecken und wie viele Kanten hat ein Würfel?', a: '8 Ecken und 12 Kanten.' },
  { id: 'q36', t: 'frage', e: '⏱️', q: 'Wie viele Minuten haben 3 Stunden?', a: '180 Minuten, denn 3 · 60 = 180.' },
  { id: 'q37', t: 'frage', e: '🕒', q: 'Es ist 14:45 Uhr. Wie spät ist es in 50 Minuten?', a: '15:35 Uhr. Erst 15 Minuten bis 15:00 Uhr, dann noch 35 Minuten dazu.' },
  { id: 'q38', t: 'frage', e: '🎬', q: 'Ein Film dauert 1 Stunde und 45 Minuten und beginnt um 16:30 Uhr. Wann ist er zu Ende?', a: '18:15 Uhr. 16:30 + 1 Stunde = 17:30, plus 45 Minuten = 18:15.' },
  { id: 'q39', t: 'frage', e: '👕', q: 'Du hast 3 Hosen und 4 T-Shirts. Wie viele verschiedene Outfits kannst du daraus kombinieren?', a: '12 Outfits, denn 3 · 4 = 12.' },
  { id: 'q40', t: 'frage', e: '🍨', q: 'Es gibt 5 Eissorten und 3 verschiedene Soßen. Du nimmst eine Kugel und eine Soße. Wie viele Möglichkeiten gibt es?', a: '15 Möglichkeiten, denn 5 · 3 = 15.' },
  { id: 'q41', t: 'frage', e: '⚖️', q: 'Wie viele Gramm sind 5 Kilogramm?', a: '5000 Gramm, denn 1 kg = 1000 g.' },
  { id: 'q42', t: 'frage', e: '📏', q: 'Wie viele Zentimeter sind 2,5 Meter?', a: '250 cm, denn 1 m = 100 cm.' },
  { id: 'q43', t: 'frage', e: '📅', q: 'Wie viele Tage sind 5 Wochen und 3 Tage?', a: '38 Tage, denn 5 · 7 = 35 und 35 + 3 = 38.' },
  { id: 'q44', t: 'frage', e: '🐞', q: 'Wie viele Beine haben 7 Marienkäfer und 3 Spinnen zusammen?', a: '66 Beine: 7 · 6 = 42 und 3 · 8 = 24. Zusammen 42 + 24 = 66.' },
  { id: 'q45', t: 'frage', e: '🐌', q: 'Eine Schnecke will aus einem 10 m tiefen Brunnen klettern. Tagsüber schafft sie 3 m nach oben, nachts rutscht sie 2 m zurück. Am wievielten Tag ist sie draußen?', a: 'Am 8. Tag! Jeden Tag kommt sie netto 1 m weiter. Nach 7 Tagen und Nächten ist sie bei 7 m, am 8. Tag klettert sie noch 3 m – und ist oben, bevor sie wieder zurückrutschen kann.' },
  { id: 'q46', t: 'frage', e: '🕵️', q: 'Ich bin ein Vielfaches von 6, kleiner als 50 und meine Quersumme ist 12. Wer bin ich?', a: '48, denn 8 · 6 = 48 und 4 + 8 = 12.' },
  { id: 'q47', t: 'frage', e: '🕵️', q: 'Ich bin eine ungerade Zahl zwischen 20 und 30 und lasse mich durch 9 teilen. Wer bin ich?', a: '27, denn 3 · 9 = 27.' },
  { id: 'q48', t: 'frage', e: '🔟', q: 'Welche Primzahlen gibt es zwischen 10 und 20?', a: '11, 13, 17 und 19. Die haben keine anderen Teiler außer 1 und sich selbst.' },
  { id: 'q49', t: 'frage', e: '🧠', q: 'Rechne im Kopf: 99 + 99 + 99. Gibt es einen Trick?', a: '297. Trick: 3 · 100 = 300, dann 3 abziehen.' },
  { id: 'q50', t: 'frage', e: '⚡', q: 'Rechne möglichst schlau: 25 · 4 · 7.', a: '700. Erst 25 · 4 = 100 und dann 100 · 7 = 700.' },
  { id: 'q51', t: 'frage', e: '♻️', q: 'Du gibst 8 Flaschen mit je 25 Cent Pfand zurück. Wie viel Geld bekommst du?', a: '2,00 €, denn 8 · 25 ct = 200 ct.' },
  { id: 'q52', t: 'frage', e: '🥐', q: 'Du kaufst 3 Brötchen zu je 0,45 € und bezahlst mit 2 €. Wie viel Rückgeld bekommst du?', a: '0,65 €. Die Brötchen kosten 3 · 0,45 € = 1,35 €, und 2,00 € − 1,35 € = 0,65 €.' },
  { id: 'q53', t: 'frage', e: '✏️', q: 'Ein Stift kostet 1,20 € und ein Heft 2,30 €. Du zahlst mit einem 5-Euro-Schein. Wie viel Rückgeld bekommst du?', a: '1,50 €, denn 1,20 € + 2,30 € = 3,50 € und 5,00 € − 3,50 € = 1,50 €.' },
  { id: 'q54', t: 'frage', e: '🍕', q: '8 Kinder teilen sich 2 Pizzen, jede mit 8 Stücken. Wie viele Stücke bekommt jedes Kind?', a: '2 Stücke, denn 2 · 8 = 16 Stücke und 16 : 8 = 2.' },
  { id: 'q55', t: 'frage', e: '🚌', q: 'Im Bus sitzen 24 Leute. An der Haltestelle steigen 9 aus und 5 ein. Wie viele Leute sind jetzt im Bus?', a: '20 Leute, denn 24 − 9 + 5 = 20.' },
  { id: 'q56', t: 'frage', e: '😴', q: 'Eine Katze schläft etwa 16 Stunden am Tag. Wie viele Stunden schläft sie in einer Woche?', a: '112 Stunden, denn 7 · 16 = 112.' },
  { id: 'q57', t: 'frage', e: '♟️', q: 'Ein Schachbrett hat 8 mal 8 Felder. Wie viele Felder sind es insgesamt und wie viele davon sind weiß?', a: '64 Felder, davon 32 weiße, denn 8 · 8 = 64 und die Hälfte ist weiß.' },
  { id: 'q58', t: 'frage', e: '🚗', q: 'Ein Auto fährt 80 km pro Stunde. Wie weit kommt es in 2 ½ Stunden?', a: '200 km: 2 Stunden sind 160 km, eine halbe Stunde sind 40 km.' },
  { id: 'q59', t: 'frage', e: '🕰️', q: 'Wie viele Sekunden hat eine Stunde?', a: '3600 Sekunden, denn 60 · 60 = 3600.' },
  { id: 'q60', t: 'frage', e: '🏫', q: 'Dein Schulweg ist 1,2 km lang. Wie viele Kilometer gehst du in einer Schulwoche (5 Tage), wenn du immer hin und zurück läufst?', a: '12 km, denn 1,2 km · 2 · 5 = 12 km.' },
  { id: 'q61', t: 'frage', e: '🎩', q: 'Zaubertrick: Denk dir eine Zahl. Verdopple sie, addiere 10, halbiere das Ergebnis und zieh deine Zahl wieder ab. Was kommt heraus?', a: 'Immer 5! Zum Beispiel mit 7: 7 → 14 → 24 → 12 → 12 − 7 = 5.' },
  { id: 'q62', t: 'frage', e: '➕', q: 'Wie viel ist 1 + 2 + 3 + … + 10? Tipp: Bilde Paare.', a: '55. Die Paare 1+10, 2+9, 3+8, 4+7, 5+6 ergeben je 11. Das sind 5 Paare: 5 · 11 = 55.' },
  { id: 'q63', t: 'frage', e: '🧑‍🎓', q: 'Der berühmte Mathematiker Gauß soll als Kind in Sekunden 1 + 2 + 3 + … + 100 ausgerechnet haben. Kannst du das auch?', a: '5050. Es gibt 50 Paare (1+100, 2+99, …), jedes ergibt 101. Und 50 · 101 = 5050.' },
  { id: 'q64', t: 'frage', e: '🐓', q: 'Im Stall stehen Hühner und Kühe. Zusammen sind es 10 Tiere und 28 Beine. Wie viele Hühner sind es?', a: '6 Hühner und 4 Kühe, denn 6 · 2 + 4 · 4 = 12 + 16 = 28.' },
  { id: 'q65', t: 'frage', e: '👔', q: 'Ein Hemd braucht in der Sonne 1 Stunde zum Trocknen. Wie lange brauchen 5 Hemden, die nebeneinander hängen?', a: 'Auch 1 Stunde. Sie trocknen gleichzeitig.' },
  { id: 'q66', t: 'frage', e: '9️⃣', q: 'Wie viele Zahlen von 1 bis 100 enthalten mindestens eine Ziffer 9?', a: '19 Zahlen: 9, 19, 29, … 89 (das sind 9 Zahlen) und 90 bis 99 (das sind 10 Zahlen).' },
  { id: 'q67', t: 'frage', e: '🎲', q: 'Du wirfst zwei Würfel und zählst die Augen zusammen. Welche Summe kommt am häufigsten vor?', a: 'Die 7. Dafür gibt es 6 Möglichkeiten (1+6, 2+5, 3+4, 4+3, 5+2, 6+1). Bei jeder anderen Summe sind es weniger.' },
  { id: 'q68', t: 'frage', e: '🧊', q: 'Ein Würfel hat 2 cm Kantenlänge. Wie viele kleine Würfel mit 1 cm Kantenlänge passen hinein?', a: '8 Würfel. Unten 2 · 2 = 4 Stück, und das ganze zweimal übereinander.' },
  { id: 'q69', t: 'frage', e: '🚸', q: 'Zehn Kinder stehen in einer Reihe. Mia steht an vierter Stelle von vorne. An welcher Stelle steht sie von hinten?', a: 'An 7. Stelle, denn 10 − 4 + 1 = 7. Hinter ihr stehen 6 Kinder.' },
  { id: 'q70', t: 'frage', e: '🚶', q: 'In einer Schlange stehen vor dir 5 Kinder und hinter dir 3. Wie viele Kinder stehen in der Schlange?', a: '9 Kinder, denn 5 + dich + 3 = 9.' },
  { id: 'q71', t: 'frage', e: '🏡', q: 'Ein gerader Zaun hat 10 Pfosten. Wie viele Zaunstücke sind dazwischen?', a: '9 Zaunstücke. Zwischen 10 Pfosten sind 9 Lücken.' },
  { id: 'q72', t: 'frage', e: '🥂', q: '5 Kinder stoßen mit ihren Gläsern an, jedes mit jedem genau einmal. Wie oft klirrt es?', a: '10-mal: 4 + 3 + 2 + 1 = 10.' },
  { id: 'q73', t: 'frage', e: '🔀', q: 'Du hast die Ziffernkärtchen 1, 2 und 3. Wie viele verschiedene dreistellige Zahlen kannst du damit legen, wenn du jedes Kärtchen genau einmal nimmst?', a: '6 Zahlen: 123, 132, 213, 231, 312 und 321.' },
  { id: 'q74', t: 'frage', e: '🔡', q: 'Wie viele Ziffern musst du schreiben, um alle Zahlen von 1 bis 20 aufzuschreiben?', a: '31 Ziffern: Die Zahlen 1 bis 9 brauchen 9 Ziffern, die Zahlen 10 bis 20 sind 11 Zahlen mit je 2 Ziffern = 22. Zusammen 31.' },
  { id: 'q75', t: 'frage', e: '⏰', q: 'Wie viele Minuten hat eine Dreiviertelstunde?', a: '45 Minuten, denn 60 : 4 = 15 und 3 · 15 = 45.' },
  { id: 'q76', t: 'frage', e: '🟫', q: 'Wie viele Quadratzentimeter hat ein Quadratmeter?', a: '10.000 cm², denn 1 m = 100 cm und 100 · 100 = 10.000.' },

  // Rätsel (neu)
  { id: 'r01', t: 'raetsel', e: '🦷', q: 'Was hat viele Zähne, aber kann nicht beißen?', a: 'Ein Kamm. (Auch eine Säge oder ein Zahnrad passen!)' },
  { id: 'r02', t: 'raetsel', e: '🍾', q: 'Was hat einen Hals, aber keinen Kopf?', a: 'Eine Flasche.' },
  { id: 'r03', t: 'raetsel', e: '🕰️', q: 'Was hat zwei Hände, aber kann nicht klatschen?', a: 'Eine Uhr.' },
  { id: 'r04', t: 'raetsel', e: '🪡', q: 'Was hat ein Auge, aber kann nicht sehen?', a: 'Eine Nadel.' },
  { id: 'r05', t: 'raetsel', e: '📖', q: 'Was hat einen Rücken, aber keine Beine?', a: 'Ein Buch.' },
  { id: 'r06', t: 'raetsel', e: '🧖', q: 'Was wird nasser, je mehr es trocknet?', a: 'Ein Handtuch.' },
  { id: 'r07', t: 'raetsel', e: '🤝', q: 'Was kann man geben und trotzdem behalten?', a: 'Sein Wort.' },
  { id: 'r08', t: 'raetsel', e: '📛', q: 'Was gehört dir, wird aber von anderen viel öfter benutzt als von dir?', a: 'Dein Name.' },
  { id: 'r09', t: 'raetsel', e: '🕳️', q: 'Was wird größer, je mehr man davon wegnimmt?', a: 'Ein Loch.' },
  { id: 'r10', t: 'raetsel', e: '🔤', q: 'Was kommt einmal in der Minute vor, zweimal im Moment, aber nie in tausend Jahren?', a: 'Der Buchstabe M.' },
  { id: 'r11', t: 'raetsel', e: '🔮', q: 'Was ist immer vor dir, aber du kannst es nicht sehen?', a: 'Die Zukunft.' },
  { id: 'r12', t: 'raetsel', e: '🌧️', q: 'Was fällt vom Himmel, ohne sich wehzutun?', a: 'Der Regen (oder der Schnee).' },
  { id: 'r13', t: 'raetsel', e: '🤫', q: 'Was geht kaputt, sobald du seinen Namen sagst?', a: 'Die Stille.' },
  { id: 'r14', t: 'raetsel', e: '💨', q: 'Was ist leichter als eine Feder, aber trotzdem kann es kaum jemand länger als ein paar Minuten halten?', a: 'Der Atem.' },
  { id: 'r15', t: 'raetsel', e: '🌑', q: 'Was folgt dir überallhin, verschwindet aber im Dunkeln?', a: 'Dein Schatten.' },
  { id: 'r16', t: 'raetsel', e: '🗺️', q: 'Ich habe Städte, aber keine Häuser. Ich habe Flüsse, aber kein Wasser. Ich habe Berge, aber keine Steine. Was bin ich?', a: 'Eine Landkarte.' },
  { id: 'r17', t: 'raetsel', e: '🌫️', q: 'Je mehr du davon hast, desto weniger siehst du. Was ist das?', a: 'Dunkelheit (oder dichter Nebel).' },
  { id: 'r18', t: 'raetsel', e: '🧤', q: 'Was hat einen Daumen, aber keine anderen Finger?', a: 'Ein Fäustling.' },
  { id: 'r19', t: 'raetsel', e: '🎂', q: 'Was wird jedes Jahr größer, aber nie kleiner?', a: 'Dein Alter.' },
  { id: 'r20', t: 'raetsel', e: '🍄', q: 'Was hat einen Hut, aber keinen Kopf?', a: 'Ein Pilz.' },
  { id: 'r21', t: 'raetsel', e: '✍️', q: 'Welches Wort schreibt man immer falsch?', a: 'Das Wort „falsch“.' },
  { id: 'r22', t: 'raetsel', e: '👣', q: 'Je mehr du davon machst, desto mehr bleibt hinter dir zurück. Was ist das?', a: 'Schritte (oder Fußspuren).' },
  { id: 'r23', t: 'raetsel', e: '🃏', q: 'Was hat 13 Herzen, aber keinen einzigen Herzschlag?', a: 'Ein Kartenspiel mit 52 Karten: Von jeder der vier Farben gibt es 13 Karten, also 13 Herzkarten.' },
  { id: 'r24', t: 'raetsel', e: '👨‍👧‍👦', q: 'Ein Mann hat 4 Töchter. Jede Tochter hat einen Bruder. Wie viele Kinder hat der Mann?', a: '5 Kinder: 4 Töchter und 1 Sohn. Der Sohn ist der Bruder von allen.' },
  { id: 'r25', t: 'raetsel', e: '🐘', q: 'Wie bekommt man einen Elefanten in den Kühlschrank?', a: 'Tür auf, Elefant rein, Tür zu.' },
  { id: 'r26', t: 'raetsel', e: '🌙', q: 'Es ist Mitternacht und es regnet. Kann in 72 Stunden die Sonne scheinen?', a: 'Nein! In 72 Stunden ist wieder Mitternacht – da ist es dunkel.' },
  { id: 'r27', t: 'raetsel', e: '🔑', q: 'Was hat einen Bart, ist aber kein Mann?', a: 'Ein Schlüssel. Der Teil mit den Zacken heißt Schlüsselbart.' },
  { id: 'r28', t: 'raetsel', e: '👟', q: 'Was hat eine Zunge, aber kann nicht sprechen?', a: 'Ein Schuh.' },
  { id: 'r29', t: 'raetsel', e: '👃', q: 'Welche Brücke kann man nicht überqueren?', a: 'Die Nasenbrücke (oder die Zahnbrücke).' },
  { id: 'r30', t: 'raetsel', e: '🚂', q: 'Eine Elektrolok fährt nach Norden, der Wind kommt aus dem Westen. In welche Richtung weht der Rauch?', a: 'Gar nicht – eine Elektrolok hat keinen Rauch!' },
  { id: 'r31', t: 'raetsel', e: '🐐', q: 'Ein Bauer will einen Wolf, eine Ziege und einen Kohlkopf über einen Fluss bringen. Sein Boot trägt nur ihn und eines davon. Allein gelassen frisst der Wolf die Ziege und die Ziege den Kohl. Wie klappt es?', a: 'Zuerst die Ziege rüber. Zurück, den Wolf holen und rüberbringen, dabei die Ziege wieder mit zurücknehmen. Dann den Kohl rüber, wieder zurück und zum Schluss die Ziege holen.' },
  { id: 'r32', t: 'raetsel', e: '🪣', q: 'Du hast einen 3-Liter-Eimer und einen 5-Liter-Eimer, beide ohne Markierung, und genug Wasser. Wie misst du genau 4 Liter ab?', a: '5-Liter-Eimer füllen, daraus 3 Liter in den kleinen Eimer gießen (2 bleiben übrig). Kleinen Eimer leeren, die 2 Liter hineingießen. Großen Eimer wieder füllen und den kleinen auffüllen: 1 Liter geht hinein, also bleiben 4 Liter im großen Eimer.' },
  { id: 'r33', t: 'raetsel', e: '⚖️', q: 'Du hast 9 Münzen, eine ist schwerer als die anderen. Du hast eine Balkenwaage. Mit wie wenigen Wägungen findest du die schwere Münze?', a: 'Mit nur 2 Wägungen: Teile die Münzen in 3 Dreierhaufen. Wiege zwei Haufen gegeneinander, so findest du den schwersten Haufen. Aus ihm wiegst du zwei Münzen gegeneinander und weißt es.' },
  { id: 'r34', t: 'raetsel', e: '💡', q: 'Draußen vor dem Zimmer sind 3 Schalter, im Zimmer brennt nur eine Glühbirne, die zu einem der Schalter gehört. Du darfst nur einmal ins Zimmer gehen. Wie findest du den richtigen Schalter?', a: 'Schalter 1 einige Minuten anlassen, dann aus. Schalter 2 an und rein ins Zimmer. Leuchtet die Birne: Schalter 2. Ist sie aus und warm: Schalter 1. Aus und kalt: Schalter 3.' },
  { id: 'r35', t: 'raetsel', e: '🪙', q: 'Ich habe zwei Münzen, zusammen sind sie 15 Cent wert. Eine davon ist keine 5-Cent-Münze. Welche Münzen sind es?', a: 'Eine 10-Cent-Münze und eine 5-Cent-Münze. Eine von beiden (die 10-Cent-Münze) ist keine 5-Cent-Münze – die andere aber schon!' },
  { id: 'r36', t: 'raetsel', e: '🚌', q: 'Du fährst einen Bus. An der ersten Haltestelle steigen 3 Leute ein, an der zweiten steigen 2 aus und 4 ein. Wie alt ist der Busfahrer?', a: 'So alt wie du – denn du bist der Busfahrer!' },
  { id: 'r37', t: 'raetsel', e: '🏠', q: 'Ein Mann baut ein Haus mit vier Seiten, die alle nach Süden zeigen. Ein Bär spaziert vorbei. Welche Farbe hat er?', a: 'Weiß. Ein Haus mit vier Südseiten kann nur am Nordpol stehen – da leben Eisbären.' },
  { id: 'r38', t: 'raetsel', e: '🤧', q: 'Was kann man fangen, aber nicht werfen?', a: 'Eine Erkältung.' },
  { id: 'r39', t: 'raetsel', e: '😊', q: 'Was wird mehr, wenn du es mit anderen teilst?', a: 'Freude (oder Wissen).' },
  { id: 'r40', t: 'raetsel', e: '🛣️', q: 'Was geht durch Städte und Felder, ohne sich zu bewegen?', a: 'Eine Straße.' },
  { id: 'r41', t: 'raetsel', e: '⛰️', q: 'Was hat Wurzeln, die niemand sieht, ist höher als jeder Baum, wächst und wächst und steigt doch nie?', a: 'Ein Berg.' },
  { id: 'r42', t: 'raetsel', e: '🚛', q: 'Was hat vier Räder und Fliegen?', a: 'Ein Müllwagen.' },
  { id: 'r43', t: 'raetsel', e: '⭕', q: 'Ich habe weder Anfang noch Ende. Was bin ich?', a: 'Ein Kreis (oder ein Ring).' },

  // Musik (neu)
  { id: 'm01', t: 'musik', e: '🎹', q: 'Mozart schrieb schon mit etwa fünf Jahren seine ersten eigenen Musikstücke. Mit sechs ging er als Wunderkind auf Konzertreise quer durch Europa.' },
  { id: 'm02', t: 'musik', e: '🦻', q: 'Ludwig van Beethoven wurde im Lauf seines Lebens fast völlig taub. Trotzdem komponierte er weiter – sogar seine berühmte 9. Sinfonie.' },
  { id: 'm03', t: 'musik', e: '🎹', q: 'Ein Klavier hat 88 Tasten. Wie viele davon sind weiß, wenn 36 schwarz sind?', a: '52 weiße Tasten, denn 88 − 36 = 52.' },
  { id: 'm04', t: 'musik', e: '🎻', q: 'Wie viele Saiten hat eine normale Geige?', a: '4 Saiten. Sie sind auf G, D, A und E gestimmt.' },
  { id: 'm05', t: 'musik', e: '🎸', q: 'Wie viele Saiten hat eine normale Gitarre und wie viele ein E-Bass?', a: 'Die Gitarre hat 6 Saiten, der E-Bass meistens 4.' },
  { id: 'm06', t: 'musik', e: '⛪', q: 'Die Orgel wird „Königin der Instrumente“ genannt. Große Kirchenorgeln haben mehrere tausend Pfeifen – manche sogar über 10.000.' },
  { id: 'm07', t: 'musik', e: '🎶', q: 'Welche Flöte ist die kleinste im Orchester und klingt am höchsten?', a: 'Die Piccoloflöte. Sie ist nur etwa halb so lang wie eine Querflöte.' },
  { id: 'm08', t: 'musik', e: '🎼', q: 'Do, Re, Mi, Fa, Sol, La, Si: Die Namen der Töne stammen aus den Anfangssilben der Zeilen eines alten lateinischen Liedes.' },
  { id: 'm09', t: 'musik', e: '💨', q: 'Schall braucht in der Luft etwa 1 Sekunde für 340 Meter. Im Wasser ist er mit rund 1500 Metern pro Sekunde viel schneller.' },
  { id: 'm10', t: 'musik', e: '〰️', q: 'Was entscheidet darüber, ob ein Ton hoch oder tief klingt?', a: 'Wie schnell etwas schwingt. Schnelle Schwingungen klingen hoch, langsame klingen tief.' },
  { id: 'm11', t: 'musik', e: '🎶', q: 'Das A, nach dem sich ein Orchester stimmt, schwingt genau 440-mal pro Sekunde. Es heißt Kammerton.' },
  { id: 'm12', t: 'musik', e: '🎷', q: 'Das Saxofon ist nach seinem Erfinder Adolphe Sax benannt. Es ist aus Metall – gehört aber zu den Holzblasinstrumenten, weil es ein Rohrblatt aus Holz hat.' },
  { id: 'm13', t: 'musik', e: '🎶', q: 'Ist die Querflöte ein Holz- oder ein Blechblasinstrument?', a: 'Ein Holzblasinstrument – obwohl sie heute aus Metall ist. Früher waren Flöten aus Holz, der Name ist geblieben.' },
  { id: 'm14', t: 'musik', e: '🗣️', q: 'Wenn du singst, schwingen die Stimmbänder in deinem Kehlkopf. Das sind zwei kleine Hautfalten.' },
  { id: 'm15', t: 'musik', e: '👨‍👧‍👦', q: 'Johann Sebastian Bach hatte 20 Kinder. Mehrere von ihnen wurden auch berühmte Musiker.' },
  { id: 'm16', t: 'musik', e: '🔴', q: 'Der Komponist Antonio Vivaldi hatte rote Haare. Darum nannte man ihn in Italien „den roten Priester“.' },
  { id: 'm17', t: 'musik', e: '🎻', q: 'Wer hat „Die vier Jahreszeiten“ komponiert?', a: 'Antonio Vivaldi. Es sind vier Violinkonzerte, eins für jede Jahreszeit.' },
  { id: 'm18', t: 'musik', e: '✨', q: 'Im „Tanz der Zuckerfee“ aus dem Nussknacker-Ballett von Tschaikowsky klingt eine Celesta. Sie sieht aus wie ein kleines Klavier, klingt aber wie funkelnde Glöckchen.' },
  { id: 'm19', t: 'musik', e: '🎹', q: 'Das Klavier heißt eigentlich „Pianoforte“. Was bedeutet das?', a: '„Leise-laut“. Anders als beim Cembalo kann man beim Klavier leise und laut spielen, je nachdem wie fest man die Taste drückt.' },
  { id: 'm20', t: 'musik', e: '🔊', q: 'Was bedeuten „forte“ und „piano“ in der Musik?', a: 'Forte heißt laut, piano heißt leise.' },
  { id: 'm21', t: 'musik', e: '🎹', q: 'Wie viele verschiedene Töne hat eine Oktave auf dem Klavier (weiße und schwarze Tasten zusammen)?', a: '12 Töne: 7 weiße und 5 schwarze Tasten.' },
  { id: 'm22', t: 'musik', e: '💃', q: 'Wie viele Schläge hat ein Takt in einem Walzer (3/4-Takt)?', a: '3 Schläge: eins-zwei-drei.' },
  { id: 'm23', t: 'musik', e: '🎼', q: 'Eine halbe Note dauert 2 Schläge, eine Viertelnote 1 Schlag. Wie viele Achtelnoten dauern so lange wie eine halbe Note?', a: '4 Achtelnoten. Zwei Achtel sind ein Schlag, also vier Achtel sind 2 Schläge.' },
  { id: 'm24', t: 'musik', e: '🎵', q: 'In einem 4/4-Takt steht schon eine halbe Note und eine Viertelnote. Welche Note fehlt noch, damit der Takt voll ist?', a: 'Eine Viertelnote: 2 + 1 + 1 = 4 Schläge.' },
  { id: 'm25', t: 'musik', e: '🪘', q: 'Das Didgeridoo ist ein langes Blasinstrument der Aborigines in Australien. Mit einer besonderen Atemtechnik (Zirkularatmung) kann man dabei ununterbrochen spielen, auch beim Einatmen.' },
  { id: 'm26', t: 'musik', e: '🏔️', q: 'Ein Alphorn ist oft mehr als 3 Meter lang. Sein Klang trägt in den Bergen weit durch die Täler.' },
  { id: 'm27', t: 'musik', e: '🌺', q: 'Die Ukulele kommt aus Hawaii. Ihr Name wird oft mit „hüpfender Floh“ übersetzt – weil die Finger so flink darüber springen.' },
  { id: 'm28', t: 'musik', e: '👐', q: 'Welches Instrument spielt man, ohne es zu berühren?', a: 'Das Theremin. Man bewegt nur die Hände in der Nähe von zwei Antennen, und das verändert Tonhöhe und Lautstärke.' },
  { id: 'm29', t: 'musik', e: '🎻', q: 'Geigen von Antonio Stradivari sind über 300 Jahre alt und werden heute für Millionen Euro verkauft.' },
  { id: 'm30', t: 'musik', e: '🐋', q: 'Buckelwale singen lange Lieder, die sich über die Jahre verändern. Die Wale lernen neue Melodien voneinander.' },
  { id: 'm31', t: 'musik', e: '🦜', q: 'Der Leierschwanz in Australien kann Geräusche nachmachen, die er gehört hat: zum Beispiel Handyklingeln oder Kamera-Klicks.' },
  { id: 'm32', t: 'musik', e: '📀', q: 'Auf einer Schallplatte ist der Ton als winzige Wellen-Rille eingeritzt. Eine Nadel folgt dieser Rille, wird dadurch zum Schwingen gebracht und so entsteht die Musik.' },
  { id: 'm33', t: 'musik', e: '🎹', q: 'Ein Klavier hat rund 230 Saiten. Beim Spielen schlagen kleine Hämmerchen darauf.' },
  { id: 'm34', t: 'musik', e: '💃', q: 'Das Wort „Orchester“ kommt aus dem Griechischen und bedeutete ursprünglich „Tanzplatz“.' },
  { id: 'm35', t: 'musik', e: '🧠', q: 'Wenn du ein Instrument spielst, arbeiten viele Teile deines Gehirns gleichzeitig: Hören, Sehen, Bewegen und Fühlen.' },
  { id: 'm36', t: 'musik', e: '🎩', q: 'Welcher Komponist reiste schon als Kind durch Europa und galt als Wunderkind?', a: 'Wolfgang Amadeus Mozart (1756–1791).' },
  { id: 'm37', t: 'musik', e: '🎤', q: 'Wie nennt man eine Gruppe aus vier Musikern?', a: 'Ein Quartett. Zu zweit ist es ein Duo, zu dritt ein Trio, zu fünft ein Quintett.' },
  { id: 'm38', t: 'musik', e: '🎼', q: 'Was ist eine Oktave?', a: 'Der Abstand von einem Ton bis zum nächsten gleichnamigen Ton, zum Beispiel von einem C zum nächsten C. Der obere Ton schwingt genau doppelt so schnell.' },
  { id: 'm39', t: 'musik', e: '🥁', q: 'Warum klingt eine große Trommel tiefer als eine kleine?', a: 'Das große Trommelfell schwingt langsamer. Langsame Schwingungen klingen tief.' },
  { id: 'm40', t: 'musik', e: '🍾', q: 'Du pustest über den Rand einer Flasche, bis es tutet. Wird der Ton höher oder tiefer, wenn du Wasser einfüllst?', a: 'Höher. Die Luftsäule in der Flasche wird kürzer, und kürzere Luftsäulen schwingen schneller.' },
  { id: 'm41', t: 'musik', e: '🔤', q: 'Die weißen Klaviertasten heißen auf Deutsch C, D, E, F, G, A und …?', a: 'H. (In anderen Ländern heißt der Ton „B“.)' },
  { id: 'm42', t: 'musik', e: '📏', q: 'Wie viele Linien hat ein Notensystem?', a: '5 Linien.' },
  { id: 'm43', t: 'musik', e: '🗝️', q: 'Welcher Schlüssel öffnet keine Tür, steht aber am Anfang jeder Notenzeile?', a: 'Der Notenschlüssel. Er zeigt, welche Töne auf welchen Linien stehen.' },
  { id: 'm44', t: 'musik', e: '🎹', q: 'Welches Instrument hat Tasten und Saiten – wird aber auch zu den Schlaginstrumenten gezählt?', a: 'Das Klavier. Kleine Hämmerchen schlagen auf die Saiten.' },
  { id: 'm45', t: 'musik', e: '🎤', q: 'Welche vier Stimmlagen gibt es in einem gemischten Chor?', a: 'Sopran, Alt, Tenor und Bass.' },
  { id: 'm46', t: 'musik', e: '🎧', q: 'Was ist ein Ohrwurm?', a: 'Ein Lied, das dir nicht mehr aus dem Kopf geht. (Es ist aber auch ein richtiges Tier, ein Insekt!)' },
  { id: 'm47', t: 'musik', e: '🎻', q: 'Welches Streichinstrument spielt man im Sitzen und stützt es mit einem Stachel am Boden ab?', a: 'Das Cello.' },
  { id: 'm48', t: 'musik', e: '🎼', q: 'Welche berühmte Sinfonie beginnt mit vier Tönen: „Ta-ta-ta-taaa“?', a: 'Beethovens 5. Sinfonie.' },
  { id: 'm49', t: 'musik', e: '🎵', q: 'Wie nennt man Musik ohne Gesang?', a: 'Instrumentalmusik.' },
  { id: 'm50', t: 'musik', e: '🔔', q: 'Wie viele Töne hat ein Dreiklang?', a: '3 Töne, daher der Name.' },
  { id: 'm51', t: 'musik', e: '🥁', q: 'Was passiert mit dem Ton einer Gitarrensaite, wenn du sie kürzer greifst?', a: 'Er wird höher, denn eine kürzere Saite schwingt schneller.' },

  // Denk mal (neu)
  { id: 'o01', t: 'offen', e: '🎻', q: 'Wenn du ein ganz neues Instrument erfinden dürftest: Wie sieht es aus und wie klingt es?' },
  { id: 'o02', t: 'offen', e: '🎵', q: 'Welches Lied würdest du als Titelmusik für deinen eigenen Film aussuchen – und warum?' },
  { id: 'o03', t: 'offen', e: '🌍', q: 'Stell dir vor, du darfst ein neues Land gründen. Wie heißt es, wie sieht die Flagge aus und welche Regel gibt es als Erstes?' },
  { id: 'o04', t: 'offen', e: '🦸', q: 'Welche Superkraft wäre im Alltag am nützlichsten – und welche wäre am lustigsten?' },
  { id: 'o05', t: 'offen', e: '🌌', q: 'Wenn du auf einen anderen Planeten reisen könntest: Wie müsste er sein, damit du dort leben möchtest?' },
  { id: 'o06', t: 'offen', e: '🤖', q: 'Du bekommst einen Roboter geschenkt, der genau eine Sache für dich erledigt. Was soll er tun?' },
  { id: 'o07', t: 'offen', e: '🐾', q: 'Wenn du für einen Tag ein Tier sein dürftest: Welches wäre es und was würdest du als Erstes tun?' },
  { id: 'o08', t: 'offen', e: '🕰️', q: 'Wenn du eine Zeitmaschine hättest: In welche Zeit würdest du reisen und was wolltest du dort sehen?' },
  { id: 'o09', t: 'offen', e: '🧩', q: 'Welche Frage würdest du gern einmal einem klugen Forscher stellen?' },
  { id: 'o10', t: 'offen', e: '🏠', q: 'Stell dir dein Traumhaus vor. Welches Zimmer gibt es dort, das es sonst nirgendwo gibt?' },
  { id: 'o11', t: 'offen', e: '🎨', q: 'Welche Farbe klingt für dich wie Musik – und welche Musik würde zu ihr passen?' },
  { id: 'o12', t: 'offen', e: '🔮', q: 'Was glaubst du: Wie sieht die Schule in 100 Jahren aus?' },
  { id: 'o13', t: 'offen', e: '🍽️', q: 'Du darfst ein neues Gericht erfinden. Was kommt hinein und wie heißt es?' },
  { id: 'o14', t: 'offen', e: '🚗', q: 'Wenn es Fahrzeuge gäbe, die alles können: Wie sähe dein Traumfahrzeug aus und was könnte es?' },
  { id: 'o15', t: 'offen', e: '🌳', q: 'Du findest einen Zauberbaum, an dem alles wächst, was du dir wünschst. Was wächst als Erstes daran?' },
  { id: 'o16', t: 'offen', e: '🤔', q: 'Was ist etwas, das du heute gelernt hast und gestern noch nicht wusstest?' },
  { id: 'o17', t: 'offen', e: '🎲', q: 'Erfinde ein neues Brettspiel: Wie lautet der Name und was ist das Ziel?' },
  { id: 'o18', t: 'offen', e: '🌈', q: 'Wenn du einen Tag lang die Farben der Welt ändern könntest: Was würdest du umfärben?' },
  { id: 'o19', t: 'offen', e: '🧠', q: 'Wenn du eine Sache sofort perfekt können würdest, was wäre das? Und warum gerade das?' },
  { id: 'o20', t: 'offen', e: '🌙', q: 'Was glaubst du, träumen Tiere? Und wenn ja, wovon?' },
  { id: 'o21', t: 'offen', e: '🐙', q: 'Wenn Kraken drei Herzen haben: Wie viele Herzen hättest du gern – und wofür bräuchtest du sie?' },
  { id: 'o22', t: 'offen', e: '📚', q: 'Wenn du eine Figur aus einem Buch treffen könntest: Wer wäre es und was würdest du fragen?' },
  { id: 'o23', t: 'offen', e: '🎶', q: 'Welcher Ton oder welches Geräusch macht dich besonders glücklich? Und welches nervt dich am meisten?' },
  { id: 'o24', t: 'offen', e: '🚀', q: 'Stell dir vor, du bist die erste Person auf dem Mars. Was sind deine ersten Worte?' },
  { id: 'o25', t: 'offen', e: '🏝️', q: 'Du bist auf einer einsamen Insel. Du darfst drei Dinge mitnehmen. Welche?' },
  { id: 'o26', t: 'offen', e: '🕵️', q: 'Du bist Detektivin oder Detektiv: Welches Rätsel in deiner Umgebung würdest du gern lösen?' },
  { id: 'o27', t: 'offen', e: '🧸', q: 'Wenn deine Kuscheltiere nachts lebendig würden: Was würden sie wohl tun?' },
  { id: 'o28', t: 'offen', e: '🌊', q: 'Stell dir vor, du lebst für einen Tag unter Wasser. Wie wäre dein Tag?' },
  { id: 'o29', t: 'offen', e: '🔢', q: 'Wenn du eine Zahl zu deiner Lieblingszahl machen müsstest: Welche wäre es und warum?' },
  { id: 'o30', t: 'offen', e: '📖', q: 'Schreib im Kopf den ersten Satz für ein Buch, das du gern schreiben würdest.' },
  { id: 'o31', t: 'offen', e: '🧪', q: 'Welche Erfindung fehlt der Welt noch? Wie würde sie funktionieren?' },
  { id: 'o32', t: 'offen', e: '🎭', q: 'Wenn du einen Tag lang jemand anderes sein dürftest: Wer wärst du und was würdest du machen?' },
  { id: 'o33', t: 'offen', e: '🏔️', q: 'Wo auf der Erde möchtest du unbedingt einmal sein? Was würdest du dort zuerst machen?' },
  { id: 'o34', t: 'offen', e: '🥁', q: 'Welcher Rhythmus passt zu deinem Herzschlag, wenn du aufgeregt bist? Und welcher, wenn du ganz ruhig bist?' },
  { id: 'o35', t: 'offen', e: '🧙', q: 'Wenn du einen Zauberspruch erfinden dürftest: Wie lautet er und was bewirkt er?' },
  { id: 'o36', t: 'offen', e: '⭐', q: 'Wenn du einen Stern am Himmel nach dir benennen dürftest: Wie würde er heißen?' },
  { id: 'o37', t: 'offen', e: '💬', q: 'Wenn Tiere sprechen könnten: Mit welchem Tier würdest du dich am liebsten unterhalten und was würdest du fragen?' },
  { id: 'o38', t: 'offen', e: '🌱', q: 'Was würdest du pflanzen, wenn du einen riesigen Garten hättest – nur für dich?' },
  { id: 'o39', t: 'offen', e: '🎁', q: 'Was wäre das schönste Geschenk, das du jemandem machen könntest, ohne Geld auszugeben?' },
  { id: 'o40', t: 'offen', e: '🔇', q: 'Was würdest du tun, wenn für einen Tag alle Geräusche der Welt verschwinden würden?' },
  { id: 'o41', t: 'offen', e: '🏫', q: 'Wenn du einen neuen Stundenplan erfinden dürftest: Welches Fach wäre das Allererste, das es unbedingt geben müsste?' },
  { id: 'o42', t: 'offen', e: '🪐', q: 'Wenn ein Außerirdischer bei dir landet: Was würdest du ihm von der Erde als Erstes zeigen?' },
  { id: 'o43', t: 'offen', e: '🎬', q: 'Welcher Film oder welche Serie sollte unbedingt eine Fortsetzung bekommen? Wie würde sie weitergehen?' },
  { id: 'o44', t: 'offen', e: '🧗', q: 'Was wäre etwas, das du dich im Moment noch nicht traust, aber gern einmal ausprobieren würdest?' },
  { id: 'o45', t: 'offen', e: '🤹', q: 'Welchen Zirkus-Trick möchtest du gern können – und wie würdest du ihn üben?' },
  { id: 'o46', t: 'offen', e: '🕊️', q: 'Wenn du allen Menschen auf der Welt gleichzeitig etwas sagen könntest: Was wäre das?' },
  { id: 'o47', t: 'offen', e: '⏳', q: 'Wenn du einen Tag in deinem Leben noch einmal erleben dürftest: Welcher wäre es?' },
  { id: 'o48', t: 'offen', e: '🎼', q: 'Wenn dein Tag eine Melodie wäre: Wäre sie schnell oder langsam, laut oder leise?' }
];
