// Story-Episoden: Die Zahleninsel und die verschwundenen Töne (need = fertige Gruppen bis zur Freischaltung; Name 'Fino' wird beim Anzeigen durch FN() ersetzt)
const STORY_EPS = [

  // ───────────────────────── 01 ─────────────────────────
  { id:'e01', title:'Der verschwundene Ton', icon:'🏝️', need:0,
    summary:'Die Zahlenglocke läutet nur noch sechs Töne – das C ist spurlos verschwunden!',
    scenes:[
      { bg:'strand', who:'fino', mood:'happy', say:'Willkommen auf der Zahleninsel, {name}! Hier rauscht jede Welle im Takt und selbst die Muscheln können rechnen. Ich bin Fino, dein Fremdenführer mit Fuchsnase!' },
      { bg:'strand', who:'narrator', say:'Jeden Morgen läutet die große Zahlenglocke sieben Töne über die ganze Insel: C, D, E, F, G, A, H. Heute Morgen klingt sie nur … sechs.' },
      { bg:'strand', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Krakeel und Kokosnuss! Das C fehlt! Ich bin ein Papagei, ich höre sowas sofort. Mein Schnabel hängt ganz schief vor Schreck!' },
      { bg:'strand', who:'fino', mood:'think', say:'Ein Ton kann sich doch nicht einfach in Luft auflösen. Schau mal, hier liegen Muscheln in einem seltsamen Muster!' },
      { bg:'strand', who:'fino', mood:'think', say:'Paul sagt, das Muster ist ein Schloss. Wir müssen nur die Muscheln zählen, dann springt es auf.',
        puzzle:{ q:'Die Muscheln liegen in 4 Reihen zu je 6 Stück. Wie viele Muscheln sind das?', opts:['18','24','28'], c:1, ok:'Klick! Das Muschelkästchen springt auf.', no:'Nichts rührt sich. Zähl noch einmal: 4 Reihen, in jeder 6 Muscheln.', hint:'Rechne 4 · 6 oder zähle in Sechserschritten.' } },
      { bg:'strand', who:'narrator', say:'Im Kästchen liegen eine winzige graue Feder, weich wie Nebel, und ein Zettel: „Ich leihe mir nur ein bisschen Klang. Ich bringe ihn bald zurück. – P.“' },
      { bg:'strand', who:'npc', npc:'🦜', name:'Papagei Paul', say:'P?! Etwa Papagei?! Eine Frechheit! Ich klaue höchstens Sonnenblumenkerne. Folgt dem grauen Flaum, er führt zur Echohöhle!' },
      { bg:'strand', who:'du', mood:'think', say:'Wer auch immer P. ist: Höflich ist die Person auf jeden Fall.' },
      { bg:'hoehle', who:'narrator', say:'In der Echohöhle schallt alles zurück. Jeder Schritt. Jeder Atemzug. Manchmal sogar ein Gedanke.' },
      { bg:'hoehle', who:'fino', mood:'happy', say:'Der Weg teilt sich. Welchen nehmen wir?',
        choice:{ opts:['Links, am Tropfstein-Xylophon vorbei','Rechts, am Wasserfall entlang'],
                 then:['Plink-plonk! Die Tropfsteine klingen wie ein Xylophon. Fino summt mit und bleibt fast stehen.','Der Wasserfall rauscht im Takt. Fino tanzt ein paar Schritte, bis ihm das Fell nass wird.'] } },
      { bg:'hoehle', who:'fino', mood:'think', say:'Eine Felswand versperrt den Weg. Das Echo flüstert Zahlen: „Drei … sechs … neun … zwölf …“ Die nächste Zahl öffnet die Wand.',
        puzzle:{ q:'Welche Zahl kommt als Nächstes? 3, 6, 9, 12, …', opts:['14','16','15'], c:2, ok:'Das Echo jubelt „fünfzehn, fünfzehn, fünfzehn“ – der Fels gleitet zur Seite!', no:'Das Echo murmelt nur „hm, hm, hm“. Schau dir die Abstände zwischen den Zahlen an.', hint:'Um wie viel wird es von Zahl zu Zahl mehr?' } },
      { bg:'hoehle', who:'narrator', say:'Dahinter liegt ein winziges Zimmer aus Nebel, mit einem Kissen, in dem noch eine Delle ist. Aber niemand ist da.' },
      { bg:'hoehle', who:'fino', mood:'think', say:'Jemand hat hier gewartet. Wir sind nicht allein auf dieser Insel, {name}. Und ich will unbedingt wissen, wer P. ist!' }
    ] },

  // ───────────────────────── 02 ─────────────────────────
  { id:'e02', title:'Tick-9 verliert den Takt', icon:'🤖', need:1,
    summary:'In Taktstadt geht alles schief – nicht nur das D ist weg, auch der Taktroboter stolpert.',
    scenes:[
      { bg:'stadt', who:'fino', mood:'cheer', say:'Das ist Taktstadt! Hier sind sogar die Ampeln musikalisch: grün, gelb, rot, Pause!' },
      { bg:'stadt', who:'narrator', say:'Heute klatschen die Leute schief, die Uhren gehen nach und der Straßenmusikant pfeift falsch. Über Nacht ist auch das D verschwunden.' },
      { bg:'stadt', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep. Ich bin Tick-9, der Taktroboter. Mein Herz ist ein Metronom. Es macht tick … tack … toick? Das ist nicht gut.' },
      { bg:'stadt', who:'du', mood:'cheer', say:'Wir bringen dich wieder in den Takt! Wo fangen wir an?' },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'In meiner Werkstatt! Die Zahnradkiste hat ein Zahlenschloss. Ohne die richtige Zahl piept sie bis morgen.' },
      { bg:'labor', who:'fino', mood:'think', say:'Tick-9 braucht 8 Zahnräder, und jedes wird mit 6 Schrauben befestigt. Das Schloss will die Gesamtzahl wissen.',
        puzzle:{ q:'8 Zahnräder mit je 6 Schrauben – wie viele Schrauben sind das?', opts:['42','54','48'], c:2, ok:'Klick-klack! 48 Schrauben – die Kiste springt auf.', no:'Piep-piep! Falsche Zahl. Zähl ruhig in Sechserschritten: 6, 12, 18 …', hint:'8 · 6 – die 6er-Reihe!' } },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep! Seltsam: Um das größte Zahnrad hing ein grauer, flauschiger Faden. Er riecht nach Salz und Seetang.' },
      { bg:'labor', who:'fino', mood:'think', say:'Jetzt stellen wir seinen Takt ein. Ein Takt hat 4 Schläge, eine halbe Note dauert 2 Schläge und liegt schon im Takt.',
        puzzle:{ q:'Ein Takt hat 4 Schläge. Eine halbe Note (2 Schläge) ist schon da. Was passt noch hinein?', opts:['zwei Viertelnoten','eine Viertelnote','vier Viertelnoten'], c:0, ok:'Tick! Tack! Tick! Tack! Genau 4 Schläge – der Takt sitzt!', no:'Das Metronom stolpert. Zähl nach: 2 Schläge sind schon da, 4 sollen es werden.', hint:'Eine Viertelnote dauert 1 Schlag.' } },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Zum Dank wünsche ich mir einen neuen Anstrich. Welche Farbe soll mein Gehäuse bekommen?',
        choice:{ opts:['Himmelblau','Grasgrün'],
                 then:['Himmelblau! Tick-9 spiegelt sich in einer Pfütze und piept vor Glück: „Wie ein Stück Meer!“','Grasgrün! Tick-9 sieht jetzt aus wie ein sehr ordentlicher Frosch und ist wahnsinnig stolz.'] } },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep! Mein Herz tickt wieder. Und der Faden riecht nach Meer. Dort steht nur ein Gebäude, das nachts blinkt: der Leuchtturm!' },
      { bg:'labor', who:'fino', mood:'cheer', say:'Auf zum Leuchtturm! Tick-9, danke für den Hinweis. Wir sind dem Dieb mit den Samtpfoten dicht auf den Fersen.' },
      { bg:'stadt', who:'narrator', say:'Hinter den beiden tickt Taktstadt wieder im Takt. Nur ein Platz in der großen Melodie bleibt leer: das D.' }
    ] },

  // ───────────────────────── 03 ─────────────────────────
  { id:'e03', title:'Das Licht im Leuchtturm', icon:'🗼', need:2,
    summary:'Auf den 120 Stufen des Leuchtturms wartet ein Logbuch – und ein Tintenfisch mit Notenschlüssel.',
    scenes:[
      { bg:'meer', who:'narrator', say:'Das Meer glitzert wie ein Sack voller Silbermünzen. Am Ende der Mole ragt ein rot-weiß gestreifter Leuchtturm in den Himmel.' },
      { bg:'meer', who:'fino', mood:'cheer', say:'Sein Licht blinkt kurz, kurz, lang. Kurz, kurz, lang. Fast wie ein Lied ohne Töne!' },
      { bg:'meer', who:'npc', npc:'🧓', name:'Lotte', say:'Ahoi! Ich bin Lotte, Leuchtturmwärterin seit vierzig Jahren. Heute Nacht ist mein Licht zum ersten Mal aus dem Takt gekommen. Und das E ist weg!' },
      { bg:'meer', who:'npc', npc:'🧓', name:'Lotte', say:'Jede Nacht kam eine kleine graue Wolke vorbei und fragte höflich, ob sie etwas Klang mitnehmen darf. Ich dachte, sie meint den Buchstaben!' },
      { bg:'meer', who:'fino', mood:'think', say:'Eine Wolke, die höflich klaut? Das klingt nach einem Rätsel mit Samtpfoten.' },
      { bg:'meer', who:'du', mood:'think', say:'Dann sehen wir im Logbuch nach. Wo liegt das?' },
      { bg:'meer', who:'npc', npc:'🧓', name:'Lotte', say:'Ganz oben! Der Turm hat 120 Stufen. Ein Viertel davon schaffe ich jeden Morgen vor dem Frühstück. Wie viele Stufen sind das?',
        puzzle:{ q:'Ein Viertel von 120 Stufen – wie viele Stufen sind das?', opts:['30','40','24'], c:0, ok:'Genau 30! Der Aufstieg beginnt.', no:'Hm. Teile 120 in 4 gleich große Teile.', hint:'120 geteilt durch 4.' } },
      { bg:'nacht', who:'narrator', say:'Oben ist es schon dunkel. Das große Licht dreht sich langsam und streicht über die Wellen wie ein glühender Pinsel.' },
      { bg:'nacht', who:'npc', npc:'🧓', name:'Lotte', say:'Mein Licht blinkt alle 15 Sekunden einmal. Zählt mit, dann zeige ich euch das Logbuch.',
        puzzle:{ q:'Alle 15 Sekunden ein Blinken: Wie oft blinkt das Licht in 1 Minute?', opts:['3','5','4'], c:2, ok:'Blink, blink, blink, blink – genau vier Mal!', no:'Das Licht stolpert. Eine Minute hat 60 Sekunden – wie oft passen 15 Sekunden hinein?', hint:'15, 30, 45, 60 …' } },
      { bg:'nacht', who:'npc', npc:'🧓', name:'Lotte', say:'Hier, die Wolke hat etwas ins Logbuch gekritzelt: einen Tintenfisch mit Notenschlüssel!' },
      { bg:'nacht', who:'fino', mood:'happy', say:'Ein Krake mit Notenschlüssel! Das kann nur Konrad sein, der Musikant mit den acht Armen. Wir müssen übers Meer!' },
      { bg:'meer', who:'npc', npc:'🧓', name:'Lotte', say:'Mein Boot liegt bereit. Wollt ihr die Segel setzen oder lieber rudern?',
        choice:{ opts:['Segel setzen','Rudern'],
                 then:['Segel hoch! Der Wind pustet so kräftig, dass Fino die Ohren flattern wie zwei Fähnchen.','Plitsch, platsch! Fino hat bald einen Rudertakt gefunden: „Und eins und zwei und eins und zwei …“'] } },
      { bg:'meer', who:'npc', npc:'🧓', name:'Lotte', say:'Fahrt immer der Nase nach, die Fische singen euch den Weg. Und bringt das E zurück, sonst blinkt mein Licht nie wieder richtig!' }
    ] },

  // ───────────────────────── 04 ─────────────────────────
  { id:'e04', title:'Konrads acht Arme', icon:'🐙', need:4,
    summary:'Der Musikant Konrad spielt mit acht Armen – und versteckt in seiner Muschelflöte etwas Goldenes.',
    scenes:[
      { bg:'meer', who:'narrator', say:'Unter dem Boot glitzert es. Blubb-blubb-bumm! Da unten spielt jemand Schlagzeug, Flöte und Geige. Gleichzeitig!' },
      { bg:'meer', who:'fino', mood:'cheer', say:'Das muss Konrad sein! Wir nehmen die Taucherglocke und fahren hinunter.' },
      { bg:'buehne', who:'npc', npc:'🐙', name:'Krake Konrad', say:'Willkommen in meinem Muschel-Theater! Acht Arme, acht Instrumente, null Pausen. Gestern Nacht ist mir ein Ton in die Flöte gehüpft und will nicht mehr raus!' },
      { bg:'buehne', who:'fino', mood:'think', say:'Ein Ton, der sich versteckt? Das ist bestimmt das E aus dem Leuchtturm. Es ist der Wolke ausgebüxt!' },
      { bg:'buehne', who:'npc', npc:'🐙', name:'Krake Konrad', say:'Es kommt nur heraus, wenn das Orchester richtig zählt. In diesem Lied spielt jeder meiner 8 Arme 5 Töne.',
        puzzle:{ q:'8 Arme spielen je 5 Töne. Wie viele Töne sind das insgesamt?', opts:['35','40','45'], c:1, ok:'Plink! Die Flöte zittert vor Freude – genau 40 Töne.', no:'Die Flöte wackelt nur. Rechne noch einmal: 8 Arme, jeder spielt 5 Töne.', hint:'8 · 5 – die 5er-Reihe!' } },
      { bg:'buehne', who:'npc', npc:'🐙', name:'Krake Konrad', say:'Und das Publikum? Jeder Seestern zahlt für den Eintritt 4 Perlen. Heute kommen 25 Seesterne.',
        puzzle:{ q:'25 Seesterne zahlen je 4 Perlen. Wie viele Perlen sind das?', opts:['120','90','100'], c:2, ok:'100 Perlen! Die Kasse klimpert wie ein kleiner Schatz.', no:'Die Kasse bleibt stumm. Denk an 25 und 4: Wie viele Viertel passen in 100?', hint:'4 · 25 – denk an 4 Münzen zu 25.' } },
      { bg:'buehne', who:'npc', npc:'🐙', name:'Krake Konrad', say:'Und jetzt der Probelauf: Auf welchem Instrument spielst du mit mir?',
        choice:{ opts:['Muschelflöte','Seetang-Harfe'],
                 then:['Tuuuu! Die Muschelflöte klingt wie ein Wal, der sich in eine Zahl verliebt hat. Konrad klatscht mit allen acht Armen.','Pling-pling! Die Seetang-Harfe kitzelt an den Fingern. Konrad wird ganz still vor Rührung.'] } },
      { bg:'buehne', who:'narrator', say:'Plopp! Aus der Muschelflöte rollt eine kleine, golden glühende Kugel, noch ganz verschlafen. Es ist das E!' },
      { bg:'buehne', who:'fino', mood:'cheer', say:'Das E ist wieder da! Ich stecke es vorsichtig in meinen Notenrucksack. Der erste gerettete Ton!' },
      { bg:'buehne', who:'npc', npc:'🐙', name:'Krake Konrad', say:'Die Wolke flog nach Norden zum Berg. Sie sah müde aus und murmelte: „Ihr armen Töne, ihr braucht endlich mal Ruhe.“' },
      { bg:'buehne', who:'du', mood:'think', say:'Ruhe? Ein seltsamer Plan für jemanden, der Töne einsammelt.' },
      { bg:'buehne', who:'fino', mood:'think', say:'Entweder ist sie ein ganz schlechter Dieb oder ein ganz besonderer. Auf zum Berg!' }
    ] },

  // ───────────────────────── 05 ─────────────────────────
  { id:'e05', title:'Der Berg der langsamen Töne', icon:'⛰️', need:5,
    summary:'Auf dem Weg zum Gipfel hilft eine Schildkröte, die nur im Tempo Largo geht.',
    scenes:[
      { bg:'berg', who:'narrator', say:'Der Berg ragt so hoch, dass seine Spitze im Nebel verschwindet. Mitten auf dem Weg liegt ein Felsbrocken. Er bewegt sich.' },
      { bg:'berg', who:'npc', npc:'🐢', name:'Theodor', say:'Guuuuten Taaaag. Ich bin Theodor. Ich spiele nur Largo. Das heißt: so langsam wie möglich.' },
      { bg:'berg', who:'fino', mood:'cheer', say:'Largo ist ein Tempo mit genau 60 Schlägen pro Minute. Ein Schlag pro Sekunde, ruhig wie ein Herzschlag!' },
      { bg:'berg', who:'npc', npc:'🐢', name:'Theodor', say:'Genaaau. Gestern kam eine graue Wolke vorbei und hat mich dreimal überholt. Sie hat sich dabei zweimal entschuldigt.' },
      { bg:'berg', who:'npc', npc:'🐢', name:'Theodor', say:'Wollt ihr auf meinem Panzer reiten? Oder lieber neben mir herwandern?',
        choice:{ opts:['Auf dem Panzer reiten','Neben Theodor herwandern'],
                 then:['Hopp! Auf dem Panzer schaukelt es sanft wie in einer Wiege mit Aussicht. Fino gähnt zweimal.','Schritt für Schritt: Theodor erzählt Geschichten und die Bergblumen nicken im Takt.'] } },
      { bg:'berg', who:'npc', npc:'🐢', name:'Theodor', say:'Wenn wir im Largo gehen, schlagen wir 60 Schläge pro Minute. Wir brauchen 5 Minuten bis zum ersten Rastplatz.',
        puzzle:{ q:'Largo: 60 Schläge in 1 Minute. Wie viele Schläge sind es in 5 Minuten?', opts:['65','300','360'], c:1, ok:'300 Schläge. Theodor nickt langsam, aber zufrieden.', no:'Theodor schüttelt den Kopf, ganz langsam. 60 Schläge, aber 5 Mal so lange …', hint:'5 · 60 – erst 5 · 6, dann eine Null dran.' } },
      { bg:'berg', who:'narrator', say:'Weiter oben steht ein Holzwegweiser: „Gipfel der Stille – 1000 m. Ihr seid auf 450 m.“' },
      { bg:'berg', who:'fino', mood:'think', say:'Das letzte Stück wird steil. Wie viele Höhenmeter fehlen uns noch bis ganz oben?',
        puzzle:{ q:'Der Gipfel liegt auf 1000 m. Wir sind auf 450 m. Wie viele Meter fehlen noch?', opts:['650','560','550'], c:2, ok:'550 Meter! Das schaffen wir, Schritt für Schritt.', no:'Hm, das stimmt nicht ganz. Rechne 1000 − 450.', hint:'Erst bis 500, dann bis 1000.' } },
      { bg:'berg', who:'narrator', say:'Oben weht ein kühler, sanfter Wind. Zwischen zwei Steinen glimmt etwas Silbernes: das F, eingewickelt in ein kleines Daunenkissen!' },
      { bg:'berg', who:'fino', mood:'cheer', say:'Das F! Mit Kissen! Wer auch immer das war, wollte, dass es dem Ton gut geht.' },
      { bg:'berg', who:'narrator', say:'An der Tür einer kleinen Wolkenhütte hängt ein Zeichen: das Zeichen für eine Pause in der Musik. Aber die Hütte ist leer.' },
      { bg:'berg', who:'fino', mood:'think', say:'Eine Pause … Warum wählt jemand, der Töne einsammelt, ausgerechnet das Zeichen für Stille? Das Rätsel wird immer größer.' },
      { bg:'berg', who:'npc', npc:'🐢', name:'Theodor', say:'Gut Ding will Weeeeile haben. Passt gut auf eure Ohren auf, ihr beiden.' }
    ] },

  // ───────────────────────── 06 ─────────────────────────
  { id:'e06', title:'Der Markt der Klangkekse', icon:'🧺', need:6,
    summary:'Auf dem Markt knuspert nichts mehr – und eine graue Wolke hat Pausenbrötchen gekauft.',
    scenes:[
      { bg:'markt', who:'narrator', say:'Auf dem Markt der Klangkekse duftet es nach Zimt, Zahlen und warmem Brot. Jeder Stand klingt anders: Der Käsestand quietscht, der Obststand pfeift.' },
      { bg:'markt', who:'fino', mood:'cheer', say:'Hier gibt es die besten Klangkekse der Insel! Einmal reinbeißen, und du hörst einen Ton!' },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Brummbrumm! Willkommen bei Bruno! Aber heute knuspert nichts. Mein G ist weg, und ohne G schmecken die Kekse nach Pappe.' },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Gestern Abend stand eine graue Wolke am Stand. Sie hat nur Pausenbrötchen gekauft. Die machen kein Knacken, nur ein sanftes Seufzen.' },
      { bg:'markt', who:'fino', mood:'think', say:'Pausenbrötchen … und das Pausenzeichen an der Hütte auf dem Berg. Das passt zusammen!' },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Hilf mir erst an der Kasse, dann erzähle ich mehr. Ein Brötchen kostet 70 Cent. Fino kauft 3 Stück.',
        puzzle:{ q:'3 Brötchen zu je 70 Cent – was kostet das zusammen?', opts:['2,10 €','1,90 €','2,40 €'], c:0, ok:'2,10 Euro! Bruno klimpert mit den Münzen.', no:'Das stimmt nicht ganz. Rechne 3 · 70 Cent und wandle die Cent in Euro um.', hint:'3 · 70 = 210 Cent. Wie viele Euro sind 210 Cent?' } },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Jetzt bist du dran! Du kaufst Klangkekse für 3,60 Euro und zahlst mit einem 5-Euro-Schein.',
        puzzle:{ q:'Du zahlst 3,60 € mit einem 5-Euro-Schein. Wie viel Wechselgeld bekommst du?', opts:['2,40 €','1,40 €','1,60 €'], c:1, ok:'1,40 Euro Wechselgeld. Gut gerechnet!', no:'Nicht ganz. Zähle von 3,60 € bis 5 € hinauf.', hint:'Von 3,60 € bis 4 € sind 40 Cent, dann noch 1 €.' } },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Welchen Klangkeks darf ich dir einpacken?',
        choice:{ opts:['Zimtkeks mit tiefem Ton','Honigkeks mit hohem Ton'],
                 then:['Brumm-brumm! Der Zimtkeks klingt wie eine Tuba im Bademantel. Fino kichert so laut, dass die Tauben vom Dach fliegen.','Piiiep! Der Honigkeks klingt hoch und süß wie ein Spatz mit Schnupfen. Der ganze Markt lächelt.'] } },
      { bg:'markt', who:'narrator', say:'Mitten im Gedränge huscht etwas Kleines, Graues zwischen den Ständen hindurch und zieht eine Spur aus feinen Wolkenfäden hinter sich her.' },
      { bg:'markt', who:'fino', mood:'think', say:'Da! Sie war hier. Wenn wir den Fäden folgen, kommen wir zum Trommelwald!' },
      { bg:'markt', who:'npc', npc:'🐻', name:'Bäcker Bruno', say:'Im Trommelwald wohnt Dachs Dörte. Sag ihr: Bruno schickt euch. Und bringt mir mein G zurück!' },
      { bg:'markt', who:'du', mood:'cheer', say:'Versprochen! Und danach bekommt jeder Ton einen eigenen Keks.' }
    ] },

  // ───────────────────────── 07 ─────────────────────────
  { id:'e07', title:'Der Trommelwald', icon:'🥁', need:8,
    summary:'Im Trommelwald ist es ganz leise geworden – und im dicksten Baum brummt das G.',
    scenes:[
      { bg:'wald', who:'narrator', say:'Im Trommelwald wachsen Bäume mit hohlen Stämmen. Wenn der Wind weht, trommeln sie: bum, bum, tschak, bum.' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Seid gegrüßt! Ich bin Dörte, Dachs und Schlagzeugerin. Man nennt mich auch Frau Wirbel. Seid ihr die, die Bruno schickt?' },
      { bg:'wald', who:'fino', mood:'happy', say:'Genau! Wir suchen das G. Und die graue Wolke.' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Die Wolke war gestern hier. Sie hat sich vor jeden Baum gestellt und geflüstert: „Pssst, schlaft.“ Seitdem trommelt der Wald nur noch ganz leise.' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Zum Aufwecken brauche ich das Geheimmuster der Bäume: 1, 2, 4, 8, 16 …',
        puzzle:{ q:'Welche Zahl kommt als Nächstes? 1, 2, 4, 8, 16, …', opts:['32','24','20'], c:0, ok:'Bum-bum-tschak! Der Wald wacht auf und die Stämme wackeln im Takt.', no:'Der Wald schnarcht weiter. Schau: Was passiert mit jeder Zahl, damit die nächste entsteht?', hint:'Jede Zahl wird verdoppelt.' } },
      { bg:'wald', who:'fino', mood:'think', say:'Hört ihr das? Zwischen den Trommelschlägen brummt etwas ganz leise. Das ist das G! Es steckt im dicksten Baum!' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Der dicke Baum öffnet sich nur, wenn man den Takt kennt. Ein Takt hat 4 Schläge, wir spielen 12 Takte.',
        puzzle:{ q:'12 Takte mit je 4 Schlägen – wie viele Schläge sind das insgesamt?', opts:['44','48','52'], c:1, ok:'48 Schläge! Der Baum knarzt und öffnet sich einen Spalt.', no:'Der Baum knarzt nur. Rechne 12 · 4 noch einmal.', hint:'10 · 4 und noch 2 · 4 dazu.' } },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Und wie holen wir das G jetzt heraus? Mit einem Wirbel oder mit einem lauten Schlag?',
        choice:{ opts:['Mit einem Wirbel','Mit einem lauten Schlag'],
                 then:['Brrrrrr! Das G kitzelt es wohl: Der Stamm bebt vor Lachen und das G kullert heraus.','BUMM! Der Wald hält kurz den Atem an – dann hüpft das G wie ein Gummiball aus der Rinde.'] } },
      { bg:'wald', who:'narrator', say:'Das G landet weich im Moos, glüht golden und summt zufrieden vor sich hin. Fino packt es in den Notenrucksack.' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Nehmt diesen Trommelstock mit. Er macht auch ohne Trommel ein bisschen Rhythmus. Das Glück braucht Takt!' },
      { bg:'wald', who:'narrator', say:'Plötzlich verstummt der Wald. Hoch über den Baumwipfeln schwebt eine zarte Stimme: „Schlaft, ihr Müden … pssst … schlaft.“' },
      { bg:'wald', who:'fino', mood:'think', say:'Die Stimme kommt von oben! Wer kann uns zu den Wolken bringen?' },
      { bg:'wald', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Papagei Paul! Er hat einen Drachen so groß wie ein Segel und einen Schnabel so groß wie sein Ego.' },
      { bg:'wald', who:'du', mood:'cheer', say:'Dann nichts wie zurück zum Strand!' }
    ] },

  // ───────────────────────── 08 ─────────────────────────
  { id:'e08', title:'Pauls Wolkenflug', icon:'🪁', need:9,
    summary:'Mit Pauls Riesendrachen geht es hoch hinauf zu den Wolkenbetten.',
    scenes:[
      { bg:'strand', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Na endlich! Ich habe meinen Drachen mit Sonnenblumenkernen beladen. Das ist Wissenschaft!' },
      { bg:'strand', who:'fino', mood:'cheer', say:'Paul, du bist unser Pilot! Die Stimme kam aus den Wolken. Wir müssen hoch hinaus.' },
      { bg:'strand', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Pah, ich fliege schneller als ein Gedanke! Naja. Als ein Gedanke nach dem Mittagessen. Einsteigen!' },
      { bg:'himmel', who:'narrator', say:'Der Drachen steigt, steigt, steigt. Unter ihnen wird die Insel zum Klecks, das Meer zur blauen Decke.' },
      { bg:'himmel', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Der Drachen steigt jede Minute 30 Meter. Wir fliegen 7 Minuten. Kann jemand mitrechnen? Mein Kopf ist beim Futter.',
        puzzle:{ q:'30 m pro Minute, 7 Minuten lang. Wie hoch sind wir dann?', opts:['180 m','240 m','210 m'], c:2, ok:'210 Meter! Von hier sieht man schon die Gipfel der Berge.', no:'Der Drachen schwankt. Rechne 7 · 30 noch einmal.', hint:'7 · 3 = 21, und dann eine Null dran.' } },
      { bg:'himmel', who:'narrator', say:'Um sie herum schweben Wolken wie Kissen. Einige sind weiß, einige gelb – und eine davon ist grau.' },
      { bg:'himmel', who:'fino', mood:'think', say:'Dort drüben! Die kleine graue Wolke! Und um sie herum liegen Wolkenbetten, in denen goldene Töne schlafen.' },
      { bg:'himmel', who:'npc', npc:'☁️', name:'Graue Wolke', say:'Pssst … schlaft schön, ihr Lieben. Ihr habt so lange gespielt, ohne ein einziges Mal auszuruhen.' },
      { bg:'himmel', who:'du', mood:'think', say:'Sie flüstert wie bei einem Gutenachtlied. Das sieht gar nicht nach Diebstahl aus.' },
      { bg:'himmel', who:'narrator', say:'Als die Wolke die Besucher bemerkt, huscht sie davon wie ein Seufzer. Zurück bleibt ein Wolkenbett mit dem A, das leise summt.' },
      { bg:'himmel', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Zur Feier des Tages teile ich meine Vorräte: Ich habe 12 Sonnenblumenkerne und gebe Fino ein Drittel davon ab.',
        puzzle:{ q:'Ein Drittel von 12 Kernen – wie viele Kerne bekommt Fino?', opts:['6','4','3'], c:1, ok:'4 Kerne! Fino macht ein Gesicht, als hätte er einen Schatz gewonnen.', no:'Paul rückt die Kerne enger zusammen. Teile 12 in 3 gleich große Häufchen.', hint:'12 geteilt durch 3.' } },
      { bg:'himmel', who:'fino', mood:'cheer', say:'Das A ist gerettet! In meinem Rucksack liegen jetzt E, F, G und A. Fehlen noch C, D und womöglich bald das H.' },
      { bg:'himmel', who:'npc', npc:'🦜', name:'Papagei Paul', say:'Zeit für die Eule Ottilie! Sie schaut jede Nacht durch ihr Fernrohr und sieht alles. Außer wenn sie schläft.' }
    ] },

  // ───────────────────────── 09 ─────────────────────────
  { id:'e09', title:'Die Sternwarte der Eule', icon:'🔭', need:10,
    summary:'Ottilie kennt die graue Wolke – und das letzte H verschwindet vor ihren Augen.',
    scenes:[
      { bg:'nacht', who:'narrator', say:'Es ist Nacht. Auf einem Hügel steht ein Turm mit einem riesigen Fernrohr. Die Sterne blinken wie kleine Triangeln.' },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Schuhuu! Ich bin Ottilie, Sternenwächterin. Ich sehe alles, was nachts glitzert. Und alles, was nachts schweigt.' },
      { bg:'nacht', who:'fino', mood:'think', say:'Ottilie, wir suchen eine kleine graue Wolke, die Töne einsammelt.' },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Ach, die Pausa! Sie ist keine Diebin. Sie ist die Wolke aus der Stille zwischen den Tönen. Alle rufen ihr zu: „Pst, sei still!“' },
      { bg:'nacht', who:'du', mood:'think', say:'Dann wollen wir sie nicht jagen, sondern ihr zuhören.' },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Sie kommt, wenn das Sternbild Posaune hoch am Himmel steht. Es hat 6 Reihen zu je 7 Sternen. Zählt sie, dann stimmt mein Fernrohr.',
        puzzle:{ q:'6 Reihen mit je 7 Sternen. Wie viele Sterne sind das?', opts:['48','36','42'], c:2, ok:'42 Sterne! Das Fernrohr summt zufrieden.', no:'Das Fernrohr flackert. Rechne 6 · 7 noch einmal.', hint:'Die 7er-Reihe: 7, 14, 21, 28, 35 …' } },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Jetzt ist es 21:30 Uhr. Um Mitternacht, also um 24:00 Uhr, steht die Posaune ganz oben.',
        puzzle:{ q:'Es ist 21:30 Uhr. Wie lange dauert es bis 24:00 Uhr?', opts:['2 h 30 min','3 h 30 min','2 h'], c:0, ok:'Zweieinhalb Stunden. Zeit für Kakao!', no:'Das passt noch nicht. Zähle von 21:30 bis 22:00, dann Stunde für Stunde bis 24:00.', hint:'21:30 → 22:00 → 23:00 → 24:00.' } },
      { bg:'nacht', who:'narrator', say:'Die Zeit vergeht mit Sternschnuppen-Zählen und Kräuterkakao. Kurz vor Mitternacht richtet Ottilie das Fernrohr aus.' },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Durch welches Fernrohr wollt ihr schauen?',
        choice:{ opts:['Das silberne','Das goldene'],
                 then:['Im silbernen Fernrohr sieht man den Mond so nah, dass Fino ihm fast die Hand schütteln kann.','Im goldenen Fernrohr schimmern die Sterne wie Honig. Fino leckt sich unwillkürlich die Lippen.'] } },
      { bg:'nacht', who:'narrator', say:'Da! Eine kleine graue Wolke gleitet über den Berghang. In ihren Armen trägt sie einen leise glimmenden Ton: das H, wie ein schlafendes Baby.' },
      { bg:'nacht', who:'fino', mood:'sad', say:'Jetzt hat sie auch das letzte geholt. Die Zahlenglocke wird morgen ganz still sein.' },
      { bg:'nacht', who:'npc', npc:'🦉', name:'Eule Ottilie', say:'Pausa verschwindet zum Wasserfall am Berg. Dahinter liegt die Stille Höhle. Aber der Eingang öffnet sich nur mit einem Rhythmus-Rätsel.' },
      { bg:'nacht', who:'du', mood:'cheer', say:'Dann brauchen wir den besten Rätselknacker der Insel. Tick-9!' }
    ] },

  // ───────────────────────── 10 ─────────────────────────
  { id:'e10', title:'Das Pausen-Geheimnis', icon:'🗝️', need:12,
    summary:'In Tick-9s Werkstatt wird ein Rhythmus-Schloss geknackt – und eine große Idee wird geboren.',
    scenes:[
      { bg:'labor', who:'narrator', say:'In Tick-9s Werkstatt blinkt und piept es. Auf dem Tisch liegt der Rhythmus der Stillen Höhle, abgeschrieben von Ottilies Fernrohr.' },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep. Dieses Rätsel besteht aus Tönen UND Pausen. Pausen zählen genauso wie Noten. Ich bin begeistert!' },
      { bg:'labor', who:'fino', mood:'think', say:'Genau! Jede Pause hat eine Länge: Eine Viertelpause dauert 1 Schlag, eine halbe Pause 2 Schläge, eine ganze Pause 4.' },
      { bg:'labor', who:'du', mood:'think', say:'Also ist Stille gar nicht leer. Stille ist ein Teil der Musik!' },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep! Das erste Rad will wissen, wie fein wir teilen können.',
        puzzle:{ q:'Wie viele Achtelnoten dauern zusammen so lang wie eine Viertelnote?', opts:['2','4','8'], c:0, ok:'Zwei Achtel pro Viertel! Das erste Rad dreht sich.', no:'Das Rad klemmt. Eine Achtelnote ist halb so lang wie eine Viertelnote.', hint:'Halbiere die Viertelnote.' } },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Das zweite Rad liebt Brüche. Ein Takt ist ein Ganzes, ½ und ¼ davon sind schon besetzt.',
        puzzle:{ q:'Ein Takt ist 1 Ganzes. Besetzt sind schon ½ und ¼. Welcher Teil fehlt noch?', opts:['½','¼','¾'], c:1, ok:'Ein Viertel fehlt! Das zweite Rad rastet ein.', no:'Das Rad rutscht ab. ½ ist dasselbe wie 2 Viertel – wie viele Viertel sind schon besetzt?', hint:'Ein Ganzes besteht aus 4 Vierteln.' } },
      { bg:'labor', who:'fino', mood:'cheer', say:'Zwei Räder gedreht! Jetzt noch eines: die Karte zur Höhle hinter dem Wasserfall.' },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep. Der Pfad zum Wasserfall ist 475 m lang, dahinter sind es noch 325 m bis zur Höhle.',
        puzzle:{ q:'475 m + 325 m – wie weit ist es insgesamt?', opts:['790 m','810 m','800 m'], c:2, ok:'800 Meter! Die Karte leuchtet silbern auf.', no:'Die Karte flackert. Rechne 475 + 325 noch einmal.', hint:'475 + 25 = 500, und dann noch 300.' } },
      { bg:'labor', who:'narrator', say:'Wumms! Ein dünner Pfad aus Licht führt über den Berg zum Wasserfall. Die Tür des Rätsels ist geknackt.' },
      { bg:'labor', who:'fino', mood:'think', say:'Wie sollen wir Pausa begrüßen, ohne sie zu erschrecken?',
        choice:{ opts:['Leise hinschleichen','Ganz leise summen'],
                 then:['Schleich-schleich. Tick-9 knirscht trotz Filzpantoffeln, aber Fino hält sich mit beiden Pfoten die Schnauze zu.','Hmmmm … Das Summen legt sich wie ein weicher Teppich auf die Felsen. Tick-9 summt mit: tick-hmm, tack-hmm.'] } },
      { bg:'labor', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep. Ich habe eine Theorie: Ohne Pausen gerät jede Melodie ins Stolpern. Das habe ich selbst bemerkt, als der Takt weg war.' },
      { bg:'labor', who:'fino', mood:'happy', say:'Genau das ist die Lösung! Pausa wollte den Tönen nur Pausen schenken, aber sie hat die Musik dabei still gemacht.' }
    ] },

  // ───────────────────────── 11 ─────────────────────────
  { id:'e11', title:'Die Stille Höhle', icon:'🌌', need:13,
    summary:'Hinter dem Wasserfall wartet Pausa – und endlich versteht man, warum die Töne verschwunden sind.',
    scenes:[
      { bg:'hoehle', who:'narrator', say:'Hinter dem Wasserfall liegt eine Höhle, in der nichts hallt. Kein Tropfen, kein Echo. Doch ganz leise summt etwas.' },
      { bg:'hoehle', who:'fino', mood:'think', say:'Ein Tor aus weichem Nebel. Es will wissen, wie lang unsere Stille ist: eine ganze Pause und eine halbe Pause zusammen.',
        puzzle:{ q:'Eine ganze Pause dauert 4 Schläge, eine halbe Pause 2 Schläge. Wie viele Schläge sind das zusammen?', opts:['5','8','6'], c:2, ok:'Sechs Schläge Stille! Das Nebeltor teilt sich wie ein Vorhang.', no:'Das Tor bleibt zu. Zähle die Schläge der beiden Pausen zusammen.', hint:'4 + 2.' } },
      { bg:'hoehle', who:'narrator', say:'Dahinter liegen hunderte kleine Wolkenkissen und Lichterketten aus Glühwürmchen. Auf den Kissen schlafen drei golden glimmende Töne: C, D und H.' },
      { bg:'hoehle', who:'npc', npc:'☁️', name:'Pausa', say:'Pssst! Bitte nicht so laut … Ach, ihr seid es. Es tut mir so leid! Ich wollte nichts stehlen. Ich wollte nur, dass die Töne mal Urlaub machen.' },
      { bg:'hoehle', who:'npc', npc:'☁️', name:'Pausa', say:'Alle spielen immer, immer, immer. Kein Ton darf ausruhen. Und mich schimpfen alle: „Pst! Sei still!“ Dabei gehöre ich doch auch zur Musik.' },
      { bg:'hoehle', who:'fino', mood:'sad', say:'Oh, Pausa. Wir dachten, du bist eine Diebin. Dabei hast du den Tönen Kissen genäht.' },
      { bg:'hoehle', who:'du', mood:'happy', say:'Ohne Pausen wäre Musik nur Lärm. Du bist die halbe Magie jedes guten Liedes!' },
      { bg:'hoehle', who:'npc', npc:'☁️', name:'Pausa', say:'Meinst du das wirklich? Dann hilf mir, mein Kissenlager zu zählen. Ich habe für jeden der 7 Töne 8 Kissen genäht.',
        puzzle:{ q:'7 Töne mit je 8 Kissen – wie viele Kissen sind das insgesamt?', opts:['54','56','63'], c:1, ok:'Sechsundfünfzig! Du hast wirklich Ahnung von Zahlen.', no:'Hm, das passt nicht ganz. Rechne 7 · 8 noch einmal.', hint:'5 · 8 = 40, und dann noch 2 · 8.' } },
      { bg:'hoehle', who:'npc', npc:'☁️', name:'Pausa', say:'Ich hätte nie gedacht, dass jemand mit mir spielen will. Wollt ihr die Töne wecken? Aber ganz sanft!',
        choice:{ opts:['Mit leisem Summen','Mit einem Fingerschnipsen'],
                 then:['Hmmmm … Das Summen kitzelt die Töne wach. Sie gähnen so lange, dass Pausa kichern muss.','Schnipp! Der kleine Knall weckt die Töne – und zwei von ihnen hüpfen sofort in die Luft.'] } },
      { bg:'hoehle', who:'narrator', say:'C, D und H blinzeln, gähnen und strecken sich. Zusammen mit E, F, G und A aus dem Rucksack sind endlich alle sieben Töne wieder beisammen.' },
      { bg:'hoehle', who:'fino', mood:'cheer', say:'Alle sieben! Und morgen Abend ist das Insel-Konzert auf der großen Bühne. Pausa, du musst mitspielen!' },
      { bg:'hoehle', who:'npc', npc:'☁️', name:'Pausa', say:'Ich? Aber ich mache doch gar keinen Ton. Ich bin ja nur Stille.' },
      { bg:'hoehle', who:'du', mood:'cheer', say:'Genau. Und wir zeigen allen, wie wichtig das ist!' }
    ] },

  // ───────────────────────── 12 ─────────────────────────
  { id:'e12', title:'Das große Zahlenkonzert', icon:'🎼', need:15,
    summary:'Das ganze Eiland trifft sich zum Konzert – und die Stille bekommt ihren großen Auftritt.',
    scenes:[
      { bg:'buehne', who:'narrator', say:'Am Abend füllt sich die große Insel-Bühne. Laternen blinken, Paul prüft zum zwanzigsten Mal sein Kostüm und Konrad schleppt acht Trompeten heran.' },
      { bg:'buehne', who:'npc', npc:'🧓', name:'Lotte', say:'Alle Schiffe sind eingelaufen! Ich habe die Gäste gezählt: 400 vom Strand, 350 aus dem Dorf und 250 aus den Bergen.',
        puzzle:{ q:'400 + 350 + 250 = ?', opts:['900','1000','1100'], c:1, ok:'Tausend Gäste! Die Bühne wackelt vor Vorfreude.', no:'Hm, das stimmt noch nicht. Rechne zuerst 400 + 350, dann noch 250 dazu.', hint:'400 + 350 = 750. Und dann noch 250.' } },
      { bg:'buehne', who:'npc', npc:'🦡', name:'Dachs Dörte', say:'Alle sollen sitzen! Ich habe 50 Reihen mit je 20 Stühlen aufgestellt. Reicht das für die Gäste?',
        puzzle:{ q:'50 Reihen mit je 20 Stühlen – wie viele Stühle sind das?', opts:['1000','700','1500'], c:0, ok:'Genau 1000 Stühle – für jeden Gast einer!', no:'Ein paar Gäste würden stehen. Rechne 50 · 20 noch einmal.', hint:'5 · 2 = 10, dann zwei Nullen dran.' } },
      { bg:'buehne', who:'npc', npc:'☁️', name:'Pausa', say:'Ich zittere wie ein Wölkchen im Wind. Was, wenn ich alles verderbe?' },
      { bg:'buehne', who:'du', mood:'happy', say:'Du spielst die wichtigste Stelle: die Pause vor dem großen Finale. Die Stille macht den Knall erst groß.' },
      { bg:'buehne', who:'npc', npc:'🤖', name:'Tick-9', say:'Piep! Das Stück hat 3 Teile, jeder Teil 8 Takte, jeder Takt 4 Schläge. Ich zähle ein, wenn ich die Gesamtzahl kenne.',
        puzzle:{ q:'3 Teile mit je 8 Takten zu je 4 Schlägen. Wie viele Schläge hat das ganze Stück?', opts:['108','84','96'], c:2, ok:'96 Schläge! Tick-9 piept vor Stolz und zählt ein.', no:'Piep-piep! Rechne zuerst die Schläge eines Teils: 8 · 4.', hint:'Ein Teil hat 8 · 4 = 32 Schläge. Und davon 3 Teile.' } },
      { bg:'buehne', who:'narrator', say:'Fino hebt den Notenrucksack. Sieben goldene Kugeln steigen auf und schweben an ihre Plätze: C, D, E, F, G, A, H.' },
      { bg:'buehne', who:'fino', mood:'cheer', say:'Wie soll das Finale beginnen? Mit einem Trommelwirbel oder mit einer Pause?',
        choice:{ opts:['Mit einem Trommelwirbel','Mit einer Pause'],
                 then:['Brrrrrr! Dörtes Trommelwirbel lässt die Bühnenbretter beben und alle recken die Hälse.','Ganz still. Tausend Gäste halten den Atem an. Dann erklingt der erste Ton – und er klingt doppelt so schön.'] } },
      { bg:'buehne', who:'narrator', say:'Tick-9 zählt ein, Konrad trommelt mit acht Armen, Paul krächzt (fast) im Takt. Und mittendrin: eine Pause, so perfekt gesetzt, dass alle Gänsehaut bekommen.' },
      { bg:'buehne', who:'npc', npc:'☁️', name:'Pausa', say:'Sie klatschen … für mich? Das ist das erste Mal, dass jemand für die Stille klatscht!' },
      { bg:'buehne', who:'fino', mood:'cheer', say:'Die Zahlenglocke läutet wieder! Sieben Töne, und dazwischen Pausen. Die Insel klingt, als wäre sie neu erfunden.' },
      { bg:'buehne', who:'narrator', say:'Seitdem gehört zu jeder Melodie der Zahleninsel eine kleine Pause. Und Pausa ist Ehrenmitglied des Orchesters und schläft nie wieder allein.' },
      { bg:'buehne', who:'fino', mood:'happy', say:'Danke, {name}! Ohne dich hätten wir den Takt nie wiedergefunden. Und ich glaube, das war erst unser erstes Konzert …' }
    ] }
];
